---
title: "Capítulo 9.4: Interações"
---

# ***Variáveis fictícias*** {#sec-section1}

**Título**: Variáveis fictícias: explicação dos termos de interação

**Apresentador(es)**: Ben Lambert

Então, vamos pensar no exemplo que tivemos no último vídeo. Então, digamos que estamos interessados ​​em saber como as taxas salariais variam entre, digamos, pessoas do sexo masculino e feminino. Portanto, a ideia é regredirmos o salário, digamos, agora que estamos assumindo implicitamente que temos todas essas outras variáveis, então não vou incluí-las explicitamente. Teremos apenas alfa mais, digamos, beta-1 vezes o número de anos de educação mais beta-2 vezes nosso tipo de variável de sexo, onde nossa variável de sexo assume o valor de 1 se o indivíduo for mulher e leva em um valor nulo se o indivíduo for do sexo masculino. Mas depois incluímos outro termo, que foi, digamos, beta-3, onde multiplicamos o sexo pela educação. Portanto, a ideia é que tenhamos recolhido todas estas variáveis ​​em todos os nossos indivíduos na população ou na nossa amostra, e incluímos um termo multiplicativo na nossa especificação de regressão.

Então, o que esse termo multiplicativo significa? Como interpretamos este beta-3? Bem, vamos pensar novamente sobre qual seria esse tipo de salário médio para uma mulher e compará-lo com o salário médio para um homem. Portanto, o salário médio de uma mulher, se ela tivesse um determinado número de anos de educação, seria alfa mais beta-1 vezes o número de anos de educação que ela teve, mais, bem, esta variável sexual agora assume o valor de 1, então tenho mais beta-2. E agora nossa variável sexo aqui também está assumindo o valor 1, então tenho mais beta-3 vezes o número de anos de educação, ok? E então podemos simplificar isso se tivéssemos notado que nosso alfa e nosso beta-2 são ambos constantes aqui. Então você está escrevendo ambos no início do modelo. Obtemos uma espécie de alfa mais beta-2, digamos, e então reconhecemos que temos essencialmente dois termos educacionais. Temos este e este, então eu poderia simplificá-los também, escrevendo-os ou combinando-os. Acabei de obter beta-1 mais beta-3 vezes o número de anos de educação.

Ok, então isso é para o caso feminino. O que temos para o homem? Portanto, a ideia para o tipo de homens na nossa amostra é que a taxa salarial média é dada por alfa mais beta-1 vezes o número de anos de educação porque a nossa variável sexo assume um valor zero, então estes dois segundos termos na verdade cancelam ou não existem para o homem. Portanto, agora podemos pensar sobre quais foram os efeitos da nossa variável sexo na nossa especificação e na nossa interpretação.

Então, o que o beta-2 representa aqui? Bem, beta-2 representa o prêmio adicional que as mulheres teriam sobre os homens se tivessem zero anos de educação, porque se tivessem zero anos de educação, então ambos os termos desapareceriam, e a única diferença entre os homens e as mulheres seriam, de fato, nosso beta-2. Assim como você provou no último vídeo, esse é na verdade o prêmio salarial que as mulheres fazem, é superior ao dos homens neste caso de ter zero anos de educação.

Ok, então o que o beta-3 representa? Bem, note que a única diferença entre estas duas especificações em termos da variável educação é que essencialmente o efeito parcial da educação para as mulheres foi potenciado por um valor beta-3 relativamente aos homens. Então, o que isso significa? Pois bem, se o beta-3 foi superior a zero, significa que o efeito adicional de mais um ano de escolaridade para as mulheres foi, de fato, maior do que para os homens. Se fosse inferior a zero, então seria o contrário, pelo que os efeitos adicionais de ter mais um ano de educação em média tenderiam a causar um aumento menor no salário feminino do que no masculino. Portanto, podemos pensar sobre o que esses termos cruzados significam em nossa especificação de regressão. Bem, essencialmente o que eles querem dizer é que se eu estiver interagindo uma variável fictícia com uma variável contínua, isso nos permitirá ter inclinações diferentes daquela variável contínua específica entre os dois valores diferentes que nossa variável fictícia pode assumir. Então, essa é uma suposição bastante inadequada de se fazer em uma série de situações diferentes. Nesta situação específica, pode-se supor que pode haver um efeito diferente da educação entre homens e mulheres, mas há uma série de outras maneiras pelas quais isso pode ser verdade em outros tipos de modelos.

------------------------------------------------------------------------

# ***Variáveis contínuas*** {#sec-section2}

**Título:** Variáveis contínuas: interpretação do termo de interação

**Apresentador(es):** Ben Lambert

Olá! Neste vídeo, eu queria explicar qual é o tipo de interpretação quando temos duas variáveis ​​contínuas multiplicadas em algum tipo de modelo de regressão. Ok, então vamos pensar em um exemplo específico. A única questão aqui é que digamos que estávamos tentando explicar o nível de vendas de uma empresa, mas estamos tentando fazer isso em termos, digamos, do efeito do preço e digamos do efeito da publicidade. Sim, esse pode ser o nível de gastos com publicidade da empresa e é apenas o preço definido pela empresa para um produto específico. Portanto, a teoria tradicional esperaria que tivéssemos uma curva de demanda com inclinação descendente, então esperaríamos que o beta-1 fosse menor que zero, porque se você baixar o preço, as vendas aumentarão, e esperaríamos que, se gastarmos mais em publicidade, as vendas também tendem a ser maiores. Então temos beta-1 sendo menor que 0 e beta-2 sendo maior que 0, mas digamos que incluímos um terceiro termo aqui, que é beta-3, e agora incluímos o produto do preço e os gastos da empresa em publicidade. Que interpretação podemos realmente dar a este beta-3? Bem, vamos pensar nisso em duas situações diferentes.

**(Primeira Situação)**: Então, digamos que a empresa estava, digamos, gastando US\$ 100.000 em publicidade, e vamos pensar sobre quais seriam as vendas esperadas da empresa nessa situação. Bem, a ideia é que o nível de vendas da empresa que esperaríamos se a publicidade fosse de US\$ 100.000 seria igual a alfa mais beta-1 vezes o preço, mais agora obteremos US\$ 100.000 vezes beta-2 para este terceiro mandato, e então receberemos mais US\$ 100.000 vezes beta-3 vezes o preço. Ok, então o que isso nos mostra?

Bem, podemos realmente pensar sobre o preço efetivo porque o preço aparece duas vezes em nosso modelo aqui. Podemos combinar as variáveis ​​de preço para criar uma espécie de efeito agregado de preço. Então aqui teríamos o efeito agregado do preço seria beta-1 mais US\$ 100.000 vezes beta-3, e então tudo isso seria multiplicado pelo preço.

Portanto, uma interpretação é beta-3, e que sinal esperaríamos que beta-3 tivesse neste caso? Bem, na verdade esperaríamos que beta-3 fosse maior que zero. Por que esperaríamos isso? Bem, a ideia aqui é que se você gastar mais dinheiro em publicidade, isso tende a diminuir a sensibilidade dos seus consumidores às mudanças de preço daquele produto. Então observe que isso aparece porque beta-1 é menor que zero. Então, se adicionarmos US\$ 100.000 vezes beta-3, onde beta-3 é maior que zero, então a ideia é que na verdade diminuímos o tipo de sensibilidade dos consumidores às mudanças de preço, ou tornamos nossos clientes menos reativos ao preço, que é algo que você poderia esperar que as vendas das empresas exibissem. Certo? Você pode esperar que, se gastar mais dinheiro em publicidade, aumente o valor da marca ou o tipo de efeito não tangível que os consumidores consideram quando pensam em sua marca, o que pode torná-los menos sensíveis ao preço. Ok, então é isso que o beta-3 está representando neste caso.

**(Segunda situação)**: Vamos pensar em outro exemplo em que digamos que o nível de preço foi definido como dez e digamos como poderíamos prever as vendas da empresa nesse caso. Então a ideia é que as vendas da empresa, em média, quando o preço fosse dez, seriam iguais a alfa mais dez vezes beta-1 mais beta-2 vezes o nível de publicidade, que não especificamos. Além disso, agora podemos ter dez vezes beta-3 vezes o nível de publicidade. Portanto, observe que novamente aqui temos dois termos que possuem essencialmente a mesma variável. Podemos combiná-los e agora temos um efeito agregado de publicidade sendo beta-2 mais dez vezes beta-3. Então, o que o beta-3 representa neste caso?

Bem, lembre-se que descobrimos no primeiro exemplo que beta-3, em teoria, deveria ser maior que zero. Bem, o que isso diz neste caso? Diz que se o seu preço for mais alto (lembre-se que os preços são representados por este dez aqui), então o efeito da publicidade tende a ser maior. Então esse pode ser o caso. Se você tiver um produto com preço premium mais alto, talvez precise demonstrar aos consumidores que vale a pena comprá-lo, de modo que o efeito da publicidade seja maior do que se você tivesse, digamos, um produto de baixo preço que os consumidores iriam buscar de qualquer maneira.

Então, beta-3 em geral, o que isso significa? O que aprendemos ao considerar esses dois casos? Bem, isso mostra que o efeito do preço depende do nível de gastos com publicidade, e o efeito da publicidade tende a ser determinado ou a ser afetado pelo nível de preço, então beta-3 é uma espécie de forma de ajustar o efeito do preço e da publicidade para ter em conta os seus efeitos multiplicativos um sobre o outro.
