---
title: "Capítulo 1.4: Arquitetura Genética Compartilhada"
---

# ***Arquitetura genética compartilhada entre transtornos psiquiátricos*** {#sec-section1}

**Título**: Arquitetura genética compartilhada entre transtornos psiquiátricos

**Apresentador**: Andrew Grotzinger, PhD (Institute for Behavioral Genetics, University of Colorado Boulder)

Olá a todos, meu nome é Andrew Grotzinger e falaremos hoje sobre a arquitetura genética compartilhada entre transtornos psiquiátricos. Vou dividir minha palestra em cinco seções, começando com o problema da comorbidade de forma mais geral e como os estudos familiares têm sido usados ​​para entender a comorbidade, e depois passarei a falar sobre como os métodos genômicos têm sido usados ​​mais recentemente para entender a comorbidade: começando com a análise ao nível do genoma, seguida pelo nível da variante genética e terminando com estudos mecanicistas. Em seguida, encerraremos falando sobre os próximos passos nos esforços do Cross-Disorder.

Então, começando pelo problema da comorbidade e pelos estudos familiares: começo aqui mostrando todos os indivíduos com transtornos mentais neste espaço azul. Entre esse grupo de pessoas, cerca de dois terços atenderão aos critérios para um segundo transtorno durante a vida, 51% atenderão aos critérios para um terceiro transtorno e 41% atenderão aos critérios para um quarto transtorno, indicando alguns caminhos compartilhados bastante amplos entre esses transtornos.

Estudos probando ou estudos familiares, que são frequentemente retratados usando este esquema aqui, com os pais no topo e os filhos na parte inferior, identificaram relações recíprocas em uma série de transtornos. E por relacionamentos recíprocos, quero dizer que a prole corre risco não apenas pelo transtorno presente no pai, mas também por esse transtorno alternativo. Essas relações foram identificadas para transtorno bipolar e esquizofrenia, transtorno bipolar e depressão maior, autismo e transtorno bipolar e esquizofrenia, e uma responsabilidade geral compartilhada entre transtornos de ansiedade maiores. Indicando que esses transtornos em geral não se reproduzem de forma verdadeira.

Neste estudo de 2012, eles analisaram esses cinco transtornos nos pais no eixo x e o odds ratio de a criança desenvolver um transtorno específico no eixo y, com o nulo em 1 nesta linha tracejada vermelha. O que eles consideram consistente com esses estudos probando é que as crianças corriam realmente o risco de ter qualquer transtorno, e não apenas o transtorno presente nos pais.

Estudos com gêmeos têm sido usados ​​para acompanhar essas descobertas, observando correlações genéticas específicas entre transtornos, o que é mostrado aqui na metade inferior desta matriz deste artigo de revisão de 2019.

Uma coisa para a qual quero chamar sua atenção é que muitas dessas células estão listadas como NA, e isso ocorre porque, para um estudo com gêmeos estimar as correlações genéticas entre esses transtornos, ambos os transtornos teriam que estar presentes em um dos gêmeos. Como muitos desses transtornos são realmente muito raros, ou mesmo mutuamente exclusivos, isso muitas vezes não é possível. Considerando que, para métodos genômicos (em azul aqui acima da diagonal), você verá que as correlações genéticas são estimadas em todo o espaço psiquiátrico e isso é possível porque o uso de métodos genômicos, como a regressão bivariada do escore de LD, introduzido neste artigo da Nature Genetics em 2015 , somos capazes de estimar correlações genéticas entre amostras com vários graus de sobreposição de amostras, incluindo amostras mutuamente exclusivas, de modo que as próprias amostras possam ser independentes. Agora você pode observar as correlações genéticas para esses transtornos mais raros que provavelmente não serão medidos na mesma amostra.

Dadas as altas taxas de correlações genéticas entre os transtornos, isso nos motivou a desenvolver a modelagem de equações estruturais genômicas, que introduzimos neste artigo da Nature Human Behaviour, que é uma estrutura para modelar os padrões de associações genéticas em diferentes conjuntos de características.

Quero passar agora pelas diferentes iterações de modelagem de fatores que fizemos usando SEM genômico para transtornos psiquiátricos. Começando com esse modelo de fator inicial, encaixamos naquele artigo da Nature Human Behaviour para esses cinco transtornos principais, onde identificamos esse fator p abrangente.

Chamamos isso de p em parte apenas porque era um “placeholder”, visto que tínhamos apenas esses cinco transtornos que tinham capacidade suficiente para serem incluídos no modelo na época, o que é algo que queríamos melhorar em iterações futuras, que pudemos fazemos neste artigo da Cell de 2019 para o segundo grande esforço do Cross-Disorder, onde examinamos a arquitetura multivariada desses oito transtornos para identificar um fator compulsivo, um fator de transtorno psicótico e um fator do neurodesenvolvimento.

Atualizamos esse modelo ainda mais para incluir esses três transtornos adicionais mostrados em vermelho para esta preprint do medRxiv em 2020. Com a inclusão desses três transtornos, estamos agora tendo esse quarto fator de transtornos internalizantes, que mapeia muito bem a grande parte do trabalho de modelagem de fatores fenotípicos que tem sido feito para transtornos psiquiátricos. Eu destacaria também que, para muitos desses transtornos, atualizamos os tamanhos das amostras, mas ainda estamos retirando os mesmos fatores psicóticos compulsivos e de neurodesenvolvimento do artigo da Cell.

Há algumas advertências a serem lembradas ao interpretar as correlações genéticas entre os modelos de fatores correspondentes. Uma delas é que as correlações genéticas só serão equivalentes entre métodos genômicos e familiares quando as correlações genéticas forem constantes entre variantes raras e comuns, e isso ocorre porque a regressão do escore LD é estimada usando alelos relativamente comuns com uma frequência alélica menor superior a 1%. Portanto, se esse agrupamento realmente mudar na extremidade de variante rara do espectro, o que é certamente possível, então isso é algo que também mudará esses modelos de fatores, e é algo que ainda precisa ser examinado em trabalhos futuros.

Também é importante ter em mente que as correlações genéticas podem ser tendenciosas para cima em dois casos principais. A primeira é quando os estudos GWAS utilizam controles supernormais, que se refere a casos em que os controles não são simplesmente triados para o transtorno de interesse, mas também para transtornos relacionados, o que irá induzir uma dependência entre esse transtorno de triagem ao estimar correlações genéticas.

Eles também serão tendenciosos para cima quando houver classificação incorreta, ou seja, quando um transtorno relacionado for acidentalmente classificado como o transtorno de interesse, o que também induzirá uma correlação de polarização ascendente, embora as simulações indiquem que seriam necessárias taxas extremamente altas de classificação incorreta para explicar o padrão atual de descobertas.

Então, em geral, acho que, dados esses dois pontos, deveríamos tratar as correlações genéticas como uma espécie de limite superior do que provavelmente está presente na população, mas é algo que é realmente uma limitação interpretativa, não algo que deveria nos levar a abandonar completamente os resultados. nível da variante genética

Quero falar agora sobre análises no nível de variantes genéticas em relação ao GWAS e aos esforços de Cross-Disorder, começando com o primeiro artigo do Cross-Disorder em 2013, onde examinaram cinco transtornos principais em mais de 33.000 casos e 27.000 controles para identificar quatro hits. Que é expandido rapidamente no artigo da Cell de 2019 para agora incluir oito transtornos e mais de 230 mil casos, e quase meio milhão de controles para identificar agora mais de 109 loci pleiotrópicos.

Usando uma meta-análise de efeitos fixos no SEM genômico, também examinamos loci pleiotrópicos nos 11 transtornos e identificamos 184 loci pleiotrópicos, incluindo 69 dos 109 loci do CDG2 (Cross-Disorder, 2019), o que aponta para a replicabilidade desses achados.

Neste gráfico de Manhattan estou mostrando sucessos tanto com triângulos pretos quanto vermelhos. onde os triângulos pretos refletem hits que estavam em LD com os hits univariados, e os triângulos vermelhos indicam novos loci em relação ao GWAS univariado. O que destaca a capacidade dos esforços do Cross-Disorder não apenas para desvendar as variantes genéticas subjacentes à comorbidade, mas também para alavancar o poder compartilhado entre as características para identificar novos resultados e novas descobertas.

Também analisamos GWAS multivariados no contexto de SNPs agindo sobre esses fatores: onde na metade superior desses gráficos de Miami temos os efeitos do SNP sobre o fator, e na metade inferior o que chamamos de SEM genômico qSNP, que indexa a heterogeneidade entre os indicadores que carregam esse fator. Portanto, o qSNP realmente identifica efeitos específicos do transtorno, portanto, para esses resultados, encontramos 132 hits em LD com hits individuais, 20 novos loci e 9 hits altamente específicos do transtorno, o que novamente aponta para outro benefício dos esforços do Cross-Disorder que é identificar não apenas loci pleotrópicos, mas loci que também estão subjacentes à divergência fenotípica ou fazem com que os transtornos pareçam realmente diferentes conforme se apresentam.

Quero abordar brevemente os diferentes tipos de pleiotropia que devemos considerar ao pensar sobre o que esses hits de cross-disorder estão captando. A primeira é a pleiotropia horizontal ou verdadeira, caso em que uma única variante genética ou gene afeta dois transtornos. A segunda é a pleiotropia vertical ou mediada, na qual um gene afeta um transtorno, e então esse transtorno passa a afetar um segundo transtorno, portanto faz parte desse tipo de cascata causal.

Embora as taxas gerais de pleiotropia horizontal e vertical ainda precisem ser testadas nos transtornos psiquiátricos, em geral descobrimos que, para os traços humanos complexos, tende a haver uma mistura de ambos, o que provavelmente também se aplica ao espaço psiquiátrico.

Uma maneira de examinar a pleiotropia vertical é usar a randomização mendeliana, algo que também fizemos com aquele artigo sobre 11 transtornos, onde usamos oito instrumentos, oito SNPs como instrumentos para transtorno por uso de álcool, para examinar essa cascata causal de pleiotropia vertical e, de fato, encontrar efeitos causais do transtorno por uso de álcool na depressão maior e transtorno bipolar neste modelo usando esses oito SNPs como instrumentos.

Um terceiro tipo de pleiotropia é a pleiotropia espúria, que frequentemente ocorrerá quando houver erros de classificação diagnóstica, o que é altamente relevante para transtornos psiquiátricos, dadas taxas como 15% de erros de classificação no transtorno bipolar e na esquizofrenia. Mas quero destacar que pode não ser claro o que significa classificação incorreta, dadas as taxas realmente altas de sobreposição genética. Portanto, se considerarmos esta distribuição teórica do risco genético do transtorno bipolar em vermelho e do risco de esquizofrenia em azul, não está claro qual seria o diagnóstico correto para alguém aqui no meio em roxo. Acho que isso é algo que podemos começar a superar em termos de como pensamos sobre esse problema usando dados de nível de sintoma, que abordarei no final.

Mas antes disso quero falar sobre estudos mecanicistas, ou o que muitas vezes é chamado de estudos funcionais, que em geral procuram pegar essas centenas de variantes genéticas que estamos começando a descompactar e começar a entender o quadro biológico que está sendo pintado pela agregação dessas variantes genéticas em diferentes categorias funcionais, como quando ou onde os genes são expressos.

Nesse artigo do Cross-Disorder, eles apresentam uma série de descobertas interessantes, incluindo o resultado do GTEx de que os loci pleiotrópicos são geralmente enriquecidos no cérebro, mostrado aqui em azul. Usando padrões de expressão genética temporal espacial, eles descobriram que os loci pleiotrópicos (nesta linha azul escura) são geralmente enriquecidos durante o segundo trimestre pré-natal aqui.

Usando análises específicas de tipo de célula, eles descobriram que os loci pleiotrópicos são geralmente enriquecidos em neurônios, mas não são tão enriquecidos em microglia como indicado por este sombreado azul.

Nesse artigo sobre 11 transtornos, usamos esse novo método de SEM genômico estratificado que pode ser usado para examinar o enriquecimento multivariado para examinar o enriquecimento no nível dos fatores psiquiátricos de que falei. Descobrimos que para o fator de transtornos psicóticos, esse fator é enriquecido em genes excitatórios, genes GABAérgicos, genes intolerantes à variante truncadoras de proteínas aqui no meio e, em particular, é enriquecido na sua intersecção, o que realmente dá alguma compreensão dos processos compartilhados para os indicadores dos fatores de transtornos psicóticos (nomeadamente transtorno bipolar e esquizofrenia). E também gostaria de destacar que, em linha com as duas descobertas do Cross-Disorder, não encontramos enriquecimento nessas categorias de células gliais em nenhum dos fatores.

Portanto, termino agora falando sobre os próximos passos importantes para os esforços do Cross-Disorder. Uma das principais é a consideração de fenótipos mais sutis, o que pode ajudar a classificar alguns desses fenótipos mais mistos de que falei no caso do transtorno bipolar e da esquizofrenia, e as análises de escore poligênico de risco realmente apontam por que isso pode ser importante. Assim, por exemplo, os escores poligênicos de risco da esquizofrenia mostraram uma associação mais forte para o transtorno bipolar caracterizada por psicose incongruente com o humor em comparação com o transtorno bipolar sem psicose e com idade mais precoce de início bipolar, o que indica que certas fenótipos podem estar mais estreitamente ligadas no nível genético em todos os transtornos.

Existem diferentes métodos, como o BUHMBOX, que podem ser usados ​​em conjunto com dados genotípicos brutos para detectar se certos subgrupos dentro de um transtorno estão conduzindo correlações genéticas com outros transtornos e, embora as descobertas iniciais não tenham encontrado evidências para esses subgrupos de transtorno depressivo maior, isso em grande parte ainda precisa ser testado para outros transtornos.

Os registros eletrônicos de saúde serão um recurso incrível no futuro, que nos dará acesso a alguns desses dados de nível de sintomas que, com vários consórcios diferentes já em andamento com esse propósito explícito, incluindo eMERGE, PsycheMERGE e o programa NIH All of Us.

Outra consideração importante para futuros esforços genômicos do Cross-Disorder é a inclusão do ambiente, nomeadamente porque o padrão de sobreposição entre transtornos pode mudar em certos contextos, e ao dividir os GWAS em diferentes ambientes ou diferentes coortes, podemos examinar a estabilidade dessas correlações genéticas e se certas correlações são ou não realmente específicas do ambiente.

Um ambiente específico que considero relevante é a idade de início desse transtorno em relação ao ambiente biológico interno que pode estar ocorrendo naquele momento. Então, se considerarmos essas distribuições de idade de início da esquizofrenia (topo) e depressão maior (embaixo), você poderá ver esses dois tipos de picos mais tarde na vida, o que pode realmente indicar que há um tipo realmente específico de biologia que está sendo ativado para genes expressos mais tarde na vida, e se dividirmos o GWAS para esses dois transtornos nessa faixa etária específica de final dos 40 anos, poderemos descobrir que há um agrupamento realmente único entre os transtornos nessa faixa etária.

Assim, em geral, embora os nossos transtornos possam parecer diferentes em alguns aspectos, o que nos levou a agrupá-los nestas categorias distintas, a sua co-ocorrência em níveis muito mais elevados do que o acaso exige realmente que compreendamos as causas subjacentes desta sobreposição.

Eu diria que a genômica oferece uma oportunidade real para preencher algumas lacunas importantes na nossa compreensão desta sobreposição, em parte porque podemos examinar todo o espaço psiquiátrico utilizando diferentes métodos que nos permitem examinar a sobreposição de amostras muitas vezes independentes, e também nos permite examinar esse convergente em vários níveis de análise, inclusive na análise mecanicista do genoma e no nível do SNP. E com isso vou apenas agradecer a todos pelo seu tempo.
