---
title: "Capítulo 1.3: História"
---

# ***História da Genética Psiquiátrica (Parte 1)*** {#sec-part1}

**Título:** História da Genética Psiquiátrica (Parte 1)

**Apresentador:** Ken Kendler

Introdução

Tenho o prazer de poder falar com vocês sobre a história da genética psiquiátrica. Neste breve seminário, tudo o que posso realmente esperar fazer é fornecer uma breve introdução e alguns destaques. Decidi me concentrar na história inicial da genética psiquiátrica, já que ela é provavelmente menos familiar para a maioria de vocês, e em vez de apenas dar muitos fatos desinteressantes e datas, para tentar ilustrar isso com indivíduos proeminentes em particular, para fornecer quando eu posso fotos deles, para que você veja como são seus livros ou artigos. Eu diria que o objetivo que estabeleci foi mostrar a vocês pedaços da rica história de nossa disciplina de genética psiquiátrica, para que eu possa aguçar seu apetite por um auto-estudo adicional.

Roberto Burton

Então vamos começar. Numa fase realmente inicial, a disciplina moderna da genética psiquiátrica, tal como a entendemos, começou muito perto da época da própria psiquiatria, ou seja, algum lugar próximo as décadas entre 1780 e 1800. Mas temos uma figura gigante, Robert Burton, que escreveu no início do século XVII, neste caso no ano de 1621, pouco mais de uma década após a morte de William Shakespeare, e escreveu o que foi um clássico lido até este século sobre a depressão. O título é “Anatomia da Melancolia”, e quero apontar para vocês uma pequena parte onde ele descreve a sinopse de sua primeira partição. Como você pode ver meu pointer aqui, que ele descreve todas as causas da melancolia, dividindo-as em sobrenaturais ou naturais, e em secundárias ou primárias, ele descreve sobre as estrelas e a quiromancia, mas aqui particularmente ele observa que a velhice é um fator de risco para temperamento melancólico, e aqui notamos “pais”, sendo uma doença hereditária. Portanto, temos uma observação de décadas, e na verdade mais de séculos antes do desenvolvimento da medicina moderna e do desenvolvimento da psiquiatria, com a compreensão baseada na observação das pessoas de que uma forma de doença psiquiátrica, melancolia, passou claramente dos pais para os filhos.

Este é um preprint de um artigo que está sendo publicado no American Journal of Psychiatry e reflete uma revisão bastante detalhada da pré-história da genética psiquiátrica dos anos de 1780 a 1910. O que quero fazer a seguir é apenas destacar esta visão geral. Como você pode ver no resumo aqui, revisei 48 textos representativos publicados durante esse período, quase todos esses livros tinham seções sobre a etiologia de doenças mentais ou, na verdade, eles chamavam isso com mais frequência de insanidade. Nessa seção quase sempre faziam alguns comentários sobre a importância da genética na etiologia da insanidade. Então aqui está uma revisão dos principais pontos dessa revisão em si:

**Primeiro**, desde o início da psiquiatria como disciplina médica, por volta de 1780, a maioria dos autores especialistas que eram escritores de livros didáticos viam a hereditariedade como um dos fatores de risco mais fortes para a insanidade. **Segundo**, durante este período a maioria dos escritores concluiu que era uma predisposição para a doença, e não a doença em si, que era transmitida nas famílias. **Terceiro**, e isto está relacionado com o conceito de predisposição, eles estavam bem conscientes da aparente natureza probabilística da transmissão da insanidade. Eles notaram que muitas vezes pulava gerações, com um pai ou tia afetado, um avô, uma tia ou um tio, mas o pai também e a criança são afetados, e também notaram que muitas vezes parecia afetar apenas alguns dos muitos indivíduos dentro dos mesmos irmãos. **Quarto**, os autores discutiram longamente a questão de saber se havia o que descreveram como “homogeneidade” ou “heterogeneidade” na transmissão familiar das várias formas de insanidade. A conclusão geral foi que a transmissão heterogênea era a regra. Ou seja, nos familiares dos insanos, quase todos que estariam internados em manicômios neste momento. Os médicos que escreveram este material visualizaram uma ampla variedade de distúrbios psiquiátricos e, às vezes, neurológicos. A transmissão homogênea, isto é, a ideia de que semelhante gera semelhante, foi uma exceção. É interessante que dois tipos de síndromes sejam mencionados repetidamente nesses livros didáticos como sendo transmitidos de maneira homogênea, já que uma é o que chamaríamos de psicose cíclica ou doença maníaco-depressiva, e a outra era o suicídio, com vários autores notando suicídios ocorrendo em famílias com altos níveis de homogeneidade. **Quinto**, muitos escritores notaram que características de personalidade estranhas e excêntricas eram comuns nos parentes, e especialmente nos pais, dos seus pacientes insanos, e isto obviamente é um antecedente de desenvolvimentos posteriores de condições do espectro da esquizofrenia dentro do nosso próprio período de tempo. **Finalmente**, a herança tal como a usavam, e como Burton a usava, era comumente entendida de forma mais ampla do que seria hoje. Inclui experiências parentais ambientais anteriores, ou seja, a herança de características adquiridas foi aceita durante a maior parte do século 19 e até mesmo nas primeiras décadas do século 20, mas também alguns autores observaram que a transmissão entre pais e filhos poderia surgir de efeitos psicológicos do comportamento dos pais ou efeitos intrauterinos.

Próspero Lucas

Agora, deixe-me dar destaque a uma série de autores importantes que gostaríamos de descrever e quero começar com Próspero Lucas. Prosper Lucas foi um alienista e geneticista francês. Ele viveu de 1808 a 1885. Ele escreveu uma importante monografia de dois volumes sobre genética em 1847, como você pode ver, esta seria a tradução: "traços filosóficos e aproximadamente fisiológicos da hereditariedade natural". Estes são muito longos e extensos. Teria uma das grandes revisões de meados do século XIX no campo da genética, e ele as revisou em termos de condições médicas, físicas (que seriam características antropométricas) e psiquiátricas. Além disso, Prosper Lucas foi em sua época o que poderíamos chamar de geneticista estatístico e desenvolveu uma teoria pré-mendeliana tentando explicar a natureza estocástica da herança. A importância do trabalho de Prosper Lucas é melhor ilustrada em um dos grandes livros de toda a história da ciência, "A Origem das Espécies" de Charles Darwin, em 1859. Ele citou o livro de Prosper Lucas como "o mais completo e melhor sobre o assunto", e em seus trabalhos posteriores, particularmente sobre "Variações em Plantas e Animais", Darwin citou frequentemente o trabalho de Lucas mais de uma dúzia de vezes no próprio livro.

Jenny Koller

Agora saltemos algumas gerações para a figura de Jenny Koller, a mulher mais proeminente que contribuiu para esta literatura no século XIX. Um pouco de histórico é necessário. Ao longo de todo o século XIX, praticamente todas as observações em genética psiquiátrica foram descontroladas. A grande maioria das estatísticas relatadas é muito simples: trata-se da proporção de pacientes psiquiátricos hospitalizados que sofriam de sobrecarga hereditária, e com isso eles querem dizer que têm algum histórico bem documentado de doença psiquiátrica ou, ocasionalmente, de doenças neurológicas em seus parentes. Estas percentagens variaram muito, de quatro ou cinco por cento a 80 por cento, e isso deve-se em parte ao fato de quais doenças que consideram constituir um fardo hereditário serem bastante variáveis ​​e os familiares que contarem também serem bastante variáveis, mas nunca tinham utilizado controles. O primeiro estudo a fazer isso foi feito por Jenny Koller em 1895. Aqui está uma foto da aparência do Dr. Koller. Ela foi incentivada por sua mãe a considerar a medicina. Encontrou-se com um dos poucos médicos da Suíça na época, concluiu o curso de medicina lá, mas não conseguiu o que equivaleria a um estágio, pois não eram oferecidos para mulheres na Suíça, e por isso foi para Paris, França por seu treinamento.

Esta é a aparência do artigo dela; isso seria uma tradução. Ela estava naquele momento trabalhando em Zurique. Darei uma breve biografia em um minuto. O título é "Contribuição das estatísticas de hereditariedade hereditária dos doentes mentais no cantão de Zurique: comparação dos doentes mentais com uma carga hereditária sobre pessoas saudáveis ​​devido a transtornos mentais e afins". Podemos ver que naquela época as pessoas escreviam títulos mais longos para os artigos do que fazemos hoje, e esta era uma revista relativamente proeminente com sede em Berlim, embora fosse suíça. Publicamos na revista Neuropsychiatric Genetics no início deste ano; Astrid Klee, que é tradutora profissional de alemão, e eu, fizemos uma revisão detalhada deste artigo e, no apêndice, apresentamos uma tradução completa para o inglês. Quero apenas resumir brevemente para você aqui, apenas pegando o resumo.

O primeiro estudo desse tipo na história da genética psiquiátrica foi publicado em 1895 e foi a dissertação de doutorado da médica suíça Jenny Koller. Ela trabalhava com Auguste Forel no hospital Burghölzi em Zurique, Suíça, um hospital muito famoso na história da psiquiatria, e Forel foi sucedido por Eugen Bleuler, que discutiremos mais tarde. Ela obteve histórias de uma série de transtornos mentais e neurológicos nos pais, tias, tios, avós e irmãos de 370 pacientes psiquiátricos hospitalizados e 370 controles que não foram hospitalizados. Curiosamente, as taxas de carga hereditária foram apenas modestamente mais elevadas nos casos do que nos controles. Houve muita surpresa com o alto nível de doença mental que ocorre nos parentes dos indivíduos controle não afetados. No entanto, Koller continuou tentando abordar duas questões bastante importantes: primeiro, ela examinou quais síndromes individuais eram realmente mais comuns nos familiares dos pacientes psiquiátricos e nos controles, e encontrou apenas duas categorias, que traduzimos aproximadamente como principais doenças mentais e como excentricidades, isto é, comportamentos anormais, mas ela também considerou síndromes de apoplexia, isto é, um acidente vascular cerebral, transtornos nervosos, que incluíam coisas como dores de cabeça, e provavelmente alguns outros transtornos neurológicos, bem como ansiedade e demência e aqueles três não eram mais comuns nos familiares dos pacientes psiquiátricos do que nos controles. Além disso, as taxas de doenças mentais e excentricidades foram muito mais fortemente elevadas nos parentes de primeiro grau dos pais, principalmente crianças, principalmente pais e irmãos em casos contra controles, mas a elevação para avós, tias e tios foi muito menor. Mais uma vez, esta foi a primeira observação sistemática da tendência dos transtornos de se agregarem mais no que hoje entenderíamos como indivíduos geneticamente mais relacionados. Na minha opinião, o estudo de Koller representa um grande avanço metodológico na genética psiquiátrica, ajudando a definir quais transtornos são co-agregados com doenças mentais graves.

Ernst Rüdin

Deixe-me agora abordar o que será uma parte mais sombria da história da genética psiquiátrica. Esta é a figura de Ernst Rüdin. Darei novamente uma breve biografia. Quem puder ver vai perceber que ele tinha um alfinete de lapela com a suástica e isso fará parte da nossa história.

Bem, Ernst Rüdin nasceu em 1874 e morreu em 1952. Ele era suíço. Ele se formou na faculdade de medicina em Zurique em 1898, e seu primeiro emprego também foi no hospital Burghölzi, depois de Jenny Koller como assistente Eugen Bleuler. Mudou-se então para a clínica psiquiátrica da Universidade de Munique em 1907, onde se tornou assistente de Emil Kraepelin, com quem concluiu sua tese de doutorado. Ele foi nomeado médico sênior lá em 1909. Quando o sonho de toda a vida de Kraepelin, o estabelecimento do Instituto Alemão de Pesquisa Psiquiátrica, o primeiro instituto multidisciplinar do mundo para doenças psiquiátricas, foi estabelecido em Munique em 1917, Kraepelin nomeou Rüdin como chefe do Departamento de Estudos Genealógicos e Demográficos. A maioria dos principais membros da próxima geração de geneticistas psiquiátricos, e isso inclui figuras como Eliot Slater, Eric Stromgren e outros de toda a Europa, vieram treinar no departamento que Rüdin havia estabelecido na década de 1920 e no início da década de 1930. Rüdin teve dois trabalhos importantes em genética psiquiátrica, embora sua escola, o programa que ele estabeleceu, tivesse muitos mais trabalhos.

O primeiro foi publicado em 1911, quando ele tinha 26 anos e nesta revista e o título era “Métodos e objetivos da pesquisa familiar e da psiquiatria”. É um artigo extenso e descreve um programa de pesquisa metodologicamente sofisticado baseado em Mendel para genética psiquiátrica, mas você notará nele uma série de menções sobre “volk”, teorias eugênicas sobre o "volk" e o bem-estar dos genes do próprio "volk". Seu segundo grande trabalho foi este e junto com sua filha Edith Zerbin-Rüdin, há mais de duas décadas, publiquei na Neuropsychiatric Genetics uma síntese e resumo deste. O título seria “Estudos da herança e origem da doença mental ao problema da herança e origem primária da Demência Precoce”.

Este foi o primeiro estudo familiar sistemático em grande escala já feito sobre um transtorno psiquiátrico. Incluía o uso desses métodos recém-desenvolvidos de Weinberg para corrigir a idade da amostra e usar um método de correção em relação ao probando para obter os resultados corretos. O risco mórbido que ele calculou para a esquizofrenia definida de forma restrita e ampla na amostra foi de 5,4% e 7,7%. Esses resultados são bastante semelhantes às descobertas modernas; o estudo que fiz sobre Russ Coleman no início da minha carreira encontrou uma taxa de 6%, muito dentro da faixa que Ernst Rüdin descobriu. Ele também descobriu que outras psicoses eram comuns, com um risco mórbido de 5,1%, taxas mais baixas em meios-irmãos. Ele observou que o risco de esquizofrenia aumentava significativamente no diagnóstico parental de alcoolismo, na história de esquizofrenia em parentes de segundo ou terceiro grau e no diagnóstico parental de outras psicoses. Assim, no geral, Rüdin descobriu uma relação familiar entre a esquizofrenia e outras psicoses, um risco substancialmente menor de esquizofrenia nos pais contra irmãos, e um padrão de segregação da esquizofrenia que não estava em conformidade com os distúrbios mendelianos simples. É importante notar que este não foi um estudo familiar de caso-controle como poderíamos fazer agora; na verdade, o objetivo deste estudo foi verificar se padrões de segregação consistentes com a transmissão mendeliana simples poderiam ser encontrados. Rüdin observou nesta monografia que se houvesse dois genes recessivos, aqueles com 0,25 ao quadrado equivaleriam a uma taxa de recorrência de 0,0625, ele disse que isso poderia ser consistente com o modelo.

Agora precisamos falar sobre outra característica fundamental da carreira de Rüdin. Quando adolescente, Rüdin desenvolveu um forte interesse pela higiene racial e foi, em 1905, um dos fundadores da sociedade alemã para a higiene racial. Após a ascensão dos nacional-socialistas, ou seja, dos nazistas, na Alemanha em 1933, como diretor do Instituto Alemão de Pesquisa Psiquiátrica (ele assumiu o cargo de Kraepelin após sua morte), Rüdin colaborou extensivamente com o governo nazista, elogiou suas políticas raciais e recebeu financiamento substancial deles e, mais tarde, da Schutzstaffel. A partir de 1933, ele desempenhou um papel importante no desenvolvimento do programa nazista de esterilização involuntária de doentes clinicamente e psiquiátricos. É geralmente aceito que ele não esteve ativamente envolvido no programa Nazi T4, que consistia no assassinato sistemático de doentes mentais e deficientes mentais, que começou em 1939, mas os documentos históricos são bastante convincentes de que ele estava consciente destes esforços e sabia dos colegas que trabalhavam neles. E ele certamente não fez nenhuma tentativa de impedi-los ou divulgá-los. Além disso, conforme documentado em recursos históricos de alta qualidade que só recentemente foram disponibilizados em inglês, eu recomendaria particularmente este livro do Dr. Weiss "A Simbiose Nazista: Genética Humana e Política no Terceiro Reich". É bastante claro que Rüdin desempenhou um papel importante na legitimação científica das políticas raciais nazistas, tanto na Alemanha como a nível internacional, e sabemos historicamente que a aceitação destas políticas lançou as bases para os futuros horrores do Holocausto. À luz de suas atividades a partir de 1933, há uma série de opiniões em nosso campo sobre como deveriam ser tratadas as contribuições científicas substanciais de Rüdin para a história da genética psiquiátrica. Alguns argumentaram que qualquer discussão sobre o seu trabalho é inerentemente imoral, pois inevitavelmente o reabilita e desonra a memória daqueles cujo sofrimento ele contribuiu. E eu respeito pessoalmente essa tradição, embora não concorde com ela. Outros argumentaram que o seu trabalho pode e deve ser estudado por duas razões importantes e complementares: primeiro, ele desempenhou um papel importante na história da nossa genética psiquiátrica, mas segundo, como um estudo de caso dos potenciais efeitos trágicos do uso indevido de nossa ciência.

Eugen Bleuler

Deixe-me então prosseguir e concluir com esta figura Eugen Bleuler. Ele é provavelmente o mais conhecido de todas as pessoas de quem falei aqui. Esta é uma linda foto dele quando jovem. Bleuler é mais famoso por apresentar o termo "esquizofrenia" ao mundo em uma palestra em Berlim em 24 de abril de 1908. Ele revisou e expandiu seu conceito de esquizofrenia em seu livro seminal de 1911. Esta é sua grande monografia, " Demência Precoce, ou Grupo de Esquizofrenias ", e infelizmente só foi traduzido para o inglês em 1950. Mas em 1917, ou seja, apenas alguns anos depois da monografia publicada por Rüdin, Bleuler escreveu uma crítica muito cuidadosa ao estudo familiar de Rüdin sobre demência precoce, e esta é a versão alemã disto. E isso foi publicado agora no Schizophrenia Bulletin, que representa uma revisão detalhada do comentário de Bleuler sobre Rüdin e, como os outros trabalhos que venho fazendo, aqui no apêndice, junto com Astrid Klee, publicamos uma tradução completa para o inglês dos comentários de Bleuler.

Quero rever aqui os quatro pontos-chave apresentados por Bleuler, novamente trabalhando num momento muito diferente do nosso. Primeiro, Bleuler argumentou que a compreensão dos padrões de transmissão das famílias esquizofrênicas requer um conhecimento definitivo dos limites do fenótipo. E ele argumenta que eles permanecem desconhecidos. Bleuler sugere fortemente que a escolha de Rüdin, que foi o conceito de demência precoce de Kraepelin, foi muito restrita. Como sabemos, Bleuler estava interessado em conceitos mais amplos como a esquizofrenia latente. O que Bleuler argumentou foi que esclarecer a genética da esquizofrenia está inextricavelmente ligado ao problema de definir o fenótipo: não se pode fazer um sem o outro. Em segundo lugar, Bleuler defendeu a importância da "erbsquizose", que pode ser descrita literalmente como "esquizoidia herdada". E ele se perguntou se seus famosos "4 As" ou outras (e cito aqui de nossa tradução) "características anatômicas, químicas ou neurológicas do cérebro" poderiam estar por trás da transmissão genética da esquizofrenia. Isso realmente é muito semelhante ao nosso conceito do que pode ser um endofenótipo. Terceiro, Bleuler estava bastante interessado na natureza do início da esquizofrenia, sugerindo que as adversidades ambientais muitas vezes provocavam a manifestação de doenças "latentes". Era importante argumentar que identificar tais fatores de risco e realmente incorporá-los nos modelos genéticos, um conceito relativamente avançado com o qual ainda lutamos hoje. Quarto, embora não esteja otimista de que o conhecimento atual permitiria uma resolução dos modelos de transmissão para a esquizofrenia, Bleuler considera implausíveis os modelos de locus único para a esquizofrenia/ demência precoce, e em vários pontos se pergunta se os modelos poligênicos (ele não forneceu o número certamente não foi concebido como Ronald Fisher seria), mas um pequeno número de genes poderia ser melhor aplicado.

Resumo

Então isso conclui a parte principal e quero resumir. Meu objetivo foi apresentar a você algumas das muitas figuras e tópicos importantes da história da genética psiquiátrica. Quero deixar a vocês um tema ético e dois temas científicos abrangentes desta história. A parte ética: a nossa história ilustra os abusos a que a ciência da genética psiquiátrica e comportamental pode ser submetida, com resultados trágicos, e, portanto, a necessidade da nossa vigilância para reduzir as chances de tais desenvolvimentos no futuro. De uma perspectiva mais científica, sugeriria que a história da genética psiquiátrica inclui muitos temas, mas dois dos quais são abrangentes: o primeiro é a estreita inter-relação entre o diagnóstico psiquiátrico e a genética. Como você pode fazer a genética de um distúrbio cujos limites diagnósticos não são claros? Portanto, inevitavelmente existe uma relação íntima com estes dois campos, ou seja, para acertar a genética precisamos acertar o diagnóstico, e a estratégia genética é uma das melhores formas de nos ajudar a decidir o que é um diagnóstico válido. Portanto, estamos neste processo amplo, longo e iterativo. E a segunda questão fundamental que permeia grande parte do século XIX e início do século XX é a seguinte: será que os transtornos psiquiátricos percorrem nas famílias ou existe frequentemente uma transmissão heterogênea? E eu sugeriria para aqueles de vocês que atuam na área que essas duas questões são muito existentes e não resolvemos nenhuma delas. Obrigado pela sua atenção.
