---
title: "Capítulo 10.1: Uma carreira em genética psiquiátrica"
---

# ***Como a genética afeta nossa saúde mental?*** {#sec-section1}

**Título**: Como a genética afeta nossa saúde mental?

**Apresentadores**: Cathryn Lewis, PhD (Social, Genetic, and Developmental Psychiatry Centre, King’s College London); Alex Curmi, MD (Maudsley NHS Foundation Trust)

*Você encontrou o podcast "Thinking Mind" \[Música\].*

**Alex**: Professora Cathryn Lewis, obrigada por ter vindo ao programa.

**Cathryn**: Prazer, Alex. Obrigado pelo convite.

**Alex**: Tenho certeza de que falaremos muito sobre genética, psiquiatria, condições psiquiátricas, psicologia e como podemos, usando a arte da matemática e da estatística, desvendar alguns desses mistérios. Mas uma das melhores coisas de conversar com convidados interessantes como você é a capacidade de aprender sobre Desenvolvimento de Carreira e planos de carreira, e aprender que os planos de carreira nem sempre são lineares. E talvez você possa nos contar um pouco sobre como você se tornou professora de genética, estatística, epidemiologia,

**Cathryn**: sim, sim, então minha formação não é em psiquiatria ou psicologia, mas em matemática. Fiz uma primeira licenciatura em matemática muito pura, hum, e porque era apaixonada por matemática quando estava na escola e gostava muito dela. Mas à medida que os estudos avançavam, percebi que esse tipo de lado teórico esotérico da Academia não era exatamente o que me interessava. Queria coisas que fossem muito mais práticas, que estivessem muito mais alinhadas com a resolução de problemas do dia a dia. E então fiz um mestrado em estatística e fiz muitas análises de dados. A estatística é uma área fabulosa para estudar porque dá acesso não apenas ao lado da matemática, mas a muitas áreas diferentes nas quais as pessoas usam a estatística. E tive a sorte de durante meu doutorado começar a analisar dados genéticos e percebi que estava realmente interessada nela e também que era uma área florescente e em desenvolvimento de pesquisa médica. E isso me lançou em minha carreira de pesquisa.

Hum, devo dizer que trabalhei em diferentes áreas médicas durante minha carreira. Comecei a trabalhar com câncer, procurando genes para câncer de mama, e sou um autor muito, muito secundário no artigo que encontrou o gene BRCA1 com variantes de alto risco para câncer de mama, por exemplo, e trabalhei em doenças autoimunes, e realmente aplicando minhas técnicas estatísticas onde elas podem ser úteis. Mas o que tenho focado nos últimos 15 anos é trabalhar na genética dos transtornos mentais e na psiquiatria. E como muitas coisas, esta foi uma chance muito fortuna. Lembro-me de apresentar um pôster em uma conferência sobre doenças autoimunes, e um psiquiatra veio até mim e disse que poderíamos fazer isso na esquizofrenia, e comecei a trabalhar com ele na esquizofrenia. E então Peter McGuffin, que era chefe do Centro de Psiquiatria Social, Genética e de Desenvolvimento, onde estou agora, viu o potencial de trazer minhas habilidades para a genética da saúde mental e me abordou, e 15 anos depois, eu, hum, você sabe, totalmente inserido na genética da Psiquiatria.

**Alex**: Você descobriu que o acaso é uma parte importante na construção de uma carreira?

**Cathryn**: Hum, para mim, certamente foi. Sei que as pessoas têm abordagens diferentes para planejar suas carreiras; o meu sempre foi bastante imediatista. Eu sempre, você sabe, sempre gostei muito do que fiz e tomei decisões com base em: "Oh, parece um projeto muito bom para se envolver", "Oh, Eu realmente gostaria de trabalhar com eles." Então, eu nunca tive, você sabe, uma meta de longo prazo do que eu alcançaria, e sei que esse não é o tipo de conselho que,

**Alex**: não é o padrão, certo?

**Cathryn**: Não é... funcionou muito bem para mim, e eu realmente gostei da flexibilidade das carreiras acadêmicas para circular e acumular experiência e aprender, você sabe, com diferentes projetos e pessoas diferentes - coisas que realmente produzem uma riqueza para a próxima, uh, a próxima coisa que você fizer. E devo dizer também, talvez, que trabalhei, trabalhei meio período por 10 anos, anos enquanto meus filhos eram pequenos, e, novamente, gostei muito dessa flexibilidade para continuar com as partes da função que eram importantes para mim.

**Alex**: Então você teve uma atitude experimental em relação à sua carreira, tentando coisas diferentes, e foi guiado pelo seu senso de fascínio, que na verdade é um conselho de carreira que dou às pessoas o tempo todo porque acho que estamos condicionados pelo nosso sistema educacional realmente para cumprir metas estabelecidas por outras pessoas. E também acho que o fascínio é um tipo de sentido que você pode desenvolver. Quanto mais você é guiado por isso, mais você pode realmente sentir o quão realmente interessado ou engajado estou nessa coisa específica. Mas muitas pessoas fazem coisas com as quais não se envolveram durante toda a vida, por isso é bom saber que você conseguiu escapar dessa armadilha específica,

**Cathryn**: sim, sim, é muito bom ouvir essa perspectiva sobre isso e eu concordo com esse tipo de fascínio e, claro, é disso que se trata a pesquisa e a exploração científica. Mas talvez eu possa fazer um apelo, você sabe, eu tenho formação em matemática, e muita ciência agora é sobre grandes números, é sobre IA, é ter as habilidades não apenas para fazer trabalho molecular (você sabe, no laboratório ou trabalhar com pessoas), mas para poder analisar esses dados e juntar as coisas. E eu recomendaria a qualquer pessoa que tenha a oportunidade de desenvolver ainda mais as suas competências em matemática ou estatística, o que realmente abre portas para a variedade de coisas diferentes em que se pode envolver. Em particular pessoas jovens se tiverem a chance de estudar matemática, sabe, em um nível além dos 16 anos, onde é obrigatório no Reino Unido, sabe, até o sonho lá de baixo que realmente abre portas tendo essas habilidades e mostrando sua capacidade de pensar analiticamente. E como matemático, é claro, sou tendencioso, acho que as habilidades matemáticas abrem portas em muitos campos.

**Alex**: Absolutamente. Então talvez você possa nos contar um pouco sobre estatísticas. Como é que as estatísticas nos ajudam a desvendar alguns dos mistérios, especialmente na Psiquiatria, que estamos a tentar desvendar?

**Cathryn**: Então, uma das coisas que as estatísticas permitem que você controle é o risco de algo acontecer, e é nisso que estamos muito interessados ​​como indivíduos. Você sabe, começar algo muito básico que a gente pensa muito é o histórico familiar de transtornos psiquiátricos. Então sabemos, você sabe, por estudos científicos, por nossa experiência pessoal, que os transtornos de saúde mental tendem a ocorrer nas famílias. Muitas vezes vemos que alguém que foi diagnosticado com depressão, um dos pais ou um parente mais distante, também tem depressão. E olhando para as famílias, conseguimos identificar riscos de as próprias pessoas desenvolverem um transtorno, devido ao seu histórico familiar.

Mas penso que as pessoas nem sempre são muito boas a interpretar os riscos de forma adequada, e vemos isso muito bem nos jornais, por exemplo. Vemos que algo é dito que aumenta em cinco vezes o risco de algo realmente ruim acontecer, e isso é bastante assustador de ver, saber que: "Oh, bebi muito café, posso correr cinco vezes mais risco de algo mais acontecendo." Mas isso cinco vezes é um risco relativo, comparado ao fato de não acontecer. A outra informação que não somos bons em analisar é o risco absoluto. Então, se a chance de algo acontecer é muito rara, digamos, uma em cada dez mil vezes, então, em cinco vezes, ainda é muito incomum que isso aconteça. E penso que somos muito ruins em interpretar os riscos porque precisamos de juntar esse risco relativo, que muitas vezes é bastante assustador, com o risco absoluto, o que pode fazer com que isso volte a ser bastante tranquilizador.

**Alex**: sim, então, o risco relativo é como, qual é a probabilidade de você desenvolver uma condição dada uma situação específica? Isso é um risco relativo…

**Cathryn**: Exatamente.

**Alex**: O risco é só da população, quem vai desenvolver isso? Qual é a probabilidade de desenvolver uma condição,

**Cathryn**: sim, exatamente. E então, para trazer isso de volta à saúde mental, na esquizofrenia, por exemplo, sabemos que alguém que tem um pai que foi diagnosticado com esquizofrenia tem, você sabe, talvez oito ou dez vezes mais probabilidade de desenvolver esquizofrenia, e isso é um número realmente assustador, e sei que há muita preocupação, com razão, sobre isso, mas, para colocar isso em contexto, se o risco populacional de esquizofrenia for de cerca de um por cento, então ter um risco oito vezes maior de desenvolver esquizofrenia é um risco de oito por cento. Então, sim, esses 8 por cento são maiores que o risco populacional, mas isso ainda significa que há 92 por cento de chance de que isso não aconteça, então na verdade não desenvolve esquizofrenia.

**Alex**: então, realmente, nós não... quando vemos dados genéticos, particularmente acho que um problema é quando os dados científicos são filtrados pela mídia porque a mídia obviamente é incentivada a produzir algo atraente ou sensacional. Mas, deixando isso de lado, parece que não temos boas intuições sobre como avaliar o risco tal como o vemos conforme relatado pelos dados científicos.

**Cathryn**: Sim, concordo plenamente com você, e há, você sabe, como você diz, os jornais, os jornalistas têm que, você sabe, vender suas notícias, e então eles tendem a relatar as coisas que têm maior probabilidade de chamar a atenção, você sabe, mais uma espécie de clickbait. E assim tendem a reportar o risco relativo em vez do risco absoluto, mais tranquilizador.

**Alex**: A outra coisa, eu acho, a visão muito tradicional da genética é que nosso DNA tem uma determinação muito alta sobre o que acontece. Você sabe, se você tiver os genes específicos para uma condição, você vai contrair essa condição. É assim que tendemos a pensar classicamente. Mas sabemos cada vez mais que existem algumas condições que têm uma enorme quantidade, uma enorme variedade de influência genética, muito mais do que um gene. Digamos que se você tem uma doença como a doença de Huntington, esse é um gene, e se você tiver o gene, você desenvolverá essa doença. Mas a maioria das coisas, é justo dizer que a maioria das coisas não é como a doença de Huntington?

**Cathryn**: É muito justo dizer isso. Portanto, algumas características são exatamente como as de Huntington, como a fibrose cística ou variantes no gene BRCA1 para o câncer da mama, onde essas alterações genéticas por si só colocam alguém num risco muito elevado de desenvolver uma doença genética, e esse é o tipo de genética que conhecemos. somos ensinados na escola, e isso nos leva a pensar na genética como preto e branco, sim, não, você sabe, corremos risco ou não corremos risco.

**Alex**: Você tem o gene da gordura, exatamente, exatamente.

**Cathryn**: Bom, e posso dizer que todos nós temos o gene da gordura, todos carregamos esse gene, mas o que difere entre nós são as mudanças nesse gene, então mudanças específicas ao nível das variantes de DNA que carregamos, e é isso que faz uma diferença entre nós.

**Alex**: Conte me mais sobre isso.

**Cathryn**: Então, nossos genes são compostos de uma longa sequência de variantes de DNA, então os pares de bases A, C, G e T, e cerca de 99% do nosso genoma são exatamente os mesmos. Você sabe, você, eu e todos que estão ouvindo este podcast teremos exatamente o mesmo par de bases exatamente no mesmo lugar em nosso DNA. Mas um por cento do nosso genoma pode diferir entre nós, e o nosso genoma tem mais de três bilhões de pares de bases, por isso um por cento ainda nos dá muitas oportunidades de divergir, e algumas dessas mudanças têm um impacto muito grande no nosso risco de doenças diferentes, condições diferentes. Mas a maioria das mudanças que vemos no nosso DNA têm um efeito muito modesto no risco de doenças, e grande parte da minha investigação centra-se na genética da depressão e, nos últimos 10 anos, temos realizado estudos para identificar as contribuições genética da depressão. E fazemos isso em um desenho epidemiológico clássico, que é um estudo de caso-controle. Coletamos e realizamos estudos recentes com grupos de pessoas que foram diagnosticadas com depressão e comparamos seu DNA com pessoas da população em geral ou pessoas que sabemos que não foram diagnosticadas com depressão até o momento. E avançamos no genoma olhando para vários lugares diferentes no genoma, e olhamos para a frequência dessa mudança, e dizemos, ok, neste local no genoma, as pessoas têm um alelo C ou um alelo A, ali. Qual é a frequência desse alelo A em pessoas com depressão e em pessoas sem depressão? E então fazemos um teste estatístico muito simples e dizemos: isso difere? E fazemos isso em vários milhões de lugares ao longo do genoma, e ao realizar testes estatísticos muito cuidadosos, podemos identificar mudanças específicas que parecem aumentar o risco das pessoas desenvolverem depressão,

**Alex**: diferenças genéticas tão específicas, muito específicas que estão mais correlacionadas com alguém que tem depressão.

**Cathryn**: Exatamente, mas o risco real conferido por cada uma dessas alterações individuais é muito, muito baixo. Não estamos no território do distúrbio mendeliano de gene único em que estivemos com a doença de Huntington. Estamos agora num modelo genético poligênico, que é o que parece estar subjacente à depressão, à esquizofrenia, à bipolaridade, ou a todas e também à maioria das doenças físicas que realmente têm impacto na vida das pessoas. Não estamos à procura de alterações genéticas únicas; procuramos alterações genéticas espalhadas por todo o genoma, cada uma das quais tem um efeito muito modesto no risco das pessoas desenvolverem uma doença. Mas quando os reunimos ao longo do genoma, obtemos muito mais informações sobre os riscos.

**Alex**: Então, realmente, o papel das estatísticas em tudo isso é analisar enormes quantidades de dados e descobrir quais são os padrões, quais são os padrões significativos que podemos extrair desses dados?

**Cathryn**: Exatamente, e isso realmente é análise de big data. E são big data de duas maneiras. Nosso genoma é muito grande e precisamos analisar todo esse genoma. E também, porque os riscos conferidos por cada mudança são muito modestos, precisamos aqui de estudos realmente amplos para podermos identificar essas mudanças. Assim, na genética da depressão, há 10 anos, realizamos um grande estudo internacional através do Psychiatric Genomics Consortium (PGC) que reuniu internacionalmente 10000 pessoas com depressão e 10000 pessoas sem depressão. E ficamos muito entusiasmados com isso. Foi o maior estudo já realizado em genética da depressão. E não encontramos absolutamente nada.

**Alex**: Uau.

**Cathryn**: E este foi um estudo massivo; milhões de fundos de pesquisa foram investidos nisso. E, claro, foram, você sabe, 10000 pessoas, você sabe, seu tempo e sua energia, sua participação no estudo, e isso foi extremamente decepcionante na época. E recuamos e pensamos sobre isso e analisamos o que aconteceu em outros estudos, como esquizofrenia e bipolaridade, e em estudos sobre doenças cardíacas e artrite reumatoide que tiveram mais sucesso. E começamos a pensar, bem, o que há de diferente na depressão? E percebemos algumas coisas. Em primeiro lugar, você sabe, a depressão é muito mais difícil de diagnosticar e muitos outros transtornos onde os estudos genéticos tiveram sucesso há 10 anos. E então provavelmente havia muita heterogeneidade nesses estudos que não estávamos levando em consideração. E também, a genética da depressão… a genética é uma contribuição muito mais modesta para o risco na depressão do que na esquizofrenia. Assim, quando analisamos estudos com gêmeos, a herdabilidade da depressão é inferior a 40%, em comparação com até 80% na esquizofrenia. Isso significa que, além da contribuição da genética, há muito mais espaço para a contribuição de outros fatores de risco. E pensamos nisso, penso nisso no contexto do modelo biopsicossocial. Portanto, podemos investigar a parte biológica, mas precisamos reconhecer, especialmente na depressão, que há muito, muito mais acontecendo na parte psicossocial.

**Alex**: Esta é uma conversa muito interessante porque obviamente você vem do lado do big data e eu sou um clínico. E é tão interessante porque, pelo que você está me contando, faz sentido à luz da minha experiência clínica. Que, pela minha experiência clínica anedótica, faz sentido para mim quando você me diz que há uma enorme ou maior influência psicossocial na depressão com esquizofrenia porque com a depressão, por exemplo, você pode ver de forma muito direta e intuitiva como os fatores de estilo de vida, se alguém tem um emprego, se tem um bom relacionamento, se tem amigos, se tem um trabalho significativo pode influenciar se fica ou não deprimido. E então, vamos continuar na frente poligênica. Então, estamos perto de descobrir, por exemplo, quantas alterações genéticas podem estar envolvidas numa doença como a esquizofrenia, ou isso ainda é um mistério, o número total de alterações genéticas envolvidas?

**Cathryn**: Estamos fazendo progressos substanciais. Então, falei sobre o estudo da depressão onde não encontramos absolutamente nada.

**Alex**: Por que você acha que não encontraram nada?

**Cathryn**: Porque, hum, porque, estatisticamente, os estudos são sempre uma mistura de sinal e ruído, e você precisa obter sinal suficiente para se destacar do ruído. E esse estudo, apesar de ter tido 9000 pessoas que contribuíram generosamente para a nossa investigação, simplesmente não foi suficiente. E então, tendo recuado e pensado sobre isso, tivemos... tivemos a confiança para dizer que só precisamos continuar, trata-se de tamanho da amostra e, uh, e então saímos, aumentamos substancialmente o tamanho da amostra, colaboramos com muito mais pessoas, e nosso último estudo genético, que ainda não foi publicado, temos falado sobre isso em conferências, agora identificamos 500 variantes genéticas em todo o genoma que acreditamos desempenharem um papel na depressão.

**Alex**: Quantas pessoas foram necessárias?

**Cathryn**: Essa é uma pergunta muito boa. Foram necessários meio milhão de pessoas com depressão para descobrir isso. E algumas pessoas, pensando nisso no modelo biopsicossocial, algumas pessoas dizem: "Bem, por que você se preocupa? Se você realmente precisa de tantas pessoas para encontrar essas mudanças genéticas muito modestas, você sabe, bem, não deveríamos nos concentrar nosso tempo, nossa energia e nosso dinheiro em fazer coisas diferentes para resolver a depressão?" E acho que minha resistência a isso é que precisamos fazer tudo o que pudermos em nossa depressão e em todos os transtornos de saúde mental. Você sabe, é um grande problema para a sociedade, para as pessoas que foram diagnosticadas e para as famílias que cuidam delas. E precisamos fazer tudo o que pudermos, adotando todos os ângulos que possam nos ajudar a diagnosticar, tratar e talvez até prevenir esses transtornos. E a genética nos permite acessar essa biologia subjacente, e isso é realmente difícil de controlar nos transtornos de saúde mental. Exatamente, e não temos biomarcadores; você sabe, não podemos fazer um exame de sangue e identificar pessoas de alto risco ou usar isso para um diagnóstico. E assim, espero que a genética nos dê uma ideia dessa biologia subjacente. Vai nos contar mais sobre porque as pessoas ficam deprimidas, quais são os caminhos para isso, quais são as mudanças no cérebro, no corpo, que podem levar à depressão. E então, é claro, isso nos dá perspectivas sobre como poderíamos ajudar a evitar isso. Você sabe, isso nos dá novos alvos de medicamentos que poderemos desenvolver

**Alex**: ou outras intervenções como a estimulação cerebral estão se tornando mais envolvidas?

**Cathryn**: Sim, exatamente, sim.

**Alex**: É realmente interessante. Então, conversei com ele esta semana, conversei com Nolan Williams, que é psiquiatra em Stanford e é especialista em estimulação cerebral. E ele realmente disse, com base em seu trabalho, que faz tratamentos de estimulação cerebral muito intensos, estimulação magnética, ele descobriu, ao fazer isso e ao estudar pessoas em exames de ressonância magnética, que há um subconjunto de pessoas com depressão onde a depressão parece estar correlacionada com , se não for causado por uma área do cérebro sendo ativada antes de outra área do cérebro - o córtex cingulado anterior sendo ativado antes do córtex pré-frontal dorsolateral (eu sei que isso é demais, me desculpe). E através da estimulação, você pode reverter essa temporalidade, onde uma área é ativada antes da outra e a regula, e isso parece ter um efeito incrível na apresentação clínica das pessoas; eles ficam muito menos deprimidos.

Então, absolutamente, a biologia é fundamental. Sabemos, temos uma noção de quantas ou quantas mudanças encontramos variações genéticas em condições como esquizofrenia, bipolaridade, e há uma sobreposição entre as duas?

**Cathryn**: Para esquizofrenia e transtorno bipolar, encontramos mais de 200 variantes para cada um deles. Mas, apesar de tudo isso, sabemos que essa é a ponta do iceberg. Você sabe, há muito mais para descobrir. Há uma sobreposição entre eles, há uma sobreposição entre todos os transtornos psiquiátricos, e o modelo, a maneira como pensamos sobre isso atualmente, é que provavelmente existem algumas alterações genéticas, alguns genes envolvidos que são relevantes para o cérebro em geral e em todos os aspectos. diagnósticos diferentes. E então é provável que haja outras variantes que sejam exclusivas talvez de subgrupos de transtornos ou de transtornos e condições individuais. E assim, mas trabalhando também através de diagnósticos e transdiagnosticamente, a genética deveria novamente ajudar-nos a fazer isso e mostrar onde estão as semelhanças e onde estão as diferenças.

**Alex**: Porque, na verdade, esse quadro genético (não tenho certeza se você está ciente disso) é muito desafiador para nossa estrutura diagnóstica como médicos, porque colocamos os diagnósticos em categorias ou grupos. Dizemos que esta pessoa tem uma condição psicótica, como esquizofrenia, ou esta tem um transtorno de humor, como bipolar, quando parece estar em algum lugar entre os dois, chamamos isso de transtorno esquizoafetivo ou depressão, ou o que quer que seja. E esta imagem é muito contínua, onde há muitos genes diferentes e em algum lugar pode estar em qualquer ponto do espectro, e então esses genes, sobre os quais gostaria de falar mais tarde, têm que interagir com estímulos ambientais. Isso mostra um quadro onde as pessoas realmente não estão em uma categoria ou outra, mas tudo é uma espécie de espectro. Você concordaria com essa noção?

**Cathryn**: Sim, e provavelmente um espectro multidimensional, e nada disso será fácil, e como a genética pode ajudar nisso? Bem, quero dizer, você falou sobre pessoas que não se enquadram em um determinado grupo de diagnóstico, e eu sei que os diagnósticos das pessoas mudam ao longo da vida e seus sintomas mudam. E eu espero que a genética possa nos dar uma perspectiva sobre isso, porque a nossa genética permanece constante durante toda a vida. E esse é um dos valores reais dos testes genéticos, é que as variantes de que estamos a falar, herdamos elas dos nossos pais, e elas permanecem estáveis ​​durante toda a vida. E assim, se pudéssemos obter alguma informação sobre como a genética pode ajudar a prever o prognóstico, como poderá a saúde mental das pessoas evoluir ao longo da vida, o que a sua genética indica que podem estar em maior risco de desenvolvimento, espero que esse tipo de informação possa tornar-se útil no diagnóstico. Nunca será a resposta completa; nada será a resposta completa em psiquiatria; é tudo muito complexo. Mas precisamos tomar, precisamos trabalhar juntos. Eu, como geneticista, preciso trabalhar com você como psiquiatra. Precisamos trabalhar com pessoas que fazem estimulação cerebral e neuroimagem e trabalhar com psicólogos e sociólogos e olhar para isso na sua totalidade para ver como podemos progredir.

**Alex**: Quero dizer, como médico, acho que ter mais informações genéticas sobre um determinado paciente seria extremamente útil. Então, porque ficamos envolvidos em mistérios de diagnóstico o tempo todo, e isso pode ser muito intrigante, e claro, as pessoas mudam sutilmente de um dia para o outro se dormiram o suficiente, que medicação estão tomando, mas se podemos obter alguns dados concretos, por exemplo, testes sofisticados o suficiente para dizer: "Esta pessoa tem 150 das 200 alterações associadas ao transtorno afetivo bipolar, e ela tem 50 das alterações associadas à esquizofrenia", por exemplo, Posso realmente ver que isso traria um enorme valor para os médicos e para os próprios pacientes. Porque grande parte do problema de não estar bem é a enorme quantidade de sofrimento mental de não estar bem, é o mistério. E obviamente, como você está dizendo, não queremos adotar uma abordagem muito dura, onde a genética é tudo, mas qualquer coisa que possa nos ajudar a esclarecer essas complexidades pode ser muito terapêutica, eu acho.

**Cathryn**: Esse é um ponto muito bom, e estamos começando a fazer isso por meio de escores poligênicos. Agora, essas variantes individuais que temos, as 500 variantes para depressão, mais de 200 para esquizofrenia e bipolar, individualmente, nos dão pequenas quantidades de informação. Não podemos usá-los sozinhos. Mas quando os juntamos ao longo do genoma, podemos construir escores poligênicos, que fazem exatamente o que acabamos de dizer. Analisa quantas dessas variantes de risco alguém carrega. Agora, você sabe, todos nós carregamos algumas dessas variantes de risco, e a maioria das pessoas carrega um número médio, então a genética da depressão não lhes dirá muito; eles terão uma carga média para depressão. Mas algumas pessoas podem apresentar escores poligênicos elevados para depressão porque, por acaso, herdaram mais dessas variantes de risco dos seus pais do que outras pessoas. E isso é algo que estamos começando a analisar: como esses escores nos permitem observar a propagação do risco na população. Então, até agora, a quantidade de risco que eles explicam é bastante baixa. Por exemplo, na esquizofrenia, onde talvez tenhamos os perfis genéticos mais fortes até à data, se olharmos para as pessoas que têm os escores poligênicos mais elevados, então os 10% da população que estão em maior risco e os 10% que estão em menor risco, a diferença no risco de esquizofrenia é cerca de 16 vezes, para usar um risco relativo.

**Alex**: Então, 16 vezes mais provável.

**Cathryn**: sim, exatamente. Assim, os 10% das pessoas com maior risco têm 16 vezes mais probabilidade de desenvolver esquizofrenia do que os 10% com o menor risco.

**Alex**: o que é bastante substancial porque o risco de esquizofrenia é de cerca de um por cento no início do estudo, ou seja, 16 por cento,

**Cathryn**: mas isso deixa de fora os 80 por cento intermediários dessa distribuição e outra maneira de ver isso é dizer, bem, o que podemos querer fazer sobre isso? Outra perspectiva sobre isto é dizer, bem, se pudéssemos identificar as pessoas que correm o 1% de risco mais elevado, então aquela um em cada cem pessoas que têm a carga genética mais elevada para a esquizofrenia, e comparássemos o seu risco com todos senão, o que seria isso? Quão grande seria isso? Vale realmente a pena conhecer, identificar o que é o mais elevado? E aí há um aumento de seis vezes no risco, então isso é muito mais modesto. Na verdade, isso quer dizer que, embora saibamos bastante sobre a genética da esquizofrenia, ela por si só ainda não nos dá sinais suficientes de que seria útil.

**Alex**: Mas você disse que o 1%, o 1% do topo, tem um aumento de 6 vezes em comparação com todos os outros? Qual proporção teve 16 vezes?

**Cathryn**: Uh, então o risco de 16 vezes estava olhando para os dez por cento superiores e inferiores. Está bem, está bem. Então, eles estão olhando para os extremos reais, e isso é estatisticamente válido, mas é uma estatística que diz: "Certo, se olharmos para os extremos reais, o que isso nos diz?" E essa é uma informação realmente útil para estudos de pesquisa. Poderíamos usar muito isso para comparar, você sabe, pessoas que se inscreveram em estudos de pesquisa e que apresentam o maior e o menor risco. Mas isso não é tão útil para você como médico. E como médico, eu penso, você sabe, focando nas pessoas com maior risco e dizendo: "Isso me diz muita coisa?" e em nível populacional, acho que não. Mas onde pode ser útil é, você sabe, onde alguém apresenta sintomas. Então, talvez alguém tenha tido seu primeiro episódio de psicose ou esteja em um grupo de risco ultra-alto, você sabe, incluindo a genética junto com todas as outras informações que você tem sobre seus pacientes, que eu acho que podem ser úteis.

**Alex**: E poderia ajudar aconselhar os indivíduos ou seus médicos sobre quais fatores de estilo de vida encorajar ou evitar. Então, algo sobre o qual falamos muito neste podcast é a associação entre cannabis e psicose, o que é um pouco complicado de explicar, pois a maioria das pessoas que usam cannabis não encontrará nenhum problema, o que é importante quando estamos pensando em política jurídica e coisas assim. Mas uma minoria substancial ou uma minoria significativa pode desenvolver uma doença psicótica, e isto foi estudado epidemiologicamente por Marta de Forte num enorme ensaio multicêntrico onde existe uma correlação clara entre o consumo de cannabis e o desenvolvimento de sintomas psicóticos. E acho que, mesmo de forma anedótica, muitas, muitas pessoas conhecem aquela pessoa, quando era criança, que fumou muita maconha e acabou desenvolvendo algum tipo de problema de saúde mental. Então você acha que esses escores poligênicos de risco, especialmente quando forem mais sofisticadas, quando conhecermos mais sobre as variantes genéticas, seremos capazes de nos dizer: "Você precisa ficar longe disso, daquilo ou daquilo outro? "

**Cathryn**: Acho que isso seria muito útil e certamente estamos caminhando nessa direção. Hum, e tenho o prazer de trabalhar com Marta de Forte e ouvir sobre sua pesquisa maravilhosa. E acho que isso é realmente útil ou potencialmente útil numa mensagem de saúde pública. Hum, mas a razão pela qual é útil é porque temos o sinal genético e temos uma intervenção. Você sabe, nós sabemos que, bem, com uma carga genética muito alta, talvez você realmente não devesse fumar cannabis. Portanto, conhecer a genética não é suficiente; precisamos saber o que fazemos a respeito, e acho que a genética da esquizofrenia e da cannabis é o exemplo perfeito disso.

**Alex**: Ou alguém com alto risco de depressão, digamos, quando adolescente, você poderia ensinar-lhe certas habilidades, habilidades cognitivo-comportamentais em torno da flexibilidade mental, porque a flexibilidade mental é muito importante para tratar e prevenir a depressão, por exemplo.

**Cathryn**: Sim, exatamente. E também talvez o potencial do exercício, que muitas pessoas diriam que tem um papel tanto na prevenção como na aceleração da recuperação da depressão. Hum, e é muito fácil para nós que estamos aqui sentados apresentar esses exemplos potenciais de onde isso pode acontecer, onde a genética pode ser útil. Mas, você sabe, não somos, não somos muito bons em avaliar riscos; não somos muito bons em lidar com informação genética porque, como sociedade, nunca tivemos que fazer isso antes.

**Alex**: É contra-intuitivo.

**Cathryn**: Isso é. E acho que me preocupo um pouco se começaremos a dizer aos adolescentes: "Bem, vocês não deveriam fumar cannabis porque têm um alto risco genético de desenvolver esquizofrenia ou psicose". Essa é uma mensagem muito difícil de transmitir a um adolescente, e eu acho…

**Alex**: não é marketing fácil.

**Cathryn**: Temos um longo caminho a percorrer para garantir que nossas comunicações sobre genética sejam feitas de uma forma que seja útil para as pessoas, que não seja assustadora, que seja vantajosa, que não aumente o estigma, mas que vá ser útil para todos os envolvidos.

**Alex**: E suponho que de certa forma isso seja preciso porque, você sabe, estamos tendo uma longa conversa telefônica, apenas para desvendar as diferentes peças disso, e temos exemplos históricos, obviamente, de genética e um argumento genético sendo mal representado em para justificar um objetivo ideológico ou um objetivo político, coisas nesse sentido. Então, acho que há um problema com a nossa espécie: desenvolvemos tecnologia muito mais rápido do que desenvolvemos a capacidade de compreendê-la eticamente. Se desenvolvermos armas atômicas e então tivermos que descobrir como vamos pensar sobre isso em uma estrutura ética, e acho que o mesmo poderia ser dito com a genética, porque talvez eu pudesse perguntar a você, você acha que há uma potencial escuridão? lado da genética e melhorar a nossa compreensão genética, que ela poderia ser usada para fins prejudiciais no futuro?

**Cathryn**: Acho que o potencial certamente existe, e precisamos ter muito cuidado sobre como falamos sobre genética e sobre o aumento da alfabetização genética das pessoas, para que elas entendam que a genética não é apenas um sim-não, que as pessoas correm alto risco de um transtorno ou não, mas é uma medida contínua. Medir a propensão genética de alguém para a depressão, para a esquizofrenia, você sabe, é como medir a altura de alguém; não é um sim-não, é, você sabe, as pessoas são de risco médio, algumas de alto risco e outras de baixo risco. Mas creio que também vimos áreas onde a genética pode ser mal utilizada. Assim, vimos a genética entre diferentes grupos populacionais em todo o mundo a ser usada como justificação para a discriminação, sendo aproveitada pela extrema direita para justificar as suas perspectivas. Outra área que estamos vendo e que preocupa muitos de nós na pesquisa genética é a utilização desses riscos poligênicos para doenças em locais que não são apropriados. E vemos, falamos sobre o risco da esquizofrenia ser útil, mas não por si só; precisa estar em contexto com todo o resto. Mas há algumas empresas que oferecem riscos genéticos como parte do rastreio de embriões na fertilização in vitro, e fazem-no porque temos a tecnologia e estão a aplicá-la. Mas acho que temos que ter muito cuidado nesses casos, pois o que somos, o que, a forma como aplicamos a nossa informação genética é realmente sustentada por sólidas preocupações éticas e estatísticas.

**Alex**: Você acha que, no caso dessas empresas, o problema é que elas estão representando falsamente o quão útil é a tecnologia, quão precisa ela é, ou é apenas que ela realmente tem utilidade comprovada na triagem de certas condições, mas eles estão apenas marchando em frente sem qualquer tipo de pensamento quanto à ética?

**Cathryn**: eu não acusaria nenhuma dessas empresas de avançar sem considerar a ética; isso seria antiético da minha parte. Mas, pelo que li sobre a ciência e os riscos conferidos, é muito difícil ver que seja justificável tomar uma decisão sobre quais os embriões a implantar, com base, por exemplo, num escore poligênico para a esquizofrenia. E, claro, as preocupações a jusante são, vocês sabem, o impacto no estigma, o impacto nesta ideia de que poderíamos remover os transtornos mentais através de um simples teste genético. É realmente preocupante, é completamente inapropriado e penso que precisamos de discussões sociais muito mais amplas.

**Alex**: E parece que ainda há muito mistério em todo esse processo para fazer essas afirmações e comercializar essas coisas como uma espécie de... Posso facilmente fantasiar sobre como o marketing tem um maior grau de certeza.

**Cathryn**: Exatamente, e acho que tem muito barulho. Quero dizer, para colocar isto em contexto, os riscos que temos para a esquizofrenia representam cerca de sete por cento da compreensão geral dos riscos da esquizofrenia. Assim, podemos estimar o que está acontecendo nesses sete por cento, restando 93 por cento que não incluímos nesse cálculo, nessa avaliação.

**Alex**: Hum, como o ambiente interage com nossa genética para influenciar uma apresentação específica?

**Cathryn**: Essa é uma pergunta muito boa, e temos esse conceito de interação gene-ambiente que faz parte de estudos de pesquisa há décadas, e nosso entendimento é que, para a maioria dos exemplos, não é uma interação, mas é um aditivo, um efeito combinado e o que quero dizer é que a genética e o ambiente se combinam para dar cumulativamente um risco do transtorno, mas não interagem a nível estatístico. Sim, então o que quero dizer com interagir aqui é que, bem, vamos olhar para isto ao contrário, que os genes e o ambiente parecem contribuir de forma independente, por isso o risco genético de alguém para uma doença irá dar-lhe uma certa quantidade de risco, o seu componente ambiental lhe dará outro risco, e podemos simplesmente adicioná-los. Se há uma interação, isso significa que o meio ambiente, a forma como o meio ambiente contribui depende da genética, e não é isso que estamos vendo na maioria dos casos. Então, você sabe, nossa compreensão intuitiva, eu acho, ou um pensamento útil foi, bem, se as pessoas têm um risco genético realmente alto e um ambiente pobre, talvez isso faça com que seus riscos aumentem, você sabe, talvez a combinação de duas coisas ruins realmente levará a um risco muito, muito maior.

**Alex**: Você pensa em um composto,

**Cathryn**: sim, mas não é isso que estamos vendo, estamos vendo que há um efeito aditivo, e a evidência disso ainda é bastante modesta nos transtornos de saúde mental, mas é isso que estamos vendo nas doenças cardíacas, digamos, onde temos um controle muito melhor sobre os efeitos de risco tradicionais, você sabe, da obesidade, do colesterol, e combinamos isso com a genética, e eles parecem ser aditivos. Então, eu sempre, como estatístico, recuo quando as pessoas falam sobre interações porque o que parecemos estar vendo é mais um efeito conjunto aditivo.

**Alex**: isso talvez não se encaixe, talvez haja algo que não se encaixe com o que entendemos sobre parte da biologia, porque meu entendimento é que certos genes podem ser ativados ou desativados dependendo de gatilhos ambientais, mas esse conceito, a ideia de que os genes podem ser ligados ou desligados, isso se enquadra no seu entendimento estatístico?

**Cathryn**: Acho que sim porque esses modelos, você sabe, são complexos, e não acho que o modelo que você descreveu entraria em conflito com um efeito aditivo. Mas temos um longo caminho a percorrer, quero dizer, você sabe, já falamos sobre o rápido progresso que fizemos nos estudos genéticos nos últimos 10 anos, e à medida que nossa compreensão melhora, à medida que sabemos mais sobre a genética e na biologia, podemos, você sabe, encontrar efeitos interativos, mas o que acho que podemos dizer é que eles não são, você sabe, não são o sinal esmagador que estamos encontrando.

**Alex**: porque acho que talvez a maneira como eu estava usando a interação fosse diferente da maneira como você quis dizer interagir matematicamente e eu quis dizer interagir como no ambiente, os estímulos ambientais ligando ou desligando um gene.

**Cathryn**: Sim, você está certo, sim, os termos estatísticos e biológicos são um pouco diferentes e enfatizam o fato de que precisamos trabalhar juntos, precisamos combinar todas essas diferentes perspectivas.

**Alex**: Então, falamos muito sobre condições psiquiátricas, você conhece os estados patológicos, mas vamos falar sobre um estado não patológico, mas ainda psicológico, como a personalidade. A genética influencia nossa personalidade?

**Cathryn**: A genética tem influência em nossa personalidade e eu diria que a genética tem uma influência em tudo. A pergunta que deveríamos realmente fazer é qual é o tamanho da influência genética? Hum, e a influência na personalidade é bastante alta e, claro, isso também tem um impacto na saúde mental. Portanto, o neuroticismo como traço de personalidade está altamente correlacionado com a depressão.

**Alex**: E o que é neuroticismo? Devo apontar aos nossos ouvintes. Ok, há duas coisas que quero destacar. A primeira coisa é a maneira como a personalidade é usada tecnicamente. Quero dizer, é assim que usamos a personalidade coloquialmente, e nos deparamos com isso quando, por exemplo, falamos sobre isso ou sobre transtornos de personalidade. Quando falamos tecnicamente de personalidade, queremos dizer um conjunto de características que são estáveis ​​ao longo da vida e que influenciam a interação de alguém consigo mesmo, com o mundo e com outras pessoas. Essa é a minha definição de personalidade em discurso de elevador. Hum, acho que é muito importante ter isso em mente. Essa era a segunda coisa que eu ia apontar, da qual não consigo me lembrar agora. Hum, o neuroticismo é usado em muitos contextos diferentes na psicologia e na literatura psicanalítica. O que queremos dizer quando falamos de neuroticismo neste contexto?

**Cathryn**: Então, neste contexto, o neuroticismo através de uma série de questões que, hum,

**Alex**: então penso nisso como uma sensibilidade ao estresse. Então, quanta desregulação emocional você experimenta por unidade de estresse? Da mesma forma que você pega a pessoa A e a pessoa B, ambas perdem o emprego, a pessoa A terá uma resposta emocional específica e a pessoa B terá uma resposta emocional específica, e é bem provável que sejam diferentes. As pessoas são diferentes, respondem emocionalmente de maneira diferente a unidades aproximadamente iguais de estresse. Mas neuroticismo não tem um bom nome resiliência psicológica, então esse é um problema que aconteceu, mas, hum, sim, como, então como, em média, que tipo de influência a genética está tendo em nossa personalidade?

**Cathryn**: Portanto, a genética tem influência na personalidade, e vemos isso em estudos em todo o mundo, em estudos com gêmeos e estudos genéticos. Você sabe, sabemos que há uma grande contribuição, exatamente da mesma forma que há uma contribuição para os transtornos de saúde mental, e é exatamente o mesmo tipo de modelo que é poligênico. Você sabe, estamos começando a identificar variantes individuais que contribuem para os traços de personalidade, para o bem-estar, para qualquer forma que queiramos medir a personalidade de alguém. Mas, novamente, cada uma dessas variantes individuais tem um efeito muito pequeno, e estamos novamente começando a identificar os perfis poligênicos que contribuem para a personalidade de alguém.

**Alex**: Acho que as pessoas terão uma resistência inerente à ideia de que existe alguma influência genética na personalidade porque tem aquele sabor de determinação biológica, e a personalidade é realmente importante. Então, se você considerar uma característica como conscienciosidade, a conscienciosidade das pessoas está altamente correlacionada com o sucesso na vida, e isso se subdivide em diligência e normalidade. Portanto, diligência é literalmente o quanto você trabalha. Obviamente, você pode ver como isso teria uma correlação com o sucesso. Se as pessoas descobrissem que, seja geneticamente ou não, elas têm uma particularidade, porque você pode fazer um teste e descobrir qual é a sua personalidade ou quais características você tem em alta ou baixa, isso é isso, isso é uma sentença de prisão? Você está vinculado a isso? Ou há coisas que você pode fazer para mudar seus traços de personalidade?

**Cathryn**: Eu quero recuar nessa frase sentença de prisão, absolutamente não. Nenhuma das genéticas de que estamos falando neste contexto, esses modelos poligênicos, nenhum deles é determinístico. Você sabe, eles são probabilísticos e se combinam com o ambiente, com sua família, você sabe, com a sociedade em que você está. Eles podem lhe dar uma certa predisposição herdada que pode empurrá-lo para um certo caminho para começar, mas que a genética sempre estará misturada com tudo o mais a que você está exposto.

**Alex**: Quais são algumas dicas ou talvez princípios que você descobriu para construir uma carreira de sucesso na ciência? O que é algo muito difícil de conseguir. Quais são algumas coisas que você aprendeu ao longo dessa estrada?

**Cathryn**: Então construir uma carreira de sucesso, tantas coisas diferentes. Acho que flexibilidade e resiliência são uma delas. A ciência em si é um acaso, quer saber, se os estudos em que você está envolvido, você sabe, recebem financiamento, têm um resultado bem-sucedido, estão na moda e são populares no meio científico, tudo isso depende muito da sorte. Depende muito de com quem trabalhamos, você sabe, de ter mentores e supervisores de apoio que possam avaliar seus pontos fortes e ver, você sabe, como você pode se desenvolver melhor e em que direção você poderia estar se movendo para ajudá-lo a prosperar. Hum, é realmente importante. Mas também aquela capacidade de se recuperar, você sabe, de trabalhar naquele ambiente pessoal, naquele ambiente profissional onde quando seu artigo é rejeitado por um periódico pela terceira vez ou seu pedido de financiamento não é financiado novamente, você sabe, isso ser capaz de pensar "certo, qual é o plano B aqui? para onde devo ir a seguir? e como as pessoas podem me ajudar a alcançar o que desejo?"

**Alex**: Portanto, sua atitude em relação ao fracasso é muito importante.

**Cathryn**: Sim, quero dizer, você sabe, eu sento aqui como acadêmica, como professora, mas trabalhar em uma universidade é apenas um dos lugares onde a ciência de excelência acontece. Muitos dos meus alunos de doutorado e muitos dos meus pós-doutorados, você sabe, não permanecem na academia, mas passam para a indústria, para a indústria farmacêutica, para a biotecnologia, para o trabalho político, para organizações governamentais e do terceiro setor. Existem tantas carreiras diferentes e fascinantes com base científica onde nossos estagiários podem prosperar, e eu incentivo essa amplitude de descoberta em todas as opções disponíveis.

**Alex**: E outra coisa que observei sobre a ciência de fora, eu nunca fiz pesquisa. É que isso requer um equilíbrio muito delicado entre curiosidade e mente aberta, por um lado, e depois ser cético e detalhista, por outro. E essas duas coisas nem sempre andam juntas, mas pelo que observei, os melhores cientistas parecem ser capazes de fundir ambas, ou pelo menos as equipes e os laboratórios. As melhores equipes e laboratórios têm pessoas que são boas em ambos. Essa foi a sua experiência ou foi algo diferente?

**Cathryn**: Gosto dessa perspectiva de olhar para a ciência. Hum, e você falou sobre uma pessoa ter ambos. Para mim, muito disso tem a ver com trabalho em equipe, você sabe. Então você obtém uma descoberta maravilhosa, você sabe, você aperta o botão no computador e obtém seu valor p altamente significativo, e fica entusiasmado com isso na reunião de equipe. E então, você sabe, os bons cientistas que trabalham com você estarão dizendo, bem, e quanto a isso, e você explicou isso e controlou isso? E será esse equilíbrio dessa empolgação, dessa moderação, dessa verificação, dessa análise de sensibilidade.

**Alex**: Onde você se vê? Você é o entusiasta ou a influência moderadora ou ambos?

**Cathryn**: Sou estatístico. Eu sou um cético, e sou um cético em relação a cada número que as pessoas me apresentam, e elas têm que me justificar e me mostrar isso, você sabe, o que quer que façam com seus dados, qualquer perspectiva que tenham sobre esse estudo, esse efeito não desaparece, então vou acreditar.

**Alex**: Ok, então deveríamos trabalhar juntos porque sou definitivamente um entusiasta.

**Cathryn**: Seria uma ótima parceria.

**Alex**: Hum, você era um ouvinte deste podcast e estou constantemente tentando torná-lo melhor, e estou constantemente perguntando, você sabe, o que você ganha ao ouvi-lo e como poderia ser melhor?

**Cathryn**: Hum, sou um grande fã do podcast. Eu aprendi muito, hum, tanto dentro quanto fora da minha área que realmente me ajudou, você sabe, a me desenvolver como cientista e trabalhando com saúde mental, e realmente sendo apreciado. Hum, quero dizer, como já falamos, sou um estatístico. Muitas vezes vejo as coisas de uma perspectiva numérica, em vez de uma perspectiva de pessoas, e ouvir podcasts como este realmente me fez apreciar a verdadeira diversidade do trabalho que acontece e o valor das pessoas com experiência vivida, e como, você sabe, conseguir pessoas envolvidas na pesquisa, qualquer que seja a sua experiência, é essencial para que pessoas como eu façam uma boa pesquisa. Então, eu diria apenas para continuar com essa diversidade.

**Alex**: Preciso mais da sua moderação.

**Cathryn**: Mais genética, mais biologia, mas é essa diversidade que, para mim, é a verdadeira força do seu trabalho.

**Alex**: Professora Lewis. Muito obrigado.

**Cathryn**: O prazer é meu. Obrigado por me receber, Alex.
