---
title: "Capítulo 10.2: Cuidados na Predição Genética"
---

# ***Cuidados na Predição Genética*** {#sec-section1}

**Título:** Prevendo a probabilidade de futuros transtornos psiquiátricos: um olhar mais atento e alguns cuidados

**Apresentador(es):** Howard Edenberg , PhD (Department of Biochemistry and Molecular Biology, Indiana University School of Medicine)

Prever a probabilidade de futuros transtornos psiquiátricos parece muito atraente, especialmente se houver a possibilidade de uma intervenção precoce eficaz. Mas vamos dar uma olhada mais de perto e observar alguns cuidados antes de avançar muito rapidamente.

Olá sou Howard Edenberg, da Universidade de Indiana.

Os transtornos psiquiátricos e por uso de substâncias são transtornos genéticos complexos. O risco é afetado tanto pelos genes quanto pelo meio ambiente. Nenhum deles trabalha sozinho e interage, às vezes de maneiras complexas. Para muitos transtornos, incluindo os transtornos por uso de substâncias, a contribuição genética total para o risco é aproximadamente igual à contribuição ambiental, e para transtornos por uso de substâncias há um componente ambiental necessário: o consumo ou uso da substância. Assim, a genética nunca irá prever completamente futuros transtornos psiquiátricos, particularmente os transtornos por uso de substâncias.

Mesmo os estudos genéticos mais bem desenvolvidos até o momento estão longe de ser capazes de fazer predições confiáveis. Estamos apenas começando a identificar as variações genéticas que afetam o risco. Para os transtornos por uso de substâncias, por exemplo, transtornos por uso de álcool, neste momento, as variantes comuns medidas em todo o genoma predizem apenas uma pequena fração do risco, cerca de 10 por cento, portanto as atuais tentativas de predição são, na melhor das hipóteses, prematuras. O que torna tais tentativas ainda mais problemáticas é o risco de as pessoas poderem sofrer estigma associado ao fato de serem rotuladas como tendo um transtorno por uso de substâncias ou um transtorno psiquiátrico.

Existem, no entanto, algumas alegações de precisão muito elevada na predição do risco de um transtorno complexo como a dependência de opióides. Soubemos de uma empresa que afirma ter um teste para aconselhar os médicos se alguém tem probabilidade de se tornar dependente de opioides antes que o médico prescreva opioides para o alívio da dor. A predição da empresa baseia-se no treinamento de um modelo de aprendizado de máquina em um pequeno conjunto de casos e controles usando um punhado de variantes genéticas, apenas 15, que são supostamente provenientes de vias de recompensa cerebral, e reivindicam uma precisão extraordinariamente alta. Examinamos suas reivindicações e encontramos sérios problemas. Os SNPs do sistema de recompensa cerebral escolhidos diferem nas frequências alélicas em diferentes populações, e os modelos de aprendizado de máquina baseados nesses SNPs escolhidos acabaram prevendo a ancestralidade genética muito melhor do que previram o risco. Na verdade, descobrimos que os SNPs aleatórios correspondentes às mesmas frequências alélicas menores tiveram o mesmo desempenho que esses SNPs do sistema de recompensa cerebral. Portanto, existem sérios problemas com a suposta precisão deste teste. O primeiro problema, claro, é que a predição não é precisa e pode, portanto, levar a decisões médicas erradas. Em particular, isto pode levar ao subtratamento da dor nos indivíduos que são sinalizados como estando em risco aumentado de dependência de opióides. Como o teste detecta diferenças de ancestralidade, pode levar a um aumento da discriminação médica contra aqueles de algumas ancestralidades e pode estigmatizar aqueles que se prediz estarem em risco. Ter isso marcado nos registos médicos pode afetar o tratamento no futuro e, claro, a estigmatização pode ir além do mero tratamento médico para a sociedade em geral. Publicamos nossas análises desses testes específicos no medRxiv para aqueles que gostariam de saber como chegamos a algumas das conclusões que acabei de transmitir a vocês. \[Agora publicado: PMID: 34710714; PMCID:[PMC9358969](http://www.ncbi.nlm.nih.gov/pmc/articles/pmc9358969/)\]

Portanto, esta foi uma história de advertência. Embora nosso estudo tenha se concentrado em um exemplo de teste preditivo para transtorno por uso de opioides, é provável que surjam questões semelhantes em testes para outros transtornos por uso de substâncias e transtornos psiquiátricos em geral. Especialmente porque estes tipos de transtornos são frequentemente acompanhados de estigma, temos de ter especial cuidado para que os nossos testes sejam precisos, para que os nossos testes não discriminem pessoas de diferentes ancestralidades e para que o bem que eles fazem supere o potencial de estigmatização.

Obrigado por ouvir meus comentários
