---
title: "Chapter 10.4: Language in Genetics Research (Video Transcript)"
---

**Title**: Bioessentialism

**Presenter(s)**:

-   Carina Seah, MSc (Department of Genetics and Genomic Sciences, Icahn School of Medicine at Mount Sinai)

-   Kayla Townsley, MSc (Department of Genetics and Genomic Sciences, Icahn School of Medicine at Mount Sinai)

**Carina Seah**:

Hi there, my name is Carina Seah. I am an MD, PhD candidate at The Icahn School of Medicine at Mount Sinai, co-mentored by Kristen Brennand and Laura Huckins. Today, we're going to start by telling you a little bit about biological essentialism, explaining what that is, how it impacts our science, and how we can avoid kind of the flaws and misconceptions of it. This is a part of a project designed through the Racism and Bias Initiative and Center for Anti-Racism in Practice at Mount Sinai, and we are RBICAP Fellows along with Kayla Townsley.

Before we get started, this is an evaluation to get an idea of the kind of context and information and understanding you come into the course with. So if you can take a couple of minutes to pause here, scan this QR code, and take the evaluation, that'd be fantastic.

Okay, so let's get started into "what is biological essentialism?" and "how does it play a role in our science?". Before we get started, we always start with grounding assumptions. Usually, when we do this in a discussion, we touch upon sensitive topics. We touch upon a lot of historical harms. Feel free to pause, step away, take whatever time you need, understand, and sit with any discomfort you may feel, and understand that's normal, a part of the process of growing and learning, and forgive yourself for anything that you don't already know, anything that you are starting to learn, and sustain yourself in this journey.

*What is Biological Essentialism?*

So let's start with a unifying definition of biological essentialism. At the most basic, biological essentialism is an attribution of social categories to underlying fixed biology. So these social categories can be things like race, gender, and sexuality that can be assigned to something like ancestry, genetics, sex, or hormones. So, biological essentialist beliefs will take these social categories and attribute them to predetermined biological factors, and then, using biological essentialism theory, they use biological processes to explain these social categories.

*The Three Claims of Biological Determinism/Essentialism*

There are three main tenets of biological essentialist theory, and these assumptions are used to guide that attribution of social categories to biology. So, the first one is that inequalities observed in society are directly because of differences in intrinsic merit and ability amongst individuals. The second is that since social inequalities are based on intrinsic differences between individuals, these intrinsic differences are explained by genetic or biological differences. And then, finally, these biological differences between people exist as a natural hierarchy, which translates into hierarchical status, wealth, and power. So, this allows biological essentialism to explain hierarchical structures that exist within society through these biological means.

So, from this, we can trace some biological essentialist beliefs by taking some of these social categories and filtering them through biological essentialist logic. So, to start, we have that immutability of these fixed social characteristics and attribution of them to biology. So, that would be something like saying race is genetic or races are genetically distinct or saying that gender is determined by biology, such as sex chromosomes and external sex organs. Because now you've defined these social characteristics as biological, now you can apply biological theories to these traits. So, evolutionary theory or survival of the fittest defines a biological reason for there to be biologically distinct abilities, which is that some sort of evolutionary selective pressure may lead to different biological roles, for example, races or genders. So, that's the application of this theory to the "biologic-ification" of race and gender. And then finally, what evolutionary theory does is it provides a merit-based hierarchy where something like evolutionary fitness or superiority is translated to the biological superiority of certain traits, which puts forth that society is hierarchical based on this ability and based on superiority.

So let's trace a common societal assumption and role and show how the underlying stigma or connotations behind it may be upheld by biological essentialist beliefs. So, if we take the identity of "housewife" in society today, we can start by outlining how the social identity of being a woman is conflated with biology. So, the first thing is by defining a woman biologically, like, for example, by their sex chromosomes or external sex organs, you are able to biologically categorize women, such as by ability to carry a child or by the size of their head, anything like that. So, next, since you have these biologically-defined features, you can apply some sort of evolutionary logic to it. So, perhaps now you say a woman's role is that of a gatherer and a nurturer since she has the ability to carry children and a smaller size, so perhaps less hunting ability. And then finally, you use these biological bases to make societal claims, such as that a woman's characteristics may make her suited for the home or dependent on men. And so, from here, you can see how this framework of a biological essentialist thought structure can underlie a social belief.

**Kayla Townsley**:

All right, hi everyone. After that great introduction by Carina, I'm gonna move forward. My name is Kayla. I use she/they pronouns. I'm a fifth-year PhD student at Mount Sinai, mentored by Dr. Kristen Brennand and Dr. Laura Huckins at Yale, and like Carina, a fellow in the graduate student biomedical science and Center for Anti-Racism in Practice. And that's a part of what this work is coming from, in developing this curriculum. So, I'll kind of jump off of where Carina left off with topics of just covering basically what biological essentialism is. I'm going to take you through an example.

*Essentialist Views*

So, early essentialist thought assumed that stark phenotypic differences or observable traits must mean immutable differences between two biological entities. A lot of this came from essentialist ideas that led Carl Linnaeus, ascribed as the father of modern taxonomy, to categorize organisms based on essentialist reasoning. While Linnaeus believed all humans to be of the same species, he categorized them into four varieties based on skin color and origin or geographical location, and then ascribed to them a social hierarchy and temperament. So we can see how that may continue to lead to the development of the concept of race, which we will touch on later. But overall, many biological essentialism stems from the belief that phenotypes, especially visual characteristics, encode innate and unchangeable behavior. Thus, an essentialist view would start with the assumption that phenotypically we can categorize human bodies into two typically observed subtypes, those being male and female, initially based on external genitalia and secondary sex characteristics, and later supported by the attribute of X and Y chromosomes to binary sex determinants. So, biological essentialism would declare this as a natural phenotypic and/or physical binary that must encode unique behaviors between the two categories.

These innate differences in behaviors within naturally embed themselves in social structures and hierarchies, since, for example, women have a womb and carry the child, they must naturally be caregivers, capable of more compassion and empathy, but destined to raising family and dealing with home life. This is reflected in early anthropological concepts of hunter-gatherer civilizations and the interpretation of those cultural systems in that hierarchy that reflected current gender norms. So, the belief that these assigned biological categories or taxonomies make societal gender roles innate, means that biological essentialism can then attribute behaviors and objects as either being biologically masculine or feminine based on the relationship with these gender roles.

That's an example here where we see things like colors being coded by gender, activities like what sports you do, if you like flowers, etc., etc.

When biological essentialism would then claim that because these behaviors, interests, and skills can now be assigned as masculine or feminine, physiologically male and female bodies must be inherently built for these different roles and innately different, which kind of is circular logic that goes back to support the original claim. So, any differences in behaviors, any differences in, let's say, brain recordings, brain activity, seen in adult males versus females based on this categorization, goes back to just support this initial biological essentialist claim, without diving into potential confounders or other societal and environmental influences that may lead to these differences.

*Materialist (non-essentialist) Views*

So now, I want to talk about a non-essentialist view and how we, as scientists and biologists, really address a lot of these issues. When we take a step back from the traditions of biological essentialism in science and look to the advancements we've actually made in our science due to a greater ability to explore nature on multiple levels, we find that most essentialism really doesn't carry new weight. However, instead of appreciating this, we describe deviations from human-assigned essentialist categories as abnormalities. So, from a theoretically materialist and dynamic materials viewpoint, one that takes into account the dynamics of the physical, temporal, and organic attributes of human behavior and social structure, we can better understand the dynamic interactions of these factors.

So, first, we would say that biologically or even organically, we observe diversity. This diversity is natural. Second, we observe that people assigned to one sex or another, based on a social category, are given innate roles in social structure. And history tells us that these roles have temporarily changed and are different in different physical locations. So, if we see these different roles playing out in different structures and different cultures, this can't be something that's biologically encoded. Third, we observe that the social structure has led to the relation of skills, behaviors, and objects associated or necessary and integrated in that given social role are now becoming associated with the individuals placed in that role unless associated with one sex or the other in this kind of, um, what I call the social category of sex.

So then, when we look in our science and we actually see differences, let's say, in brain activity, biology, health risk, or precedents, then we'd have to ask if these biological differences that we observe, let's say, an ability to perform a skill, like throwing a ball or other things, are actually due to innate biology, or is it the result of an interaction of these physical, temporal, and organic situations existing with those differences we observed. So, in that sense, do people who are assigned male at birth have a better throw because that is an innate ability, or is it because they were taught to catch earlier and at an earlier age, and it was more societally acceptable for them to play sports involving hand-eye coordination? There are some interesting studies that really do look into that, that we can give resources for at the end of this.

Okay, so we wanted to take a little pause here and just ask you all to reflect on what other examples of biological essentialism you can think of. So I'll just give, like, a moment, and let y'all think, or maybe you can just pause for a second.

*Gender Essentialism - Karyotypic Sex as Law*

And I'll move on to a really contemporary example, which is gender essentialism and sex essentialism and basically the idea that karyotypic sex or external sex characteristics are law. And what I mean by that is that sex essentialism claims that sex is a biological binary determined by external genitalia and X and Y chromosomes alone, and gender essentialism claims that gender roles and a gender binary is biologically determined by the sex binary, i.e., if somebody has XX chromosomes, they are female, and thus they are a woman. This is a really common misconception in science and general society today, and we can see that a lot of rights of queer and trans folks are being kind of tested because of and supported by this sex essentialist and gender essentialist viewpoint. So far there have already been hundreds of laws proposed to limit gender-affirming care across the U.S. in 2023. This is only one example of how biological essentialism reinforces discrimination and sets rules in society, which we'll discuss in more depth later.

So, these are just some examples of Trans medical care bans across the U.S., and a lot of them are kind of set up as this precedence of not allowing the harm of minors, but it is continuing to move up and seeks to ban gender-affirming care for adults as well, and essentially taking this away from the individual's choice and saying that because, you know, biology says there are two sexes and there have to be two genders, and people shouldn't be allowed to change that. And we actually know, if we really dive into the biology and what we've been able to learn with contemporary methods, is that sex is not a binary at all. It's quite a complex biological spectrum.

*Biological Essentialism: A tenet of the European (white) Patriarchy*

Okay, so those were some examples in a contemporary instance that we're seeing, but we wanted to talk about how biological essentialism is a tenet of the European white patriarchy and essentially drive into the history of biological essentialism. Now, there are a lot of other histories, and essentialist thought does exist in other cultures, but because modern science is such a product of Western European, kind of, tradition due to a lot of different reasons, mainly imperialism and colonization, we're really just going to talk about the history from this kind of European, Eurocentric viewpoint.

*How did biological essentialism come to be?*

So a lot of essentialist thought comes from what is kind of considered the first type of science, which is philosophy, and just asking how the world works and why and what is our role in that world as humans. And so, ancient philosophical thought, mostly Plato, Aristotle, and Socrates really dived into bringing an essentialist view to understanding the world around us. And so, Plato believed that all things have an essence, which are timeless and unchangeable, and that all things are essentially trying to mirror or mimic that perfect essence. Aristotle built on this idea from Plato, but kind of diverged into substance theory, basically saying that everything has something that defines it, a perfect or initial substance. For Aristotle, male is the perfect substance, and female is the accident when the substance is imperfect. So, we can see how these essentialist ideas start to create opposing categories so early on. Both of these philosophical viewpoints are inherently essentialist and went on to inform Carl Linnaeus and other early philosophers and scientists leading to the development of taxonomy and essentialist biological categories.

So, if we talk about the Medieval Era, we get kind of a stop on science. Many foundational beliefs in religion could be traced back to early essentialist philosophy. For example, in Catholicism and Christianity, which are especially popular in European history. And so if we think of this kind of substance theory, Jesus Christ was the imitation of God's perfect form, both being separate and a part of that Essence in the same way that people were viewed as imperfect and inherently flawed imitations of God and his form that should then seek to perfect themselves in life so they can return in death to a more perfect Essence. This really tracks with a lot of Plato and Aristotle's essentialist beliefs, but in European Medieval Times, religious mysticism controlled essentially all social and governmental structures, and really the only vein of permitted intellectual thought was carried out by monks and monasteries and religious officials. So, this pause on greater philosophical and scientific inquiry in Western Europe over the period of roughly a thousand years had an indelible impact on the philosophy, religion, and societal perspectives that then kind of flourished during the Renaissance and Enlightenment eras.

So, I'm just talking without going through any of my things. So an example of this with Christianity that's essentialist is the defining of two distinct sexes created by God and that individuals are immutably one or the other. There's also the upholding of a binary of good and evil and that we can categorize behaviors or traits of an individual by these actions. There's also a lot of kind of demonization of mental health and related mental health issues to being sinful or being, you know, not in favor with God.

And when we look into what happens after the Medieval Era with the Renaissance, there was a rebirth of the Classical period and a return to the essentialist views of Plato and Aristotle. There was the beginning of the Scientific Revolution, which focused on the synthesis of religion, humanity, and nature into a worldview rooted in reason. And then this led to the development of the scientific method, which then burnished the beginning of the Enlightenment era. So, we see that throughout, this essentialist thread has really been maintained, even if it's going from, you know, early ancient Greek philosophy, and people who are considered in Christianity to be pagans because they believed in Greek mythology, to Christianity, there's still a very strong essentialist thread there, and then to that being the dominant religion at the time in Europe and leading to the Renaissance and then Enlightenment. So, we see that essentialism really holds through in a lot of these areas.

So, with the Enlightenment, there were two individuals and philosophers who held somewhat opposing but still rather essentialist views, and that's Thomas Hobbes, who believed that the natural condition of human nature is to be in a war of one against all, where human nature makes us individualistic, brutish, and aggressive, and John Locke, who believed that human nature followed laws of nature in which mankind is free to order their actions and dispose of their possessions and persons as they think fit, but within the bounds of the law of nature. So these were just, kind of, two differing and opposing perspectives on how humans innately act. And you all might remember this from high school. Hobbes was the writer of "Leviathan" and the developer of the social contract theory, and his idea of a war of one against all became an influence on Darwin's understanding of "survival of the fittest". And John Locke was considered the father of democracy, because it began a loosening of the rigidity of conscriptive human behavior and social roles, because it gave people more freedom and choice.

But as I said, this idea of war of one against all that Hobbes brought was a part of what influenced Darwin's understanding of evolution and natural selection, and so in the 19th century, we have the development of Darwinian evolution and the concept of "survival of the fittest". Basically, any behaviors or traits that did not confer what was considered a reproductive advantage or survival advantage were considered as mistakes, disadvantages, unnatural, and thought to be slowly removed from a population. There is a belief that animal nature was inherently individualistic. And after Darwinian Evolution, this idea began to be involved in another essentialist viewpoint intertwined in social contracts and understanding of social contracts, which was social Darwinism, which was a kind of "survival of the fittest" meant that certain people would inherently and innately become powerful in society because they were better, and it has to be essentially that they are biologically innately more skilled or intelligent, and thus, they will rule society. And this has been used to justify imperialism, racism, eugenics, and social inequality at various times over the past century and a half and even today.

Another influence during the 19th century was August Weismann, who was a geneticist and studied germs and germ plasma and germ cells, but in this kind of reductionist, cellular model, found the importance of genetics and really claimed that genetics determine all inherited traits. And so, you're starting to see this connection of biological essentialism and "what is that essence?", "What is that essential biological thing that makes these behaviors innate, makes these people innately different?" And so, August Weismann and this understanding of DNA that's starting to flourish in the 19th century now, we can have a link to genetics, which really leads into eugenics, which we'll talk about later.

*Summary of the historical basis of Biological Essentialism*

Okay, so a quick summary of the historical basis of biological essentialism. We have this little table where we have some major players throughout, and these are just a few but in philosophy and early philosophy, there's Plato, Aristotle, religion, and essentialist views of Christianity and Catholicism, again, especially because we're talking about the culture of science which comes from Western imperialism, we're only reflecting on those religions and philosophers from that area, right?, that kind of led into the development of modern science. Socially and politically there's Hobbes, and in science, we have Weismann and Darwin, and so this is kind of a breakdown of the essentialist thoughts that came from each, and what the biological essentials principle was.

*Bio Essentialism contributes to many contemporary misconceptions in Medicine and Science*

So with that, we want to say that biological essentialism contributes to many contemporary misconceptions in medicine and science, and Carina is going to dive into some of those examples now.

**Carina Seah**:

So now that Kayla has given us an understanding of the historical basis for biological essentialism, let's go through a few of the claims that biological essentialism makes and really break down what these claims mean, and show how recent research has really proved a lot of it wrong.

So again, these are the foundational principles of biological essentialism. One of the first ones is that inequalities in status, wealth, and power in society can be explained by biological factors such as genetics. So to do this, social properties of individuals are defined and attributed to biology. These are things like intelligence, aggression, nurturing ability, or other factors that we use to rank people by, and that's what are used to rank people by the amounts of these properties that people possess.

*Why are these conclusions logical fallacies?*

So to break down why this is a misconception, we really have to get into whether genetics really does explain inequalities in human social traits. So, biological essentialism states that we can group individuals based on genetics, and apply this evolutionary hierarchy to them, which explains these fixed inequalities in status. But this really depends on the assumption that genetic variation leads to set fixed traits.

So, modern genetics has actually shown that this isn't really true. It's actually very rare that a single genetic factor would fully explain a human trait. We can actually rank genes along a degree of genetic determinism. So, a gene that is highly deterministic would always cause a trait, so if you have Gene A, you always have Trait B. As you go down the deterministic spectrum, you get to a probabilistic association of the gene with the trait, where having Gene A puts you at risk of having Trait B. And as you move down, you decrease the effect size or the role of the gene, where now, having Gene A only sometimes leads to Trait B. We actually know that this one gene associated with one trait situation is actually highly simplistic, and very rarely true. Actually, what we've seen is that one gene may be associated with many traits. Several genes or many genes may be associated with one trait, and then these genes also interact with the environment and epigenetic factors. So, these other environmental and epigenetic factors that contribute to traits may be really substantial. So, this one-trait, one-gene view is generally very oversimplified and deterministic. It means that you could easily separate people based on whether they just had that gene, or that SNP, or not, but in reality, there are so many complex factors that contribute to traits, making it really hard to nail down any one strictly genetic or even biological categorization of people.

Even the most classic Mendelian phenotypes that we learn in high school biology are more complex than we think. So, for example, this is the GWAS for eye color, and you can see that this actually comes up with many genome-wide peaks. So, you can imagine that eye color, which we originally thought of as being very deterministic and monogenic, is actually the result of a ton of proteins and pigments in the eye, and that many different genes may impact the processing and expression of these pigments and therefore impact eye color. So, because of this, a biological grouping based on eye color would be extremely reductionist.

*Biological essentialism and heritability*

This leads us to a discussion of heritability, which we wanted to bring up here because when thinking of this on a population scale, heritability is used to define why certain groups of people would share traits. Heritability is a measure of how well differences in people's genes account for differences in their traits. This is a statistical definition, right? It relies on accounting for variance, differences rather than similarities. But the way that heritability is used commonly actually implies that there's an unchangeable genetic destiny, so that if a trait is highly heritable, then if your parents have it, then you are destined to have it as well. But what does it actually mean for a trait to be heritable?

*What is Heritability?*

So, in reality, what heritability does actually measure is the differences between people; It explains how much of the variance that we see in traits is due to differences in genetics. So, instead of being a fixed immutable thing, heritability can change within a population. In fact, heritability is actually very different just based on the way that you measure it. Most importantly, heritability is also a measure of the environment; the environment you live in can also be heritable across generations. Things like inter-generational trauma are environmental, and they predispose people to something like PTSD, but that has nothing to do with the genes they were born with. So, the image on the right shows this pretty clearly where traditionally, people think of heritability as how much of the variability in the trait can be attributed to variability in genes, but also, variability in the environment impacts heritability too, so it's not just fixed within a population.

*What is heritability NOT?*

So, let's take an example, let's say height, which is a highly heritable trait with a heritability estimate of 0.8. This does not mean that height itself is passed down to the next generation. Remember, traits are not passed down through generations, because they are affected by the environment as well. So, instead, genes are what are passed down. High heritability does not mean genetic determination. All a high heritability is saying that most of the observed variation in that trait can be correlated with genetic variation. So that trait is a good predictor of the genotype, not that you can determine the trait based off of phenotype. If you see someone is tall, you are more able to guess what the genetics look like, rather than if you look at the genetics, you can say someone will be tall. Most importantly, if a trait is highly heritable, that does not mean that the differences in that trait between groups are due to genetics.

*Misconceptions regarding heritability*

So, for example, and we'll keep our height example, we can say that traditionally, white U.S. males are tall. So, in the 19th century, they were the tallest in the world. From that, we can't draw any deterministic claims like because U.S. males are taller than, for example, Dutch males, they must have different genetics. In fact, that's not true because over time, as time has increased, now Dutch males are on average taller than white U.S. males, showing that height differences between populations are likely due to environment more than genetics.

*The majority of traits involve environmental factors*

Speaking of environment, environmental factors have a massive role in determining traits. It's not really true that traits are predetermined because of the role of the environment. For example, you could have the highest genetic risk factor for alcohol use disorder but never drink alcohol and therefore not develop alcohol use disorder. So, therefore it would be really reductionist and deterministic to describe you based on your genetic risk alone. This exists for almost every trait. But I wanted to pull one from the NIEHS website, which is this MET gene, which confers risk for autism but only in individuals who have been exposed to high levels of air pollution. So, we know that these genes do have an impact but are not sufficient alone to group individuals.

So, this is a good time to pause and take a moment to think about the answer to this question: "have you thought about or have you experienced any other examples of how these biological essentialist misconceptions have permeated into public understanding in popular culture?"

*Why are these conclusions logical fallacies?*

The next assumption of biological essentialism has to do with taking different traits and interpreting them biologically and then ranking people based on how much of these traits people possess. These traits can be thought of as little buckets containing things like IQ, sexuality, aggression, nurturing ability, fertility, etc. When these traits are attributed to biology and assigned to race, they serve as a means to rank races based on how much of these traits they possess. Here is a pretty disturbing example that I'll let you read on your own of how races were ranked, as recently as 1996, based on biologically asserted characteristics.

But actually, these behaviors and traits cannot really be thought of as these set features that can be ranked, because social and biological phenomena are not actually the sum of their parts. These traits are impacted by the environment and are changed by the environment, in addition to being impacted by genetics. And the environment is different throughout development and is dependent on the presence of that trait. So because of that, there are no universal truths that apply to all organisms; they are both shaped by and continue to shape their environment.

So here's an example of that: a trait that interacts with the environment but is also changed by the environment. For example, let's take the bucket of IQ, which has long been used to rank people, especially by race, as you saw previously. So for example, someone who starts education earlier or has more after-school activities, smaller class sizes, and individualized attention---these environmental factors are largely impacted by socioeconomic status, and likely to impact the IQ perceived by society. That perceived IQ, which is lumped into being a biological factor, leads to job acquisition and higher educational attainment, ultimately resulting in higher socioeconomic status. So this is how what is considered a biological variable of IQ is actually modified by the environment but is also used to modify the environment of socioeconomic status, leading to this dynamic property in society rather than some fixed, immutable genetic trait.

**Kayla Townsley**:

The next misconception that develops from the three tenets of biological essentialism is the belief that any deviations from the norm are abnormalities, and that they reflect medical problems that must be treated or tiered. This biological essentialist belief is one much debated after the disability rights movement, and a contemporary example is the advocacy from the autistic community currently for scientists to stop searching for a cure, and to listen to community needs. We will discuss this topic in more depth in what is our fourth lecture, which really dives into ableism and science and how ableism in science is upheld by biological essentialism. But that is just one example.

This third misconception---that deviations from the norm are abnormalities---then leads to and supports this fourth misconception: that these properties must be biologically explained by anatomical localization or can be reduced into understanding of concentrations of biological substances and can be genetically or environmentally partitioned. I'll talk about what that means.

So first, why is misconception 3 a logical fallacy, and why are deviations from what is considered a norm not actual unnatural abnormalities? If we look into the history of this and what is defined as "normal" in our society, especially in Western imperialist science, we see that a norm does not actually equate to what is biologically natural. It is a societally-implemented norm, or what is considered "normal" to a given culture or society at the time. So, a history of how this has been misused to support racism is really prevalent in the book "The Bell Curve," which was published in 1996 by Richard J. Herrnstein and Charles Murray. This book tries to discuss intelligence and class structure in American life. In 1994, he wrote this book initially and explained that abnormalities and variance in intelligence were notably different between Black and White Americans. He found a difference in the distribution of IQ scores, and he warned of the consequences of low IQ, and proposed social policies toward mitigating these consequences. His recommendations for policies to mitigate these consequences because he saw what he thought was an innate biological difference in the intelligence of Black and White Americans were ableist, racist, and in line with eugenic policies, such as opposing interracial marriages, for example.

In 1996, Stephen J. Gould revised a previous book of his, "The Mismeasure of Man," which actually discusses these issues of biological essentialism and defining norms based on bell curves and added a direct counter-argument to Murray. These books and their responses to one another are interesting to read from a historical perspective, but also provide insights into the arguments made for and against biological essentialism, and specifically for and against how we determine what is "normal" in science, and usually that is with these distributions.

*Caveats of "normal" distributions*

So, there are some caveats to what we consider normal distributions, or essentially defining the mean of a population and the tail ends of that population. One thing we have to reckon with is that sample size and power make a really big difference in whether or not two populations will converge or diverge in the trait. So we have here from this example, you can look up this site, sexdifference.org, and it talks about some of these caveats of normal distributions. But if you have a sample of 45 people per group, with an 80% chance of detecting a difference, you see less overlap as you increase the number of people in that group to 175, the same amount of chance, you see more overlap. And then, if you have a really big group of over a thousand in each sample, you're seeing that overlap between those populations is 96%.

Population also matters; we have to think about how we're sampling, who we're sampling, and because a distribution is always dependent on the population you're sampling at any given time that you're sampling it. These are distributions from a study on brain volume in different brain regions in people whose sex was identified as male or female based on their chromosomes from, I believe, UK Biobank participants. So, there are some differences in these population means. But I think an important thing to understand is that there is oftentimes more overlap than not. So, taking away from this, we should not make assumptions about an individual based on population-level statistics. Where there is biological variation, there's not really any norm. The norm is diversity, the norm is biological variation, and a spectrum of traits and phenotypes. And we have to also think about who's defining that norm, how we're defining that norm, and what population was used to define that norm. Is it actually representative of the human diversity that we see? And oftentimes, it is not.

So then, moving on to the fourth misconception, which, the third misconception of biological norms leads into this belief, basically that abnormal properties can be explained by innate biology and can be solely localized to an organism's anatomy, molecular concentration of biological substances, or their genetics, or their environment alone. This is a really reductionist and essentialist viewpoint that ignores the complex dynamicism of biology with social, political, and environmental influences. And this is considered to be the fallacy of spurious localization.

Essentially, you cannot separate biology from its environment; both are in constant interaction and dynamic change. Genes do not absolutely determine a phenotype, nor does one's environment solely dictate their biology or their phenotype. Similarly, anatomical structures that are separated from the whole function differently. A great example of this is the over-exaggeration of the role that the hippocampus plays in memory, by saying that hippocampus equals memory which I think is something we've all heard and learned about um in maybe science classes or if you're kind of in the Neuroscience field. So, this is an assumption that a trait can be pinpointed to a very specific part of an organism, acting independently in function. But we know that, while the hippocampus is necessary for memory, it is not sufficient for memory. So, you cannot separate biology from the environment or context, as both are in constant interaction and dynamic change.

The faulty reasoning behind spurious localization applies in many areas of scientific inquiry and medical practice, mostly because it is often impossible to study an organism in its full dynamic complexity. Reductionism in science, especially historically, was the only way to study these systems because we were very limited. It really allowed for what we consider to be controlled experiments. Advancements in science now allow for more complex interaction studies, but even when we have to do reductionist studies, there's always going to be this element of having to take a piece out of the system and study it independently. The problem arises when we make broad conclusions about the whole with the insight of only a part. I.e., we will always have to do some kind of reductionist study; we're always maybe only looking at one piece of the overall puzzle. But we need to be careful that our conclusions aren't overestimating or emphasizing the role of one small piece of a greater system.

A very contemporary example of this, and another fallacy of spurious localization, is the serotonin imbalance hypothesis, which posits that major depressive disorder (MDD) can be explained by imbalances in serotonin concentrations in the brain alone. However, we have a lot of data showing us that MDD is a complex trait influenced by the interaction of environmental, social, political, biological, and genetic factors, and that serotonin imbalances alone do not explain MDD and they are not the cause of MDD. It is much more complex than that, and reducing it to this one thing has really only allowed big pharma to benefit from drug sales.

Another popular example of spurious localization is the idea of the battle of the brains---a belief that differences in male and female behavior and interests are encoded in the brain, and so there have to be differences in the brain. When found, it reinforces the idea that the sex binary is innate and that gender roles assigned to a sex are supported by biological ability.

So I'm gonna share something that actually comes from, I believe a medical school. Basically, this "battle of the brains", men versus women. And they start off by trying to say that, you know, male and female brains are more alike than you might expect, but there are subtle differences and what that could mean for your health. Then they share these facts and the possible health impacts, and we want to talk about how this just leans into biological essentialism. So, in real life, relaying their findings, you know, they say the male brain is 10% larger than the female brain, it has stronger front-to-back connections optimized for motor skills, and then it has these health impacts that are unclear of how they relate to these, you know, stats on the male brain. And they do the same for the female brain, but here the assumption is that these brains are inherently different and that's they've always been that way, not that any kind of environmental influences that might be different between societal roles more likely assigned to somebody of a sex, whose sex is male or sex is female, could possibly contribute to different connections in the brain, different types of thinking, etc. A really, kind of, historical example of how these localized differences were thought to explain differences in men and women was the idea that because women's brains are smaller than men's brains, and the thought was that brain size was correlated with intelligence, women were less intelligent and less likely to be in career roles and were more fit to traditional kind of housewife roles in society. We know that this isn't true; size differences between male and female brains are small and inconsistent across studies. So even this statistic of 10% larger is inconsistent based on the studies you look at and again is related to some of the caveats of our normal distribution and how we're taking the mean of a population or sampling. But we also know today that brain size does not equal intelligence, and so this is not a fair comparison or thing to make.

So, an example of spurious localization that really took over popular culture a while back was the assignment of specific cognitive and behavioral skills to either the left or right side of the brain. And so then the left brain was considered the logical, analytical brain, and the right brain was the creative and empathetic brain. And because societally-enforced gender roles place men in logical and analytical roles and women outside of education and career-focused lives, people associated sides of the brain as being gendered. So then because the left brain is more logical and analytical, it's masculine, and because the right brain is more creative and intuitive, it's feminine. So on top of having spurious localization of these complex cognitive skills to just one hemisphere or the other, we're now getting a level of biological essentialism enforcing gender rules again and enforcing sex and gender essentialism by assigning, kind of, a gender to a location of the brain that is thought to be responsible for a certain skill.

*What social implications has this had?*

So what social implications has this had? I think this is a really nice example because I just went in and I googled "male versus female brains" and this is what pops up, like, right away. So, this is very much still a misconception in society, and it's still very much, I would say, shared and believed by a lot of people. And as a misconception, something we need to start addressing. And so here's one example. It says, "If you have a male brain, you like to make lists, you prefer to read on function, you notice grammatical errors, you read maps easily. If you have a female brain, you like to chat and gossip, you like beauty, you lack interest in historical events, you lack interest in technical details of a new computer or gadget." I mean, this is very fundamentally BS. Here's another illustration that kind of shares the same idea. Basically that women's brains are different; they focus on attention, compassion, love, this even says housework, and that male brains look at, you know, ego, aggressions, analytical nature, sex, sports, all this kind of stuff. This is a film that talks about the female brain. It's kind of interesting because the protagonist is supposed to be a neuroscientist studying differences in the brain by sex, and it very much just upholds a lot of these fallacies of spurious localization and sex differences and gendering the brain in a way that is not biologically correct. And here's another example.

And then this is an example that really shows how scientific studies can be really misused in popular media to uphold societally-enforced gender roles. And so, these images at the bottom are from a study that looked at the connectivity in the brain of people who were assigned male at birth or assigned female at birth and found essentially that they saw stronger front-to-back communication in the male brains and stronger side-to-side communication in the female brains and then this seemed to be evidence enough to say things like that means the male brain is more goal-oriented, it's focused on a narrow, deep view, it's more analytical, it's more direct and decisive, goal-oriented, realistic, thick-skinned, while the female brain, because it has side-to-side connections, has a contextual view, web thinking, theoretical, intuitive, empathetic, idealistic. And then this figure goes on to then say this is a binary effect caused by testosterone and estrogen. And so, like I said, these fMRI tracing studies of activity come from a scientific paper, but they're just put on here on all of these different spurious biological essentialist views, upholding essentially sexism in society and equating it with innate biology.

*What is the scientist's and researcher's role in preventing these misconceptions?*

That was a lot to go over. And after talking about these misconceptions and giving the example of that last image where a figure from a scientific paper was used, we have to think about what is the scientist's and researcher's role in preventing these misconceptions and the misuse of their data, their figures, in the dissemination of knowledge to just like the public and, and being used in these kind of figures. So, I'll ask if you can pause here and really take some time to reflect on this question.

But I think we're going to move forward.

*But what if we do see differences in biology? WHY is it flawed if we claim these are biological?*

Okay, so after discussing these misconceptions of biological essentialism and the fact that, you know, a lot of these societal categories and roles are said to be supported by innate biology, what do we do when we actually see differences in biology? Why would it be flawed if we claim that these are purely innately biology, you know, predetermined before we even develop as an embryo?

*Biological vs. Social Essentialism*

So before getting into that, I want to talk about biological versus social essentialism, because this is a question that's come up in the past. And so sometimes the base sense of centralism begins with social observations rather than biological observations. So this is called social essentialism, and it often makes the same claims by the logical reasoning as biological essentialism. It just flows in a parallel but opposite direction. So I'll show that example of that.

Essentially, biological essentialism, we'll see what are considered to be biologically observed differences, let's say external genitalia, the color of somebody's skin, they use these to group people based on observed biology or these observed phenotypic differences, and then they say that any deviations in roles, any social hierarchy, is the direct result of these innate biological differences between groups. Where social essentialism will start with socially observed inequalities. We'll group people based on social constructs, and then seek biological explanations for those differences. Fundamentally, both really uphold racism, ableism, sexism in society, and they're very similar forms of a kind of logical progression; they just start with different initial observations. So then, I think Carina is going to take the next slides from here.

**Carina Seah**:

*Biologically-derived social hierarchies can lead to eugenics*

By building social hierarchies on the basis of certain biological factors that are assumed to be fixed and immutable, a natural progression of this logic leads to eugenics. Eugenics is the process of increasing the occurrence of heritable characteristics regarded as desirable by forced sterilization, segregation, and social exclusion. Some of the ways this has occurred in the past are things like prohibiting the marriage or forcing the sterilization of people deemed unfit to reproduce. Some of these traits that made someone considered unfit to reproduce included things like mental and physical disabilities, scores on various IQ tests, people who were deemed criminals or deviants, and even members of certain minority groups.

*How biological essentialism in science supports oppression*

And then, how does biological essentialism support this? Well, once we have these biologically assigned social traits, anything that's considered socially undesirable is thought to be able to be eliminated via these biological means. So, if we're able to biologically classify and rank traits, we can then define some that we deem "abnormal", and then we can use biology to attempt to rid these things from our population.

Some examples of this include things like the Jim Crow laws which limited the marriage and reproduction of people by race due to defining the racial social hierarchy biologically. And then sterilization is another example. Here, I'm showing you an example of a German propaganda poster that advocated for sterilization. It states here that the cost for what someone's suffering from, in quotes, a hereditary defect, would cost the community and that it's your money too. So, rather than investing in programs to reduce the impact of disability because they saw it as a biological abnormality, the policy was to rid these traits from the population.

*How is biological essentialism perpetuated in science?*

Another example is IQ. So after World War I, the US military performed IQ testing of soldiers from the U.S. and other countries, and then ranked them, as you can see here at the figure on the right. They then used certain groups' scores as a reason to restrict their immigration to the U.S. in the Immigration Restriction Act of 1924. As we know, IQ is largely modified by the environment, but seeing IQ as purely a genetically-defined and fixed trait, this leads to the societal consequence of seeing IQ as a so-called "natural" limitation that could not be changed. And if this is the case, then it's thought to be unnecessary to provide education or social programs, as these are thought to be wasted on people with theoretically lower IQs.

**Kayla Townsley**:

All right, so Carina gave us kind of a definition of eugenics and a breakdown of some of the historical policies that have resulted from eugenic beliefs, that really upheld not only oppression, but violence and genocide. But now we want to talk about how eugenics plays a role in science today, and what the history of especially psychiatric genetics truly is. And so we talked a bit about Darwinian evolution having some essentialist claims in the 1850's, moving into Social Darwinism in the 1870's. And with the, kind of, discovery of genetics and the attribution of genetics with dictating every trait, we get the rise of eugenics in the 1900's.

So Ernst Rdin was considered the father of Psychiatry, and he lived from 1874 to 1952. He was a Swiss-born German psychiatrist, geneticist, eugenecist, and known Nazi. He was a pupil of Emile Kraepelin, who assumed the directorship of the Max Planck Institute of Psychiatry in Munich in 1931. He served on the task force of hereditary experts with Henirich Himmler, developing the German sterilization law of 1933, which, as Carina mentioned before, was mirrored off of eugenic policies and sterilization policies that already predated Nazi Germany and existed in the U.S.. Rdin officially joined the Nazi party in 1937. He assisted in policy killing or sterilizing 73 to 100% of patients diagnosed with schizophrenia, as well as their relatives, in Germany, which came out to be about 200,000 -to 300,000 people. He was honored by Hitler with medals, awards as the pioneer of racial hygienic measures of the Third Reich.

Another person considered to be a founder of Psychiatry was Franz Kallmann, and he developed the use of twin studies in the assessment of the relative roles of heredity and the environment. He was a student of Ernst Rdin, and a fierce advocate of eugenic sterilization of people with schizophrenia and their relatives as well. He was a member of the American eugenics movement during the first half of the 1900's. He was a founder of the American Society for Human Genetics, and he falsified evidence and had contaminated diagnoses and twin studies of schizophrenia to support an 80% heritability. Today this heritability estimate holds in twin studies, but not in large-scale GWAS studies, and we see a huge discrepancy in the heritability estimates from twin studies versus population-based studies. And it raises important questions about the limitations and nuances of twin studies and whether a twin study is really so devoid of environment, because the idea is that a twin study gets at exactly this "nature versus nurture". But there are a lot of studies suggesting that environment can be more similar between even adopted families, and the ways twins are raised and act, and there's some really interesting papers that discuss these limitations, these nuances, that we will share as resources at the end of this. Kallmann is still cited in textbooks and research papers today, despite having falsified evidence and being a known eugenecist. And there's a discussion of this in a paper from Kendler and Klee from 2022.

Another eugenicist who was a psychologist and geneticist was Cyril Burt. He lived from 1883 to 1971. He argued for high heritability of IQ and used this to uphold classism and racism. Burt propagated a hereditarian position where genetics plays the key role in individual development. He maintained that intelligence is a stagnant or predetermined trait, and believed that if a child or adult has a low IQ, it would be a waste to educate them or provide further opportunities that would elevate their social position because they were innately unable to go beyond their predetermined IQ. He also falsified data to support the heritability of IQ as 80%; this is known as the "Burt affair." He also performed twin studies on the heritability of intelligence between the end of World War II, after, kind of, the end of the Third Reich in Nazi Germany, up until the 1950s and 60s, which saw the rise of social essentialism, which I briefly went over. Most of his data from after World War II were found to be unreliable or fraudulent.

**Carina Seah**:

*What is a modern example of biological essentialism?*

We have provided you with many historical examples of how biological essentialism has led to eugenics and harm. We also wanted to touch on a more concrete modern-day example, which is the serotonin hypothesis.

Serotonin is very much an important mediator for major depression. SSRIs (Selective Serotonin Reuptake Inhibitors) are extremely effective and important medications to manage depression. However, if we define depression solely on the basis of serotonin imbalances in the brain, we lose focus on many of the other societal mediators of depression, such as things like financial strain, food insecurity, employment status, adverse childhood events, migrant status, working conditions, social support, and education. In fact, by addressing many of these aspects, these are just as important factors to address as some of the biological factors of depression. And so, if we wanted to mitigate the biological essentialism here, what we do is shift focus from the individual's biology to focus on the systems that create that biology to begin with.

*How do we do better? Best Practices in Research*

Now that we've shown that biological essentialism is tied to many real-world harms, what are some of the ways that we can modify the way that we teach, learn, and practice research to avoid using biological essentialist logic?

1.  *Change our language*

The first major practice we can change is our language. With regards to something like sex and gender essentialism, the major essentialist fallacy is the biological enforcement of a socially constructed gender and sex binary. So, rather than using language that continues to enforce that binary, it's important to expand our language and increase the inclusivity of our words to acknowledge this diverse biological and societal spectrum that underlines sex, gender, and sexuality. An example of this is just using the word "people" instead of "men" and "women," which expands to include people who are intersex or non-binary.

Another important consideration is when to use the word "normal." "Normal" implies some sort of homogeneous reference standard and pathologizes any variation from it. So, there's almost always a more specific word that can be used instead. Even when you're examining a patient, words like "this looks healthy" can be more inclusive of natural variation than "this looks normal."

*Be explicit and clearly state limitations*

So, overall, being very specific in your language is a major key. If you are researching sex differences, are you researching karyotypic, hormonal, or morphological differences? We all know that all three of these things exist on a spectrum and they don't necessarily correspond with each other. So, it may be necessary to be more explicit and more specific when you're outlining this variable in your studies. If you're researching race, be very careful to specify what social, political aspects of race you are studying and quantifying. If you're studying ancestry, be very specific in the locality of that ancestry. In the medical sphere, it's really important to avoid attributing race and gender as a causal explanation for observed discrepancies in disease or disorder incidents. Where possible, it's really important to shift your language to acknowledge the historical context and focus more on the social determinants as causal factors for these disparities. When we're talking about medical conditions that have known ancestry components, it's important to be explicit in distinguishing race from ancestry and then being explicit about the known variants that are different by ancestry when discussing causes.

**Kayla Townsley:**

2.  *Re-structure our experimental models/designs*

Alright, so another best practice for addressing biological essentialism in contemporary science is learning to restructure our experimental models and designs. Many of our experimental designs are fundamentally essentialist because of the history of essentialism in science and also because of this need to be slightly reductivist in our experimental design or to control for the perfect experiment. So often, if the essentialist model, especially in this case, this is an example of essentialism in sex and gender research, you're looking at the individual level and then across a lifetime in years, and you say the differences between these chromosomes (XX, XY) - you do this experiment on individuals in their adulthood - you see differences and significant differences, let's say in brain activity in a specific region of the brain, and then you say those are results. You take a snapshot, you publish those. And what happens here is the claim that you're seeing those differences is related to these sex chromosomes.

When we take a step back and look at how we can incorporate social context, environment, really all of these dynamic things that interact with a person throughout their lifetime, we can see how we can't just say that those results are related to these chromosomes. Because there are gendered models of learning, gendered types of cognitive domains, there's gendered reinforcement, gendered activities, gendered socialization, gender stereotype threats, sample selection, sample size, technical elements, statistics, the hypotheses you start with - all of this stuff needs to be thought about before you submit those results, before you say, "This is what we found." So, this is considered to be a model that's informed by gender scholarship, and you can look this model up (The link's at the bottom), but we'll include it in our resources as well.

Another thing that kind of is a part of this restructuring of experimental models and designs is the fact that our typical experimental process and the way that science publishing focuses on positive results leads to a level of confirmation bias in the field. And so, this is again focusing on sex and gender research. When we have our experiment, we show results that have a significant difference, and we just publish those results. If we do an experiment and we see similarities between sex and gender and no significant results, we consider that a null or lost experiment. So, we redesign it in order to find differences to publish; we found differences, and what happens is all of these results that show that there are all these similarities aren't what are being published, aren't what are being disseminated to the public. So, there's a confirmation bias of saying all of the scientific research is reporting significant differences by gender or by sex, and therefore, these must be innate biological differences; there must be really, really big differences. This is a way that the scientific and experimental process that currently exists allows for a lot of confirmation bias to be perpetuated.

So a recommended experimental process would be to test the sensitivity of our results. Test if we used a large enough sample size, how do we sample that population? Are we considering all the potential social contexts that might actually explain the results we're seeing instead of just ascribing them to what's easy, which is sex assigned at birth? And if we have results that show sex and gender similarities, we should learn how to publish these results as well. To publish all of the results, to describe the distributions as well as the means, to really talk about the nuances as well as the variation. Because when you just report means that are significantly different, the narrative that comes off of that is that there is a notable significant difference between all individuals who fall into one category or the other. When again, if we go back to our understanding of biological variation and distributions, there's oftentimes way more overlap between individuals than not, and we can't use these population-based means to make base assumptions about any individual person that is a part of any social category.

3.  *Incorporate community participation in study design and dissemination*

Another way to address issues with biological essentialism in our research is to incorporate community participation in study design and dissemination, and really in every single part of the scientific process. So this can be learning, educating yourself, seeking feedback, involving the community, including scientists who are part of those communities, and creating mechanisms for individuals, communities, organizations, and researchers to provide feedback on the research being done while it's being done, and then at the end, to support the researchers, to support the communities that have been a part of this process, to credit them, to hire individuals who are part of these communities to be consultants or to be the researchers, or technicians, or liaisons of the community, and to really think about how you can incorporate these roles into the grants and the funds you're asking for so that you can also provide pay for the communities and for the contribution to your science.

With this idea of community involvement, I think a really big discussion around this is happening in psychiatric genetics because of the advocacy from the autistic community and the kind of pausing of the high-profile GWAS that was coming out because of backlash from the community. So, I wanted to give a couple of resources for places to do that first step of learning and learning from researchers who have autism, from the autistic community themselves, and from studies that are structured to be co-led by communities.

A great resource is the Autism and Adulthood scientific journal, and the Editor-in-Chief, Christina Nicolaidis, is a part of the NIH Aspire initiative, which really works to help teach other researchers and scientists how to lead these community participatory research studies, specifically with the autistic community. And then at the bottom, there's this NeuroClastic; this is basically the autistic spectrum according to autistic people, so everyone contributes to this as a part of the autistic community, and they have a lot of opinion pieces, as well as scientific pieces, and other kinds of reporting on multiple issues that the autism community faces in society today. And I think it's a really great platform for some self-teaching and learning.

Another example that is a pre-print out that does some of this community participatory study on ancestry, is this genetic environmental contributions to ancestry differences in gene expression in the human brain. And you can see how these authors were, you know, citing and really acknowledging all the people who are critical to the work. If you look into their methods, and then also this acknowledgment, you see that they sought feedback and input from multiple black scientists in the field, as well as select leaders of Black in Neuro, as well as the African Ancestry Neuroscience Research Initiative, and historically kind of more black universities, as well as members of the community in, I believe, Baltimore. So we see that there are multiple ways that you can incorporate community feedback, especially when you're doing something that looks at, in this case, ancestry, but also in the understanding of ancestral genetics and a racial group, and how to make sure that you're not falling into biological essentialism where you're equating one's race with their ancestry. Because that is not true, and ancestry is a very poor proxy for race, and race is an extremely poor proxy for ancestry. There's a lot of recent studies really diving into that, and it is the really main topic of the next lecture that dives into racial essentialism.

4.  *Hire scientists that represent real human diversity & create a safe environment for them to thrive!*

Okay, so another way, which is kind of brought up before, is to hire scientists that represent real human diversity and create a safe environment for them to thrive. So we've really leaned on this thread of sex essentialism, gender essentialism, throughout the lecture today as one of the main examples that we can hit on related to biological essentialism. This is a research for doing science in the best way for retaining LGBTQ scientists. There's this whole Talent Report with recommendations; it's really insightful, and I think a lot of the recommendations that they give can be applied to any other kind, not any other, but other communities, and really how we can do better in science and medicine to combat biological essentialism and to work to deconstruct the systems in place that uphold racism, and sexism, and ableism, and transphobia, and really do science that is for the people and by the people.

This is another example actually from the NSF survey, talking about the number of grad students and their level of enrollment by race and ethnicity. With grad students, we see that this is overwhelmingly white, especially in the doctoral phase. These are occupations that the workforce by sex, ethnicity, race, and disability status, in STEM and non-STEM occupations, and you see kind of differences here by race, gender, and ability. And then even within that, we see that there are differences in the salaries, the median wages paid, and so there are multiple levels of inequality here that we need to work to address by making the field of science more representative of the world around us and the population that exists in this world. And not only by increasing the numbers of those individuals in science, but to make sure that they are allowed to have the same opportunities: the same salary, the same opportunities for raises, for promotions, for being in leadership roles, for being deans, for having their own lab. We can't just keep hiring people at low-level positions, not paying them enough, and saying, "Look how diverse people are." We need to do better.

Okay, so then there are some other examples. This is from a paper that focuses on mental health for the LGBT community, and recommendations for research design, analysis, and interpretation, and we'll include links to these references at the bottom of the page.

So with that, I think that is the end of our lecture for today, and I just want to say thank you all for sticking with us. It's a lot of information to cover. This has been an introduction on biological essentialism, and we have a lot more material diving into very specific aspects of how biological essentialism upholds racial essentialism, diving back into sex and gender essentialism, diving into ableism, and especially ableism in psychiatric genetics. That is all to come, and we really like to emphasize the intersections of all of these 'isms' that many people have multiple dimensions of both privilege and oppression. People don't usually just exist facing one thing; they're usually experiencing multiple forms of oppression at the same time. There is an intersection between all of these and an underlying cord that upholds it, and that is this foundation of biological essentialist beliefs and reasoning, and that being very prevalent in science and medicine. We, as scientists, have a responsibility to unlearn this and to do our best to make sure that our science isn't falling into these essentialist claims and ends up being used to uphold systems of oppression. So thank you all.
