---
title: "Capítulo 1.4: Genética Psiquiátrica"
---

# ***Arquitetura Genética Compartilhada*** {#sec-shared}

**Título**: Arquitetura genética compartilhada entre transtornos psiquiátricos

**Apresentador**: Andrew Grotzinger, PhD (Institute for Behavioral Genetics, University of Colorado Boulder)

Olá a todos, meu nome é Andrew Grotzinger e falaremos hoje sobre a arquitetura genética compartilhada entre transtornos psiquiátricos. Vou dividir minha palestra em cinco seções, começando com o problema da comorbidade de forma mais geral e como os estudos familiares têm sido usados ​​para entender a comorbidade, e depois passarei a falar sobre como os métodos genômicos têm sido usados ​​mais recentemente para entender a comorbidade: começando com a análise ao nível do genoma, seguida pelo nível da variante genética e terminando com estudos mecanicistas. Em seguida, encerraremos falando sobre os próximos passos nos esforços do Cross-Disorder.

Então, começando pelo problema da comorbidade e pelos estudos familiares: começo aqui mostrando todos os indivíduos com transtornos mentais neste espaço azul. Entre esse grupo de pessoas, cerca de dois terços atenderão aos critérios para um segundo transtorno durante a vida, 51% atenderão aos critérios para um terceiro transtorno e 41% atenderão aos critérios para um quarto transtorno, indicando alguns caminhos compartilhados bastante amplos entre esses transtornos.

Estudos probando ou estudos familiares, que são frequentemente retratados usando este esquema aqui, com os pais no topo e os filhos na parte inferior, identificaram relações recíprocas em uma série de transtornos. E por relacionamentos recíprocos, quero dizer que a prole corre risco não apenas pelo transtorno presente no pai, mas também por esse transtorno alternativo. Essas relações foram identificadas para transtorno bipolar e esquizofrenia, transtorno bipolar e depressão maior, autismo e transtorno bipolar e esquizofrenia, e uma responsabilidade geral compartilhada entre transtornos de ansiedade maiores. Indicando que esses transtornos em geral não se reproduzem de forma verdadeira.

Neste estudo de 2012, eles analisaram esses cinco transtornos nos pais no eixo x e o odds ratio de a criança desenvolver um transtorno específico no eixo y, com o nulo em 1 nesta linha tracejada vermelha. O que eles consideram consistente com esses estudos probando é que as crianças corriam realmente o risco de ter qualquer transtorno, e não apenas o transtorno presente nos pais.

Estudos com gêmeos têm sido usados ​​para acompanhar essas descobertas, observando correlações genéticas específicas entre transtornos, o que é mostrado aqui na metade inferior desta matriz deste artigo de revisão de 2019.

Uma coisa para a qual quero chamar sua atenção é que muitas dessas células estão listadas como NA, e isso ocorre porque, para um estudo com gêmeos estimar as correlações genéticas entre esses transtornos, ambos os transtornos teriam que estar presentes em um dos gêmeos. Como muitos desses transtornos são realmente muito raros, ou mesmo mutuamente exclusivos, isso muitas vezes não é possível. Considerando que, para métodos genômicos (em azul aqui acima da diagonal), você verá que as correlações genéticas são estimadas em todo o espaço psiquiátrico e isso é possível porque o uso de métodos genômicos, como a regressão bivariada do escore de LD, introduzido neste artigo da Nature Genetics em 2015 , somos capazes de estimar correlações genéticas entre amostras com vários graus de sobreposição de amostras, incluindo amostras mutuamente exclusivas, de modo que as próprias amostras possam ser independentes. Agora você pode observar as correlações genéticas para esses transtornos mais raros que provavelmente não serão medidos na mesma amostra.

Dadas as altas taxas de correlações genéticas entre os transtornos, isso nos motivou a desenvolver a modelagem de equações estruturais genômicas, que introduzimos neste artigo da Nature Human Behaviour, que é uma estrutura para modelar os padrões de associações genéticas em diferentes conjuntos de características.

Quero passar agora pelas diferentes iterações de modelagem de fatores que fizemos usando SEM genômico para transtornos psiquiátricos. Começando com esse modelo de fator inicial, encaixamos naquele artigo da Nature Human Behaviour para esses cinco transtornos principais, onde identificamos esse fator p abrangente.

Chamamos isso de p em parte apenas porque era um “placeholder”, visto que tínhamos apenas esses cinco transtornos que tinham capacidade suficiente para serem incluídos no modelo na época, o que é algo que queríamos melhorar em iterações futuras, que pudemos fazemos neste artigo da Cell de 2019 para o segundo grande esforço do Cross-Disorder, onde examinamos a arquitetura multivariada desses oito transtornos para identificar um fator compulsivo, um fator de transtorno psicótico e um fator do neurodesenvolvimento.

Atualizamos esse modelo ainda mais para incluir esses três transtornos adicionais mostrados em vermelho para esta preprint do medRxiv em 2020. Com a inclusão desses três transtornos, estamos agora tendo esse quarto fator de transtornos internalizantes, que mapeia muito bem a grande parte do trabalho de modelagem de fatores fenotípicos que tem sido feito para transtornos psiquiátricos. Eu destacaria também que, para muitos desses transtornos, atualizamos os tamanhos das amostras, mas ainda estamos retirando os mesmos fatores psicóticos compulsivos e de neurodesenvolvimento do artigo da Cell.

Há algumas advertências a serem lembradas ao interpretar as correlações genéticas entre os modelos de fatores correspondentes. Uma delas é que as correlações genéticas só serão equivalentes entre métodos genômicos e familiares quando as correlações genéticas forem constantes entre variantes raras e comuns, e isso ocorre porque a regressão do escore LD é estimada usando alelos relativamente comuns com uma frequência alélica menor superior a 1%. Portanto, se esse agrupamento realmente mudar na extremidade de variante rara do espectro, o que é certamente possível, então isso é algo que também mudará esses modelos de fatores, e é algo que ainda precisa ser examinado em trabalhos futuros.

Também é importante ter em mente que as correlações genéticas podem ser tendenciosas para cima em dois casos principais. A primeira é quando os estudos GWAS utilizam controles supernormais, que se refere a casos em que os controles não são simplesmente triados para o transtorno de interesse, mas também para transtornos relacionados, o que irá induzir uma dependência entre esse transtorno de triagem ao estimar correlações genéticas.

Eles também serão tendenciosos para cima quando houver classificação incorreta, ou seja, quando um transtorno relacionado for acidentalmente classificado como o transtorno de interesse, o que também induzirá uma correlação de polarização ascendente, embora as simulações indiquem que seriam necessárias taxas extremamente altas de classificação incorreta para explicar o padrão atual de descobertas.

Então, em geral, acho que, dados esses dois pontos, deveríamos tratar as correlações genéticas como uma espécie de limite superior do que provavelmente está presente na população, mas é algo que é realmente uma limitação interpretativa, não algo que deveria nos levar a abandonar completamente os resultados. nível da variante genética

Quero falar agora sobre análises no nível de variantes genéticas em relação ao GWAS e aos esforços de Cross-Disorder, começando com o primeiro artigo do Cross-Disorder em 2013, onde examinaram cinco transtornos principais em mais de 33.000 casos e 27.000 controles para identificar quatro hits. Que é expandido rapidamente no artigo da Cell de 2019 para agora incluir oito transtornos e mais de 230 mil casos, e quase meio milhão de controles para identificar agora mais de 109 loci pleiotrópicos.

Usando uma meta-análise de efeitos fixos no SEM genômico, também examinamos loci pleiotrópicos nos 11 transtornos e identificamos 184 loci pleiotrópicos, incluindo 69 dos 109 loci do CDG2 (Cross-Disorder, 2019), o que aponta para a replicabilidade desses achados.

Neste gráfico de Manhattan estou mostrando sucessos tanto com triângulos pretos quanto vermelhos. onde os triângulos pretos refletem hits que estavam em LD com os hits univariados, e os triângulos vermelhos indicam novos loci em relação ao GWAS univariado. O que destaca a capacidade dos esforços do Cross-Disorder não apenas para desvendar as variantes genéticas subjacentes à comorbidade, mas também para alavancar o poder compartilhado entre as características para identificar novos resultados e novas descobertas.

Também analisamos GWAS multivariados no contexto de SNPs agindo sobre esses fatores: onde na metade superior desses gráficos de Miami temos os efeitos do SNP sobre o fator, e na metade inferior o que chamamos de SEM genômico qSNP, que indexa a heterogeneidade entre os indicadores que carregam esse fator. Portanto, o qSNP realmente identifica efeitos específicos do transtorno, portanto, para esses resultados, encontramos 132 hits em LD com hits individuais, 20 novos loci e 9 hits altamente específicos do transtorno, o que novamente aponta para outro benefício dos esforços do Cross-Disorder que é identificar não apenas loci pleotrópicos, mas loci que também estão subjacentes à divergência fenotípica ou fazem com que os transtornos pareçam realmente diferentes conforme se apresentam.

Quero abordar brevemente os diferentes tipos de pleiotropia que devemos considerar ao pensar sobre o que esses hits de cross-disorder estão captando. A primeira é a pleiotropia horizontal ou verdadeira, caso em que uma única variante genética ou gene afeta dois transtornos. A segunda é a pleiotropia vertical ou mediada, na qual um gene afeta um transtorno, e então esse transtorno passa a afetar um segundo transtorno, portanto faz parte desse tipo de cascata causal.

Embora as taxas gerais de pleiotropia horizontal e vertical ainda precisem ser testadas nos transtornos psiquiátricos, em geral descobrimos que, para os traços humanos complexos, tende a haver uma mistura de ambos, o que provavelmente também se aplica ao espaço psiquiátrico.

Uma maneira de examinar a pleiotropia vertical é usar a randomização mendeliana, algo que também fizemos com aquele artigo sobre 11 transtornos, onde usamos oito instrumentos, oito SNPs como instrumentos para transtorno por uso de álcool, para examinar essa cascata causal de pleiotropia vertical e, de fato, encontrar efeitos causais do transtorno por uso de álcool na depressão maior e transtorno bipolar neste modelo usando esses oito SNPs como instrumentos.

Um terceiro tipo de pleiotropia é a pleiotropia espúria, que frequentemente ocorrerá quando houver erros de classificação diagnóstica, o que é altamente relevante para transtornos psiquiátricos, dadas taxas como 15% de erros de classificação no transtorno bipolar e na esquizofrenia. Mas quero destacar que pode não ser claro o que significa classificação incorreta, dadas as taxas realmente altas de sobreposição genética. Portanto, se considerarmos esta distribuição teórica do risco genético do transtorno bipolar em vermelho e do risco de esquizofrenia em azul, não está claro qual seria o diagnóstico correto para alguém aqui no meio em roxo. Acho que isso é algo que podemos começar a superar em termos de como pensamos sobre esse problema usando dados de nível de sintoma, que abordarei no final.

Mas antes disso quero falar sobre estudos mecanicistas, ou o que muitas vezes é chamado de estudos funcionais, que em geral procuram pegar essas centenas de variantes genéticas que estamos começando a descompactar e começar a entender o quadro biológico que está sendo pintado pela agregação dessas variantes genéticas em diferentes categorias funcionais, como quando ou onde os genes são expressos.

Nesse artigo do Cross-Disorder, eles apresentam uma série de descobertas interessantes, incluindo o resultado do GTEx de que os loci pleiotrópicos são geralmente enriquecidos no cérebro, mostrado aqui em azul. Usando padrões de expressão genética temporal espacial, eles descobriram que os loci pleiotrópicos (nesta linha azul escura) são geralmente enriquecidos durante o segundo trimestre pré-natal aqui.

Usando análises específicas de tipo de célula, eles descobriram que os loci pleiotrópicos são geralmente enriquecidos em neurônios, mas não são tão enriquecidos em microglia como indicado por este sombreado azul.

Nesse artigo sobre 11 transtornos, usamos esse novo método de SEM genômico estratificado que pode ser usado para examinar o enriquecimento multivariado para examinar o enriquecimento no nível dos fatores psiquiátricos de que falei. Descobrimos que para o fator de transtornos psicóticos, esse fator é enriquecido em genes excitatórios, genes GABAérgicos, genes intolerantes à variante truncadoras de proteínas aqui no meio e, em particular, é enriquecido na sua intersecção, o que realmente dá alguma compreensão dos processos compartilhados para os indicadores dos fatores de transtornos psicóticos (nomeadamente transtorno bipolar e esquizofrenia). E também gostaria de destacar que, em linha com as duas descobertas do Cross-Disorder, não encontramos enriquecimento nessas categorias de células gliais em nenhum dos fatores.

Portanto, termino agora falando sobre os próximos passos importantes para os esforços do Cross-Disorder. Uma das principais é a consideração de fenótipos mais sutis, o que pode ajudar a classificar alguns desses fenótipos mais mistos de que falei no caso do transtorno bipolar e da esquizofrenia, e as análises de escore poligênico de risco realmente apontam por que isso pode ser importante. Assim, por exemplo, os escores poligênicos de risco da esquizofrenia mostraram uma associação mais forte para o transtorno bipolar caracterizada por psicose incongruente com o humor em comparação com o transtorno bipolar sem psicose e com idade mais precoce de início bipolar, o que indica que certas fenótipos podem estar mais estreitamente ligadas no nível genético em todos os transtornos.

Existem diferentes métodos, como o BUHMBOX, que podem ser usados ​​em conjunto com dados genotípicos brutos para detectar se certos subgrupos dentro de um transtorno estão conduzindo correlações genéticas com outros transtornos e, embora as descobertas iniciais não tenham encontrado evidências para esses subgrupos de transtorno depressivo maior, isso em grande parte ainda precisa ser testado para outros transtornos.

Os registros eletrônicos de saúde serão um recurso incrível no futuro, que nos dará acesso a alguns desses dados de nível de sintomas que, com vários consórcios diferentes já em andamento com esse propósito explícito, incluindo eMERGE, PsycheMERGE e o programa NIH All of Us.

Outra consideração importante para futuros esforços genômicos do Cross-Disorder é a inclusão do ambiente, nomeadamente porque o padrão de sobreposição entre transtornos pode mudar em certos contextos, e ao dividir os GWAS em diferentes ambientes ou diferentes coortes, podemos examinar a estabilidade dessas correlações genéticas e se certas correlações são ou não realmente específicas do ambiente.

Um ambiente específico que considero relevante é a idade de início desse transtorno em relação ao ambiente biológico interno que pode estar ocorrendo naquele momento. Então, se considerarmos essas distribuições de idade de início da esquizofrenia (topo) e depressão maior (embaixo), você poderá ver esses dois tipos de picos mais tarde na vida, o que pode realmente indicar que há um tipo realmente específico de biologia que está sendo ativado para genes expressos mais tarde na vida, e se dividirmos o GWAS para esses dois transtornos nessa faixa etária específica de final dos 40 anos, poderemos descobrir que há um agrupamento realmente único entre os transtornos nessa faixa etária.

Assim, em geral, embora os nossos transtornos possam parecer diferentes em alguns aspectos, o que nos levou a agrupá-los nestas categorias distintas, a sua co-ocorrência em níveis muito mais elevados do que o acaso exige realmente que compreendamos as causas subjacentes desta sobreposição.

Eu diria que a genômica oferece uma oportunidade real para preencher algumas lacunas importantes na nossa compreensão desta sobreposição, em parte porque podemos examinar todo o espaço psiquiátrico utilizando diferentes métodos que nos permitem examinar a sobreposição de amostras muitas vezes independentes, e também nos permite examinar esse convergente em vários níveis de análise, inclusive na análise mecanicista do genoma e no nível do SNP. E com isso vou apenas agradecer a todos pelo seu tempo.

------------------------------------------------------------------------

# ***Transtorno por Uso de Substâncias*** {#sec-sud}

**Título**: A genética dos transtornos por uso de substâncias: uma revisão

**Apresentadores**: Joseph Deak, PhD (Department of Psychiatry, Yale University School of Medicine); Emma Johnson, PhD (Department of Psychiatry, Washington University in St. Louis School of Medicine)

**Joseph Deak:**

Tudo bem, então vamos em frente e começar. Hoje Emma e eu revisaremos alguns progressos recentes na genética dos transtornos por uso de substâncias e muito do que falaremos hoje é baseado em um artigo de revisão recente que escrevemos.

Tudo bem, então a palestra de hoje cobrirá amplamente o que são os transtornos por uso de substâncias e como os definimos, a epidemiologia e a epidemiologia genética dos transtornos por uso de substâncias, o progresso recente nos estudos de associação genômica em larga escala dos transtornos por uso de substâncias e as conclusões e próximos passos.

Então, o que são transtornos por uso de substâncias? Os transtornos por uso de substâncias são transtornos psiquiátricos que frequentemente ocorrem simultaneamente com muitas outras condições de saúde mental. Estes podem ser avaliados quando vemos uma variedade de classes de substâncias, incluindo substâncias que são frequentemente descritas como substâncias lícitas, como o álcool e a nicotina, bem como substâncias ilícitas, como a cannabis, os opioides e a cocaína. O uso proeminente de substâncias pode resultar em uma variedade de consequências negativas, incluindo a morte como resultado do consumo da própria substância ou o que chamamos de overdose, bem como consequências indiretas, como estar envolvido em um acidente de trânsito ou ter problemas de saúde e doenças como resultado do uso prolongado. Como falaremos mais aqui em breve, alguns desses distúrbios são influenciados por fatores genéticos e ambientais.

Então, no slide anterior, mencionamos alguns problemas adversos à saúde relacionados ao uso de substâncias. Aqui está um exemplo rápido de como isso pode parecer para uma categoria de substância, sendo aqui o uso de álcool. Portanto, estes são números do Relatório Global sobre Álcool e Saúde, divulgado em 2018, que relatou cerca de 5,3% de todas as mortes em todo o mundo são atribuíveis de alguma forma ao consumo de álcool. O gráfico abaixo divide esses dois milhões de mortes em diferentes causas, onde podemos ver que quase 21% das mortes são resultado de lesões relacionadas ao álcool e aproximadamente 40% devido a doenças digestivas, doenças cardiovasculares e diabetes. E assim, podemos ver que o uso e abuso de álcool tem um grande impacto na população mundial de várias maneiras.

E assim, passando das consequências negativas para a forma como definimos os transtornos por uso de substâncias. Portanto, os transtornos por uso de substâncias são definidos pelo DSM-V como a presença de pelo menos 2 dos 11 critérios dentro de um período de 12 meses, com a gravidade do transtorno indexada pelo número de critérios endossados: 2 a 3 para leve, 4 a 5 moderado e 6 ou mais para grave. Em termos gerais, os critérios de transtorno por uso de substâncias correspondem à presença de diferentes problemas relacionados a substâncias e podem ser avaliados em relações com várias classes de substâncias, incluindo álcool, nicotina, cannabis, opioides e cocaína.

E assim, como mencionei alguns slides atrás, os transtornos por uso de substâncias podem ser influenciados por fatores genéticos e ambientais, e essas influências são dinâmicas na medida em que interagem, aumentando ou diminuindo o risco de desenvolver o transtorno por uso. E estes fatores podem influenciar todas as fases do desenvolvimento do transtorno por uso de substâncias. Por exemplo, fatores ambientais, tais como influências dos pares, ambiente familiar, nível socioeconômico, acontecimentos de vida estressantes e condições de saúde concomitantes, também podem aumentar os fatores de risco ambientais, enquanto redes positivas de pares, ambientes familiares de apoio e maiores vantagens socioeconômicas todos podem ser protetores contra o desenvolvimento de transtornos. Da mesma forma, as influências genéticas também podem contribuir para um risco elevado, bem como servir como um papel protetor. Também é importante observar que os transtornos por uso de substâncias são de natureza altamente poligênica, o que significa que nenhum gene é necessariamente suficiente para resultar no desenvolvimento por si só.

E então, como podemos estudar a genética dos transtornos por uso de substâncias? Os primeiros esforços concentraram-se em estudos de gêmeos e famílias que demonstraram estimativas de herdabilidade terríveis que afirmam que as influências genéticas são responsáveis ​​por aproximadamente 50% do risco de desenvolver um transtorno por uso de substâncias e que, além das influências específicas da substância, também existem fatores hereditários que contribuem aos transtornos por uso de substâncias de forma mais ampla. Nos estudos de genética molecular, estudamos pontos específicos de variação, ou os chamados polimorfismos. Os avanços nos estudos de associação genômica em larga escala permitiram-nos percorrer todo o genoma para observar as medições destes pontos específicos de variação e ver se estes estão relacionados com uma característica de interesse, sendo a nossa situação os transtornos por uso de substâncias. Agora, esta história emergiu do que foi encontrado nos primeiros estudos com gêmeos e famílias, onde parecia haver certas variantes específicas de substâncias que emergem em estudos de transtornos por uso de substâncias, bem como variantes pleiotropicas que influenciam a suscetibilidade a muitos traços psiquiátricos.

Tudo bem, agora falaremos um pouco sobre alguns progressos que foram feitos em relação aos transtornos por uso de substâncias. Falarei sobre álcool e nicotina e, em seguida, Emma orientará você em alguns outros estudos adicionais.

Portanto, a dependência do álcool e o transtorno por uso de álcool são um ótimo exemplo para demonstrar o progresso que fizemos nos últimos anos. Portanto, este número é de um dos nossos primeiros estudos fortes sobre a dependência do álcool. E então, para melhor orientá-lo, isso é chamado de gráfico de Manhattan, e veremos uma série deles nos próximos slides. Então aqui no eixo x temos a posição dos cromossomos nos 22 cromossomos autossômicos e no eixo y temos negativo do log10 do valor p. Então, esses pontos de dados plotados correspondem a associações de variantes individuais com a característica na qual estamos interessados. Basicamente, o que estou pensando aqui é que valores p menores corresponderão a esses pontos mais altos no gráfico. Geralmente procuramos em 5 x 10\^-8 uma variante considerada significativa, mas realmente o que estamos procurando é o surgimento dessas torres, que a dependência do álcool faz um ótimo trabalho em demonstrar para nós aqui no cromossomo 4. Antes, como mencionei, este foi um dos primeiros GWAS de transtorno por uso de substituto bem potentes para dependência de álcool, e aqui vemos que esta torre solitária emerge na região ADH1B do cromossomo 4 com um valor p de 9,8 x 10\^-13. Portanto, este estudo teve cerca de 11.500 indivíduos de ascendência europeia que foram diagnosticados com dependência alcoólica e isso foi o mais importante.

Vamos dar uma olhada no próximo slide, então este é atualmente o maior estudo GWAS sobre o uso de álcool, que foi uma meta-análise do uso problemático de álcool em aproximadamente 435.000 indivíduos. E uma coisa que aponto aqui é que no slide anterior estamos vendo a variante mais significativa com o valor p de 9,8 x 10\^-13 e essa era a única torre que estava surgindo. Mas agora, com mais amostras, estamos vendo muito mais picos, incluindo sinais que agora são chamados de genes metabolizadores no cromossomo 4, que aumentaram substancialmente em magnitude e também vemos associações adicionais em genes emergentes, como o que vemos ao longo aqui no cromossomo 2 no gene regulador da glucoquinase que inclui a proteína reguladora envolvida no metabolismo da glicose.

Tudo bem, então, na transição para o uso de nicotina e tabaco, aqui estão as descobertas iniciais do maior GWAS em dependência de nicotina até o momento, aqui avaliadas pelas pontuações do FTND, em um estudo que incluiu 58.000 fumantes. Assim, para a dependência da nicotina e em estudos de outros fenótipos de tabagismo, como cigarros por dia ou tabagismo regular, há uma associação robusta com variantes genéticas dentro de um conjunto de genes do receptor nicotínicos de acetilcolina no cromossomo 15 que inclui o gene CHRNA5, que também é mais especificamente replicado na variante rs16969968, que aqui teve um valor de p de 1,6 x 10\^-39. Portanto, estes são os resultados principais do maior GWAS até agora, mas estudos anteriores encontraram um padrão geral de resultados semelhante.

E com isso, irei em frente e passarei as coisas para Emma para nos contar sobre o que foi encontrado em outros transtornos.

**Ema Johnson:**

Obrigado, Joe. Aqui vou apresentar um gráfico de Manhattan, que mostra os resultados do maior GWAS de transtorno por uso de cannabis até o momento. Este GWAS combinou dados do PGC, iPSYCH e deCODE Genetics e incluiu cerca de 20.000 casos e pouco mais de 360.000 controles. E este GWAS de transtorno por uso de cannabis identificou dois loci significativos. Há um locus no cromossomo 7, onde a principal variante de risco está em um íntron do gene FOXP2. Há também um locus significativo no cromossomo 8, e esse locus foi previamente identificado por Demontis et al. nos dados iPSYCH e replicado nos dados deCODE. A principal variante de risco aqui é um eQTL para CHRNA2 no cerebelo, bem como EPHX2 no cerebelo e tecido adiposo.

Também quero destacar alguns outros resultados do GWAS sobre transtorno por uso de cannabis, e isso foi recentemente aceito no The Lancet Psychiatry. Aqui estamos contrastando as correlações genéticas entre o transtorno da cannabis e uma série de características relevantes e a iniciação à cannabis e as mesmas características. Como você pode ver, há alguma divergência quando olhamos para as correlações genéticas do transtorno por uso de cannabis versus a iniciação ou o uso de cannabis. Estou apontando três em particular aqui. Para o índice de massa corporal, vemos que o transtorno por uso de cannabis está significativamente correlacionado positivamente com o índice de massa corporal. Quando olhamos para a idade de nascimento do primeiro filho, vemos que o transtorno por uso de cannabis está significativamente correlacionado com uma idade mais precoce no primeiro nascimento, e também está significativamente correlacionado negativamente com o nível de escolaridade. Quando olhamos para a iniciação à cannabis, vemos que na verdade existem correlações significativas com essas três características, mas na direção oposta do efeito. E, na verdade, para 12 das 22 características que testamos, aquelas marcadas com um asterisco, vemos correlações genéticas significativamente diferentes quando olhamos para a iniciação à cannabis versus o transtorno por uso de cannabis.

Passando para o transtorno por uso de opioides, este é o maior e mais recente GWAS de transtorno por uso de opioides e combina dados do MVP, Yale-Penn e SAGE. Isto é de Hang Zhou et al., e eles identificaram uma variante de codificação funcional significativa dentro do gene do receptor opioide mu, ou OPRM1.

Também quero destacar alguns resultados interessantes de um GWAS anterior sobre dependência de opioides, de autoria de Renato Polimanti et al. Ele olhou para um PRS para tolerância ao risco, ou um escore de risco poligênico para tolerância ao risco, e um escore de risco poligênico para neuroticismo, e se olharmos para o PRS de tolerância ao risco, Renato viu associações significativas com dois dos contrastes que ele testou. Assim, ele viu que a PRS de tolerância ao risco estava significativamente associada quando comparou indivíduos com dependência de opioides a controles não expostos e quando comparou controles expostos a controles não expostos. Se olharmos para o neuroticismo PRS, vemos que Renato viu associações significativas com o contraste de indivíduos dependentes de opioides e controles não expostos e o contraste de indivíduos dependentes de opioides e controles expostos, então isso sugere que a tolerância ao risco ou comportamentos externalizantes podem estar mais associados com a exposição, enquanto algo como neuroticismo e afeto negativo podem estar mais associados à dependência do que simplesmente à exposição.

Passar para o transtorno por uso de cocaína teve amostras muito menores do que para outros transtornos por uso de substâncias e menos GWAS e pouca replicação até o momento. Mas o que estou mostrando aqui é um dos maiores estudos publicados até hoje, e é de Spencer Huggett e Mike Stallings. E aqui eles estão, na verdade, extraindo estatísticas resumidas do GWAS de um estudo anterior de Gelernter et al., mas estão conduzindo uma associação genética tanto nas amostras euro-americanas quanto nas afro-americanas. Eles identificaram este novo gene significativo NDUFB9 nas amostras afro-americanas. Spencer também fez um trabalho interessante comparando estudos genéticos humanos com modelos de camundongos, e aqui estou mostrando uma figura de um artigo recente em que ele analisou a sobreposição de genes diferencialmente expressos e redes genéticas quando compararam casos humanos de transtorno por uso de cocaína a um modelo de rato de autoadministração de cocaína. Eles observam uma sobreposição genética significativa, sugerindo que alguns destes modelos animais podem ser úteis para estudar transtornos por uso de substâncias, pelo menos no caso da dependência de cocaína.

Joe mencionou anteriormente que estudos com gêmeos e famílias identificaram alguns fatores genéticos comuns compartilhados entre os transtornos por uso de substâncias de forma mais ampla, e vemos isso refletido quando olhamos para os dados do genoma. Então, aqui estou apresentando uma figura à direita, e esta é de um artigo de Jang et al. Quero ressaltar que aqui estamos analisando características de uso de substâncias ou iniciação de substâncias, como uso de cannabis ao longo da vida, se alguém já relatou ser fumante regular, portanto, esses não são transtornos por uso de substâncias em si, mas estão correlacionados com transtornos por uso de substâncias. Vemos correlações genéticas entre transtornos por uso de substâncias, bem como características de uso de substâncias, começando em torno de 0,5 e acima, portanto vemos essas correlações genéticas espelhadas na literatura de genética molecular. Vemos também que os transtornos por uso de substâncias e, neste caso, os traços de uso de substâncias estão correlacionados com outros transtornos psiquiátricos. Assim, no GWAS transtorno por uso de cannabis, vimos uma correlação genética significativa com o transtorno de estresse pós-traumático. O transtorno por uso de álcool e a depressão maior estão significativamente correlacionados, e com o transtorno por uso de opioides, vemos uma correlação genética significativa com o ADHD.

Então, o que vem a seguir no campo da genética do uso de substâncias? No nosso artigo de revisão, descrevemos três áreas principais que consideramos prioritárias para o nosso campo nos próximos anos. A primeira destas prioridades é aumentar a diversidade de amostras que incluímos no nosso GWAS. Assim, a maior parte dos GWAS que apresentamos hoje e certamente os maiores GWAS atuais para o uso de substâncias e transtornos por uso de substâncias incluíram principalmente indivíduos de ascendência europeia. E foi demonstrado que quando os GWAS incluem apenas indivíduos de ascendência europeia, os escores poligênicos de risco derivadas desses GWAS têm utilidade limitada em amostras-alvo de outras populações diversas. Portanto, realmente precisamos aumentar a diversidade de indivíduos que incluímos em nosso GWAS. A segunda prioridade que delineamos é a incorporação de diversos tipos de dados multiômicos, bem como a extensão para dados de espécies cruzadas. Assim, em termos de dados multiômicos, por exemplo, o GTEx é um ótimo recurso que muitos de nós usamos na condução de análises pós-GWAS. No entanto, realmente precisamos de dados específicos de substâncias, portanto, conjuntos de dados de expressão gênica após exposição a substâncias ou transtornos por uso de substâncias. Finalmente, a terceira prioridade que delineamos é o refinamento dos fenótipos e das estratégias de apuração. Assim, como mencionei anteriormente em termos de uso de cannabis versus transtorno por uso de cannabis, vemos alguma divergência para algumas das substâncias de que falamos hoje em termos de uso versus transtorno de uso ou uso problemático. Então, para a cannabis, há algumas evidências disso. Também houve algumas evidências disso para o álcool, por isso, quando comparamos o transtorno por uso de álcool com bebidas por semana ou alguma outra medida de consumo de álcool talvez mais típico. Mas precisamos realmente de fazer um trabalho melhor para determinar se estes fenótipos realmente mostram estas origens genéticas diversas ou se há algo na estratégia de averiguação que nos leva a ver estas correlações genéticas interessantes e por vezes paradoxais quando olhamos para o uso versus transtorno de uso.

Finalmente, em nosso artigo de revisão, tentamos abordar a questão: “Já podemos traduzir qualquer uma dessas descobertas sobre uso de substâncias ou transtorno por uso de substâncias para a clínica?” E a resposta é que infelizmente ainda não chegamos lá. Particularmente com uso de substâncias e transtornos por uso de substâncias. realmente não temos os tamanhos de amostra ou as descobertas robustas e o poder de que precisamos ainda para podermos usar algo como um escore poligênico de risco em um ambiente clínico. Portanto, os escores poligênicos de risco, no momento, explicam uma quantidade tão pequena de variação nas amostras-alvo que essa variação percentual explicada ainda não está em um nível clinicamente significativo, mas esperamos chegar lá um dia e pode haver outras estratégias, como farmacogenética ou estratégias de reaproveitamento/reposicionamento de medicamentos, que podem nos ajudar a traduzir essas descobertas do GWAS para a clínica, eventualmente.

Obrigado por conferir nosso vídeo e gostaríamos de mencionar que se você estiver interessado em trabalhar mais conosco para entender melhor a genética dos transtornos por uso de substâncias, consulte nosso site do PGC. Há informações lá e você pode entrar em contato com qualquer um dos co-PIs do grupo de trabalho sobre transtornos por uso de substâncias. Adoraríamos trabalhar com você. Obrigado.

------------------------------------------------------------------------

# ***Pensamentos e Comportamentos Suicidas*** {#sec-suicide}

**Título**: Visão sobre a genética do suicídio

**Apresentadores**: Hilary Coon, Anna Docherty, Douglas Ruderfer, Niamh Mullins, Eli Stahl (anfitrião)

**Eli Stahl**: OK, vamos em frente e começar. Bem-vindo à reunião Worldwide Lab do Consórcio de Genômica Psiquiátrica (PGC) em 27 de setembro de 2019. Obrigado por participar antes das conferências e durante a temporada de financiamentos. Eu sei que pelo menos dois apresentadores estão em período essencial para o prazo final de 5 de outubro para o NIH, então agradeço reservar um tempo para isso, para vocês que estão apresentando e para todos os participantes. Hoje, temos insights sobre a genética do suicídio de um grupo de colaboradores do PGC, do Consórcio Internacional de Genética do Suicídio e do consórcio psychEMERGE que trabalham com dados EHR. Temos a professora Hillary Coon da Universidade de Utah, a professora assistente Anna Docherty de Utah e o Instituto de Genética Psiquiátrica e Comportamental da Virginia Commonwealth University, VIPBG, o professor assistente Doug Ruderfer do Vanderbilt University Medical Center e a pós-doutoranda Niamh Mullins de Mount Mount Sinai School of Medicine. Os títulos das palestras são mostrados neste segundo slide.

Os títulos das palestras são mostrados neste slide. Estamos planejando quatro palestras curtas, de 10 a 15 minutos, e esperamos que haja tempo para um breve período de perguntas e respostas no final de cada palestra, e então, de acordo com o planejado, teremos de 5 a 10 minutos no final para perguntas ou qualquer discussão mais ampla. Meu plano é procurar na lista de participantes por pessoas que levantem a mão. Se você levantar a mão para fazer uma pergunta, poderei ativar seu som e você poderá fazer sua pergunta diretamente aos palestrantes aqui. Então veremos como isso funciona. Normalmente, você também pode enviar perguntas, você pode digitá-las no botão de perguntas e respostas, depois de pressionar o botão de perguntas e respostas na parte inferior, ou no botão de bate-papo, e nós leremos suas perguntas em voz alta e depois as responderemos. Setembro é o Mês de Prevenção ao Suicídio, “é mesmo?”, você pergunta. Bem, todo mês deveria ser o Mês da Prevenção do Suicídio, e por isso nos concentramos na biologia e na genética do suicídio. Esta é Hillary Coon.

**Hilary Coon**: Muito obrigado. É um prazer poder apresentar a vocês, e estamos absolutamente encantados que o suicídio esteja agora se aproximando da corrente principal da genética psiquiátrica, e é claro que nem sempre foi assim, tem estado à margem, mas isso não aconteceu porque não é importante. Nunca tivemos problemas com as declarações de impacto dos nossos projetos. Portanto, o suicídio é certamente uma enorme crise de saúde pública, é a décima principal causa de morte nos EUA. Em 2017, mais de 47 mil pessoas morreram por suicídio, e esse número ultrapassa 800 mil pessoas em todo o mundo. E as tentativas são muito mais comuns: então, para cada suicídio, há de 25 a 30 tentativas. Portanto, um grande problema mundial, um problema crescente,

e vou dar-lhes uma visão geral dos comportamentos suicidas e da morte por suicídio, em nossas conversas abrangeremos o espectro desses dois resultados. Portanto, certamente o problema é que as tentativas estão a aumentar, e a nossa predição de tentativas é bastante fraca nesta fase, o que significa que a prevenção é realmente um desafio, e uma possível solução para isto está realmente na genética.

Portanto, a herdabilidade do comportamento suicida a partir de estudos com gêmeos e famílias é de até 55%, o que sugere alguma promessa no uso desse tipo de dados para realmente nos ajudar na previsão e prevenção. Temos uma oportunidade, porém, porque a maioria dos estudos de associação genômica em larga escala anteriores foram realizados dentro de diagnósticos psiquiátricos específicos e, na verdade, a maioria deles não foi grande o suficiente para identificar quaisquer loci significativos replicados. Portanto, é realmente o momento certo para estudos usando amostras populacionais realmente grandes e também amostras psiquiátricas muito grandes dentro do Consórcio de Genômica Psiquiátrica e você ouvirá sobre ambos os esforços de nossos colegas, Dr. Ruderfer e Dr. Mullins.

Em Utah, nos concentramos mais nas mortes por suicídio, e isso se deve em parte a alguns recursos sobre os quais falarei em alguns minutos. Eu só queria destacar algumas das diferenças entre a morte por suicídio e a tentativa de suicídio, que estavam realmente focadas na tentativa de descobrir algumas das diferenças potenciais na etiologia genética entre esses dois resultados. Então, em um nível muito básico, a morte por suicídio é muito mais rara do que as tentativas (mencionei isso no slide anterior), e se você olhar para outro tipo de variável etiológica básica, que é o sexo, especialmente a morte é muito masculina. Nos EUA, esta proporção entre homens e mulheres é de quase quatro para um. Para tentativas, é mais difícil obter contagens precisas, mas elas são muito mais comuns em mulheres, e isso ocorre especialmente em jovens, onde as mulheres têm duas vezes mais chances de tentar. Vale ressaltar também que mostrei um slide sobre o aumento da incidência de tentativas; os incidentes de morte por suicídio também estão aumentando dramaticamente. Aumentou cerca de 33% desde 1999.

Portanto, uma questão sobre a qual pensamos muito é até que ponto o suicídio realmente tem alguma semelhança etiológica dramática com a doença mental. Muitos dos indivíduos que morrem por suicídio lutam contra doenças mentais, e esta tem sido muitas vezes uma situação crónica, mas também sabemos que a maioria dos indivíduos que têm uma doença mental não morre por suicídio. Portanto, há alguma indicação de que o suicídio tenha alguma outra etiologia além da vulnerabilidade psiquiátrica.

O slide que eu tinha aqui não é, na verdade, de uma família extensa de Utah; na verdade, isso é do trabalho seminal de Jenna Egeland na Velha Ordem Amish. Esta é uma família suicida que é uma das muitas famílias que ela estudou para depressão grave e transtorno bipolar. E o que ela descobriu foi que os registos de suicídio se expandiram durante cem anos nesta coorte, e desses suicídios, todos caíram em apenas quatro das famílias que ela estava a estudar, e ela chegou a uma conclusão (isto foi na década de 1980). que o suicídio era significativamente familiar e que parecia haver alguns riscos independentes da psicopatologia ou pelo menos que abrangiam vários transtornos psiquiátricos. Há um outro trabalho seminal feito por Brent e Mann publicado em 2005; isso também sugere que existem fatores de risco potencialmente exclusivos para o suicídio.

Mencionei que a tentativa de suicídio é significativamente genética. Estes são alguns dados de estudos agregados de estudos de gêmeos e de adoção de morte por suicídio. Portanto, esse resultado também parece ser significativamente genético. Você pode ver que os gêmeos idênticos são muito mais concordantes do que os gêmeos fraternos, e nos estudos de adoção, os parentes biológicos correm muito mais risco do que os parentes adotivos. A partir de algumas meta-análises deste trabalho, a evidência de morte por suicídio é, na verdade, semelhante à herdabilidade da tentativa; é cerca de 50%.

Ok, então por que Utah? Bem, Utah tem o tipo de distinção duvidosa de estar no quinto ou sexto lugar em taxa de suicídio (caiu para o sexto recentemente, mas ainda assim estamos no que é chamado de cinturão de suicídio dos EUA). Em Utah, o suicídio é, na verdade, a principal causa de morte de pessoas com menos de 25 anos. Também temos recursos excelentes que tornam a logística para fazer isso fantástica. Portanto, temos um consultório médico legista centralizado, e o médico legista está realmente interessado em colaborar conosco, e já colaboramos há cerca de vinte anos. Temos agora mais de 6.200 indivíduos que morreram por suicídio com DNA, e este número cresce a uma taxa de cerca de 700 por ano. Então, nos próximos cinco anos, teremos cerca de 10 mil pessoas que morreram por suicídio com DNA.

Também podemos vincular esses casos a um recurso populacional fantástico chamado banco de dados populacional de Utah. Este é um banco de dados estadual que inclui acesso a extensos dados de registros médicos, dados demográficos, registros genealógicos e dados geográficos, o que nos permite observar as exposições e é um recurso excelente. Agora, um dos aspectos potencialmente mais exclusivos deste recurso são, na verdade, as famílias extensas. Temos famílias muito grandes de alto risco no banco de dados populacional de Utah através de uma doação de dados genealógicos da Igreja LDS, e identificamos quarenta e três famílias de muito alto risco onde procuramos compartilhamento familiar, compartilhamento genômico e pessoas que eram então relacionados desta forma distante. Na verdade, publicamos isso na Molecular Psychiatry e encontramos 30 regiões significativas em dez dessas famílias. Estamos acompanhando isso com alguns dados de sequencimento e listei abaixo algumas dessas famílias que nos deram essas regiões significativas. As pessoas que realmente possuem dados estão circuladas em vermelho. Então, descobrimos que as regiões genômicas que são familiares são difíceis de acompanhar porque o que está impulsionando essa importância é provavelmente regulatório; não é necessariamente fácil ver uma única variante com penetrância muito alta. Enquanto isso, o que estamos fazendo é usar os casos familiares de duas maneiras diferentes para abordar outras hipóteses.

Então, essas famílias, essas pessoas nessas famílias, na verdade representam casos com risco genético aumentado. Frequentemente, depois de algumas gerações, eles estão ligados a vários fundadores comuns. Portanto, o risco genético não faz parte apenas de uma única família. Chamamos isso carinhosamente de “spaghettigrees” no banco de dados populacional de Utah, e isso também acontece com outras condições. Então eles realmente representam um enriquecimento familiar. Isso também é enriquecimento genético, né, porque esses casos compartilham muito pouco ambiente comum; eles são parentes muito distantes. Então, o que pensamos em fazer é olhar para esses casos e ver se eles parecem ter um risco significativamente elevado de psicopatologia e usar o escore poligênico de risco (PRS) (e você ouvirá mais sobre o escore poligênico de risco da minha colega, Dr. Docherty), o que fizemos foi olhar para esses casos geneticamente enriquecidos (o subconjunto europeu deles), calcular o escore poligênico de risco para uma variedade de 60 características, e então apenas olharmos para a diferença entre esses casos geneticamente enriquecidos e nossas outras mortes por suicídio, ajustando novamente para efeitos de ancestralidade residual. Também incluímos escores poligênicos de risco de morte por suicídio, diretamente para nossa própria coorte, e usamos uma validação cruzada de 10 vezes para fazer isso, uma vez que é direta em nossos próprios casos.

Então, aqui está o que descobrimos: os suicídios familiares de alto risco são, na verdade, significativamente elevados apenas pelo risco de morte por suicídio. Não encontramos enriquecimento para nenhuma outra psicopatologia nesses casos selecionados por risco genético. Eles simplesmente parecem enriquecidos para a morte por suicídio, e achamos isso muito interessante. Esperávamos que eles fossem enriquecidos para algum outro risco genético de psicopatologia, mas não encontramos isso.

Portanto, também estamos analisando esses casos e começando a ver algumas associações no nível da via genética entre eles. Olhando para variantes estruturais raras e variantes de nucleotídeo único de alto impacto, parece que estão começando a corresponder às descobertas do nosso GWAS, o que é muito interessante. Se quiser falar comigo sobre isso, terá que me encontrar no Congresso Mundial; não tenho tempo para falar sobre isso agora, mas é um trabalho emocionante.

Nós realmente acreditamos que estudar a morte por suicídio é importante, é claro, estudar a tentativa também é muito importante, mas ao estudar a morte por suicídio, podemos realmente tentar chegar à descoberta genética para os casos de alto risco mais elevados, e podemos realmente começar a observar até que ponto a etiologia difere entre a tentativa de suicídio e a morte.

Eu só quero agradecer a muitas pessoas que estão trabalhando neste projeto. É um recurso realmente grande, fantástico, com muitas pessoas da Universidade de Utah e de diferentes departamentos da nossa universidade e muitos colaboradores externos. E isso está crescendo; estamos muito entusiasmados por fazer parte do trabalho do consórcio internacional e de muitas pessoas que apoiaram este trabalho.

**Eli Stahl**: Obrigado, Hillary. Acho que vale a pena dedicar um pouco de tempo para perguntas. Se alguém tiver alguma dúvida, levante a mão ou digite novamente sua pergunta na caixa de perguntas e respostas ou na caixa de bate-papo rapidamente, antes de passarmos para a próxima apresentação. Cinco quatro três dois um. Ok, passaremos para a próxima apresentação, que é Anna Docherty.

**Anna Docherty**: Ok, obrigado por participar hoje, e vou discutir brevemente a análise de associação genômica das amostras de mortes por suicídio aqui em Utah, a partir dos incríveis recursos que Hillary Coon obteve aqui. Esta será uma conversa breve, por isso estou obviamente feliz em fornecer detalhes off-line também às pessoas interessadas.

Nosso estudo de associação genômica em larga escala das primeiras mortes por suicídio genotipadas foi um projeto de caso-controle com 3.413 mortes por suicídio em Utah, estas são mortes por suicídio não finlandesas do norte da Europa e 14.810 controles. Tivemos alguns desafios significativos na análise de associação genômica usando dados de suicídio em Utah, porque não temos controles em Utah e, ​​portanto, tivemos que tomar várias medidas para filtrar e minimizar falsos positivos em nossas análises. Outro desafio é que temos apenas cerca de 20 por cento da nossa amostra com miscigenação significativa e, portanto, com este conjunto de dados preliminares, não tivemos uma amostra suficiente para completar um GWAS com múltiplas ancestralidades, embora esperemos que nos próximos três anos teremos os números para fazer isso.

Então, falarei sobre as etapas para minimizar falsos positivos em um momento. Estes são os gráficos de análises de componentes principais (PCA) das mortes por suicídio e os controles da Geração Escócia e UK10K que usamos, bem como as superpopulações 1000Genomes. À esquerda, você verá gráficos de toda a amostra e, à direita, verá uma visualização ampliada da dobradiça de toda a amostra. Na parte superior, você verá os suicídios e controles mapeados para 1000Genomes e, na parte inferior, verá apenas as mortes por suicídio e as amostras de controle, junto com aquelas que excluímos para esta análise.

Tomamos várias medidas para filtrar possíveis falsos positivos. Primeiro, imputamos conjuntamente casos e controles de uma lista de SNPs comuns. Também criamos limites em torno de um centróide nos dados do CEU (os dados europeus 1000Genomes), onde 99% das amostras do CEU ficaram dentro desses limites. Em seguida, excluímos os casos e controles que não se enquadravam nesses limites. Também, para a análise GWAS, utilizamos modelos mistos com matrizes de parentesco genômico e PCs de ancestralidade. Para esta análise, queríamos usar duas coortes de controle porque estávamos preocupados com a possibilidade de efeitos específicos para cada coorte de controle, efeitos falsos positivos. E então, queríamos filtrar esse sinal. E assim conduzimos um GWAS de controle-controle antes do GWAS de caso-controle, e então o sinal sugestivo foi filtrado desse GWAS de caso-controle subsequente.

Estou mostrando aqui os resultados dos 3.400 suicídios e cerca de 14.000-15.000 controles. Estes são os resultados do GWAS indicando seis variantes de dois loci associados à morte por suicídio em um nível significativo. Tínhamos outras 52 variantes que eram nominalmente significativas e correspondiam a 19 genes. Como você pode ver aqui no gráfico de Manhattan, o nível de significância de todo o genoma está em verde e nossa correção FDR em roxo está em 0,1. Nosso lambda para esta análise foi 1,015.

Aqui estão os principais SNPs com importância genômica ampla nos cromossomos 13 e 15. A maioria deles é intergênica. Nossa herdabilidade baseada em SNP de regressão de pontuação LD para esta análise foi de 0,246 com um erro padrão de 0,036, portanto altamente significativo.

Estes são os nossos resultados baseados em genes do GWAS, 10 com correção de FDR em 0,1. Usamos o MAGMA para detectar 19 genes associados ao suicídio de um total de cerca de 18.000 genes. Nosso lambda para este teste foi 0,994. Associações de SNPs do cromossomo 13 foram encontradas em três genes, incluindo DACH1. 11 dos 19 genes têm evidências prévias de associação com comportamentos suicidas, e houve uma associação significativa com resultados de Esquizofrenia do GWAS Catalog. Dez dos genes também mostram evidências de expressão gênica diferencial significativa no cérebro post-mortem na esquizofrenia, no autismo ou no transtorno bipolar, e isso é corrigido em 0,05.

Queríamos aproveitar o fato de termos duas ondas de amostras de mortes por suicídio e duas coortes de controle para validar de forma cruzada e prever o risco poligênico de morte por suicídio com base no status do caso-controle. Então, o que fizemos aqui foi, para orientar cada um desses gráficos no eixo y, você verá, centrado em torno de zero, o escore poligênico de risco para suicídio, e no eixo x, você verá o limite do valor p ponto de corte para o escore poligênico de risco, começando em 10% da variância até toda a variância. No primeiro gráfico à esquerda, usamos a Onda 1 e a Geração Escócia como amostra de treinamento para pontuar a Onda 2 e UK10K e, em seguida, o procedimento foi invertido no gráfico à direita. Em ambos os casos, o PRS suicida diferenciou significativamente os casos dos controles.

Para esta próxima análise, pretendi caracterizar o risco poligênico em casos de suicídio para diferentes distúrbios potencialmente relevantes para a morte por suicídio. Então aqui, esses enredos são um pouco diferentes, estão tramando suicídio em vermelho, Geração Escócia e controles UK10K em verde e azul. Estes PRS são baseados em dados resumidos de grandes GWAS existentes de múltiplos fenótipos. O que descobrimos são aumentos significativos nos fenótipos que esperaríamos estar relacionados ao suicídio, incluindo depressão, transtorno do espectro autista, desinibição, esquizofrenia e uso de álcool.

Também queríamos nos aprofundar em alguns dos dados clínicos e nos dados sobre o modo de suicídio, e existem quatro tipos de suicídio, porque algumas das pesquisas epidemiológicas sugerem etiologias bastante complexas e subtipos potencialmente de risco. Então, observei os diagnósticos do CDI a partir dos registros eletrônicos de saúde nas mortes por suicídio, e também no modo de morte, no que diz respeito ao escore poligênico de risco para essas condições. Uma descoberta notável que vale a pena mencionar é que o suicídio por trauma violento, que é mais raro, é uma forma mais rara de suicídio, foi associado tanto ao diagnóstico clínico de esquizofrenia quanto ao risco poligênico de esquizofrenia.

Estou colocando aqui alguns dos diagnósticos mais prevalentes associados à amostra de suicídio para mostrar que, embora as taxas de esquizofrenia sejam muito altas nesta amostra, os diagnósticos associados à morte por suicídio são tipicamente bem diferentes. Vemos muita depressão relacionada à dor, diagnósticos de ansiedade, bem como distúrbios cardiovasculares e metabólicos.

Só para finalizar, temos alguns objetivos futuros aqui com uma coorte maior para completar uma replicação com controles PGC. Estamos trabalhando em uma análise condicional e conjunta baseada em múltiplas características usando dados resumidos do GWAS. Estou interessado em realizar análise de múltiplas ancestralidades quando finalmente tivermos amostras suficientes com miscigenação significativa, e tivermos localizado, com a ajuda do Dr. Stahl, os controles da Psiquiatria Genômica. Também estamos fazendo algumas subtipagens genéticas com nosso GWAS e trabalhando para aproveitar o PRS de morte por suicídio para melhorar os modelos de previsão de mortalidade por suicídio em oposição à tentativa de suicídio, com os colegas Eli Stahl, Niamh Mullins e Doug Ruderfer. E com isso termino e agradeço a todos os colaboradores do estudo e consultores.

**Eli Stahl**: Obrigado, Anna. Temos mais um curto período para tirar dúvidas. Então, por favor, digite novamente qualquer dúvida que você possa ter na caixa de perguntas e respostas ou na caixa de bate-papo. Alternativamente, você pode levantar a mão e eu posso ativar seu som.

Temos uma pergunta que foi digitada na caixa de bate-papo por Paul Nestat. Se você quiser leia e responda, ou eu posso fazer se você quiser.

**Anna Docherty**: Eu não tenho... você pode...

**Eli Stahl**: ok Pergunta: Houve algum motivo para os controles não terem sido extraídos de outras investigações de morte (não suicídio) do Utah Medical Examiner? Presumivelmente, se eles pouparam sangue de mortes por suicídio, também o fizeram para outras pessoas. Em Maryland, planejamos usar as mortes de passageiros do MVA como controle quando analisamos sangue de suicídio do médico legista, por exemplo.

**Hilary Coon**: Certo, na verdade... eu posso responder isso. Esse é um grupo de controle perfeito e temos tentado obter permissões para isso. Nossos médicos legistas foram reduzidos em cerca de quatro médicos legistas. Recentemente, eles contrataram mais algumas pessoas, então eles estão muito ocupados, sobrecarregados, e toda vez que peço mais, eles dizem: "Vamos pensar sobre isso". Então, definitivamente estamos trabalhando nisso. Temos algumas outras oportunidades potenciais para algumas amostras de biorrepositórios, mas estamos muito, muito interessados ​​em obter um grupo de controle específico para Utah. Reconhecemos que este é um grande problema. Temos um pequeno grupo de controle em Utah, pessoas não relacionadas do CEPH CEU, ou pessoas de Utah. Temos outro grupo de controle que são de um estudo de indivíduos idosos saudáveis. Muitos dos estudos em Utah são feitos com famílias porque isso é um grande ponto forte aqui. Então isso é um pouco desafiador. Temos coletado pessoas não relacionadas em vários estudos familiares também como controle. Então, sim, estamos trabalhando nisso e definitivamente trabalhando em nosso médico legista também. Muitos de vocês sabem, dar um agrado para o médico legista para ver se eles podem nos ajudar com algumas dessas amostras.

**Eli Stahl**: Ok, se houver alguma outra dúvida? Alguma outra dúvida neste momento? Então, vamos seguir em frente e ouvir Doug Ruderfer.

**Doug Ruderfer**: Excelente! Bem, obrigado Eli por organizar isso, e estou feliz por fazer parte desta sessão. Isso merece uma sessão inteira para o encontro mundial e feliz por ter ótimos colegas que se dedicam a esses temas. Entramos nisto pelas mesmas razões que mencionamos aqui, por todas as razões importantes de saúde pública e pela necessidade de aprender sobre a biologia contínua deste resultado devastador. Chegamos a isso de uma direção um pouco diferente, e isso é parcialmente uma exigência, e todos estão familiarizados com essa ideia de amostras populacionais, têm fenótipos poderosos limitados que são de baixa prevalência, e para nosso próprio trabalho em Vanderbilt, nós temos cerca de três milhões de pacientes únicos que foram atendidos pelo menos uma vez no hospital, mas muitos desses pacientes na verdade vêm para procedimentos específicos, ou dão à luz, ou vão a um centro de trauma, ou vão ao pronto-socorro, e não têm muito de dados reais. Se tivéssemos três milhões de novos pacientes e tivéssemos DNA de todos eles, poderíamos ter um estudo de associação genômica em larga escala bastante bem desenvolvido, mesmo para uma doença de 1%, mas claramente não o temos.

Se pensarmos nos indivíduos onde temos dados longitudinais, múltiplos eventos, o que chamamos de nossos “visitantes frequentes”, ou pacientes médicos domiciliares, reduzimos substancialmente o número de indivíduos para cerca de 1 milhão de pacientes, e claro, coletando DNA de todos desses ainda seria um desafio, embora tenhamos um processo de coleta bastante robusto, onde temos cerca de 250.000 indivíduos que possuem DNA em nosso biobanco, denominado BioVU.

Mas como vocês podem ver, esses números que estão diminuindo neste exato momento estão aumentando rapidamente; cerca de metade deles foram genotipados e, novamente, isso mudou dramaticamente ao longo do último ano e também mudou, mais ou menos, nesta palestra que vou dar, então não temos casos suficientes no Biobanco para constituir um estudo genético significativamente poderoso, mas o que estávamos tentando pensar é como podemos aproveitar esta informação, esta extensa informação clínica, os dados clínicos que temos, e o grande tamanho geral da amostra que existe, para melhorar a nossa capacidade para estudar a genética dessas doenças de baixa prevalência.

E esse é o tipo de questão que nos levou a pensar no suicídio como um fenótipo particular de interesse e que tem sido difícil de determinar, mas também muitos outros fenótipos potenciais, e apenas no interesse do tempo, para ir direto ao assunto, o que estamos tentando fazer aqui e qual foi a nossa abordagem, pensamos na nossa amostra de um milhão de pacientes. Podemos identificar os casos como um conjunto de indivíduos da melhor qualidade possível, validados por prontuários "padrão ouro", e então podemos utilizar as informações clínicas que temos dos registros eletrônicos de saúde que podem ser dados estruturados, que são fáceis de utilizar, trabalhar com anotações, laboratórios, de diagnósticos, medicamentos, códigos de procedimento, para construir um modelo preditivo. E a ideia é que podemos construir um modelo preditivo e demonstrar que o modelo é preditivo e preciso, o que significa que se dissermos que uma pessoa está no caso, ela é um caso e está bem calibrada, o que significa que dizemos aos indivíduos 20% de probabilidade de ser um caso, então 20% dos indivíduos estão realmente em casos.

Então o que fizemos foi converter nosso resultado binário em uma medida quantitativa, que teoricamente deveria ser bem mais poderosa do que usar o status de caso-controle. Então esse é o argumento, a teoria que estamos tentando trabalhar. Há um trabalho teórico muito bom de Yang, Wray e Visscher realmente fazendo esses cálculos e comparando o poder efetivo entre uma característica quantitativa e uma característica binária, mostrando que particularmente para fenótipos de baixa prevalência você tem muito, muito, muito mais poder para estudar o traço quantitativo do que o traço binário em si, e sugiro olhar para o artigo, é realmente fantástico.

Esse tipo de trabalho alavancador, aquele que está sendo realizado pelo meu grande colega Colin Walsh, queríamos aplicá-lo ao suicídio, novamente, por todas as razões de saúde pública e pelo interesse, e na época em que começamos isso há alguns anos, havia conhecimento limitado em termos da genética subjacente para esta característica específica. Em geral, é ótimo ver que isso avançou rapidamente nos últimos dois anos. Ao revisar os prontuários de todos os indivíduos que tinham códigos de autolesão, cerca de 8.000 indivíduos, eles examinaram cada um deles para identificar aqueles que poderiam confirmar manualmente, para validar através dos prontuários, que tiveram uma tentativa de suicídio. Há cerca de 3.000 indivíduos em nosso conjunto de dados que tiveram essa tentativa de suicídio validada por prontuário. Poderíamos construir agora um modelo para prever tentativas de suicídio, aproveitando o restante dos dados que temos, incluindo informações demográficas, medicamentos, diagnósticos e utilização de hospitais. E acontece que o uso de florestas aleatórias teve o melhor desempenho entre uma série de abordagens, e forneceu uma precisão de previsão mais próxima de 0,9 ou mais, e um modelo bem calibrado, ajustando-se assim à expectativa que pensamos que em teoria deveria nos fornecer uma característica quantitativa isso seria bem alimentado em comparação com nosso resultado binário.

E aplicamos isto à amostra que tínhamos na altura, que é de cerca de 25.000 indivíduos europeus que foram genotipados. E para lembrar, entre os indivíduos genotipados, 73 eram casos. O que estamos tentando fazer aqui é aproveitar esses dados clínicos para construir uma característica quantitativa para demonstrar que podemos ter poder para fazer GWAS em 73 casos usando a característica quantitativa.

Então, precisávamos de um grupo externo para comparar isso, precisávamos de um resultado de paciente classicamente definido para fazer isso. Por isso, aproveitamos o trabalho com nosso colega Manny Rivas em Stanford para usar o UK Biobank. Entre os 500 mil indivíduos, cerca de 150 mil deles preencheram uma avaliação on-line de saúde mental e receberam, ou aqueles que responderam “sim” a uma pergunta sobre automutilação, a pergunta: “Você já se machucou com a intenção de acabar com sua vida?" que é uma boa pergunta sobre tentativa de suicídio porque inclui intenção. 3.500 indivíduos responderam “sim”, após controle de qualidade de seus dados genéticos e redução a uma ascendência britânica homogênea, houve cerca de 2.400 casos de tentativa de suicídio. E comparamos isso com todos os controles. Se compararmos apenas com os controles que preencheram a avaliação de saúde mental online, os resultados não mudam.

Portanto, isso nos fornece agora um fenótipo de tentativa de suicídio autorrelatado classicamente determinado pelo paciente e o conjunto de dados para compará-los, embora, novamente, nenhum desses estudos deva ser bem desenvolvido para um GWAS em grande escala para uma característica poligênica.

Portanto, a primeira coisa que podemos fazer é realmente realizar um estudo de associação genômica em larga escala no UK Biobank e, não surpreendentemente, não encontramos nenhum loci significativo. Podemos então pegar esse resultado, construir escore poligênicos de risco do Biobank do Reino Unido e aplicá-lo ao nosso status de caso-controle em nossa amostra BioVU, e vemos um enriquecimento nominalmente significativo, embora sejam 73 casos, que esses indivíduos carregam risco genético mais elevado de suicídio com base no UK Biobank GWAS do que nos controles. E se compararmos agora com uma probabilidade prevista de risco de suicídio, vemos uma correlação muito mais significativa entre o risco genético subjacente de suicídio e a probabilidade de tentativa de suicídio. E isso vale mesmo se removermos esses 73 casos, então o poder não é gerado a partir desses casos, mas na verdade é gerado a partir dos dados clínicos que informam essa probabilidade, como parte dos controles. Como esperamos. Podemos fazer um estudo de associação genômica em larga escala apenas em nossa amostra BioVU, e vemos dois resultados significativos que foram adiados no momento porque nenhum deles foi replicado no UK Biobank, mas vale a pena investigar mais profundamente enquanto aumentamos o tamanho da amostra, sobre a qual Niamh lhe contará mais sobre a diretriz dela para fazermos isso.

E o mais interessante é que podemos olhar para os nossos gráficos QQ, para podermos olhar para a nossa herdabilidade, e encontramos estimativas de herdabilidade significativas e comparáveis ​​entre a nossa amostra do UK Biobank e a nossa amostra do BioVU, cerca de 4% ou 5%.

E eu acho que o mais interessante é que você pode fazer um cálculo de correlação genética direta entre essas duas amostras, e então se houver uma correlação genética significativa entre as duas amostras diferentes de duas maneiras diferentes de fenotipagem, chegando perto de 1 com intervalos de confiança altos, e também podemos mostrar que correlações genéticas significativas com características que esperaríamos com base em nossa compreensão do risco clínico de tentativa de suicídio, incluindo sintomas depressivos, depressão maior, neuroticismo, esquizofrenia, insônia e, algo interessante, uma relação negativa com a idade do primeiro nascimento, que mostrou em outros distúrbios, incluindo esquizofrenia.

Então, para resumir, pensamos neste tipo de modelo, novamente, se você puder ser preciso, se você puder ter uma boa calibração, puder capturar a contribuição genética, então efetivamente, você pode fazer um GWAS com um pequeno número de 73 casos, identificando alguma herdabilidade, e mostrou que estava significativamente correlacionado geneticamente com um resultado padrão relatado pelo paciente. Existem muitas oportunidades para utilizar esta abordagem para fenótipos que são difíceis de determinar ou de baixa prevalência, e pensamos nisso tanto no nosso trabalho como também no UK Biobank, agora que eles têm informações sobre cuidados primários.

O bom desse tipo de abordagem, novamente se funcionar, é que seu poder aumenta com o tamanho da amostra, não apenas com o número de casos. E estamos tentando fazer isto agora com as 60.000 amostras europeias adicionais que temos na nossa própria amostra BioVU para demonstrar ainda mais esse aumento de potência.

Temos um trabalho que é atualmente financiado por Colin e nosso colega Roy Perlis do MGH para fazer a mesma abordagem e aplicá-la à resistência ao tratamento na depressão e na esquizofrenia.

E no suicídio tem ido mais longe com o nosso colega Adi Bejan, pensando em como podemos identificar mais indivíduos com notas. Uma das coisas que faltam atualmente são todas as tentativas históricas de suicídio que podemos capturar, mas milhares de outros indivíduos têm tentativas históricas de suicídio e podemos capturar pensamentos ou ideações suicidas usando notas narrativas clínicas. E podemos demonstrar que podemos melhorar nosso modelo de previsão, mas também demonstrar a precisão disso usando a PNL com as previsões que temos atualmente. Então, meio que reiterando modelos aprimorados, maior poder para estudos genéticos à medida que avançamos.

Então, com isso, vou apenas agradecer aos maravilhosos colegas que estão envolvidos em toda a genética do suicídio aqui, aos meus colegas diretamente Colin, Adi e Mani, a todos no meu laboratório e, claro, a todo o financiamento e a todos os outros por ouvirem.

**Eli Stahl**: Obrigado, Doug. Novamente, vamos fazer um breve período de perguntas agora. Você pode levantar a mão como participante e eu posso ativar seu som para participar da conversa. Ou você pode digitar suas perguntas nas caixas de diálogo de perguntas e respostas ou de bate-papo. Então, há uma pergunta nas perguntas e respostas: Doug, você consegue ver? Ou posso ler para você, se quiser.

**Douglas:** Eu posso ver isso. Certo. Então, acho que começamos a… Ok, deixe-me ler a pergunta caso nem todos estejam olhando para ela. A pergunta de Adrian Campos: “Que dados faltam no UK Biobank para calcular o modelo de responsabilidade por suicídio?” Antes do GWAS, e até recentemente, faltavam muitos dados. Então, foi principalmente autorrelato e relatório do paciente, que eram as informações que usávamos, mas a extensa informação longitudinal torna-se realmente valiosa para muitos dos modelos que estamos usando atualmente, que é baseado mais em códigos de diagnóstico, medicamentos, e códigos de procedimento, que agora, considerando, creio, para alguns indivíduos, têm suas informações de atenção primária. Acho que isso é mais, é muito mais possível aproveitar essas informações para construir modelos semelhantes no UK Biobank, e essa é a nossa esperança de levar isso adiante.

**Eli Stahl**: Obrigado. Há alguma outra dúvida neste momento? Ok, podemos passar agora para a nossa apresentação final, Niamh Mullins.

**Niamh Mullins**: Obrigado. Ok, você pode ver meus slides? E você pode me ouvir? Portanto, este é um desenho entre casos e visa detectar associações específicas para tentativa de suicídio, e não para transtorno psiquiátrico, e variantes que ocorrem com maior frequência em tentativas de suicídio em comparação com outros casos psiquiátricos. Fiz um GWAS de tentativa de suicídio em cada transtorno, seguido de meta-análise entre eles. No total, foram mais de seis mil e quinhentos casos de tentativa de suicídio.

Houve algumas associações significativas. Um no GWAS de tentativa de suicídio em transtorno depressivo maior, tinha um MAF de 2%; e outro em tentativa de suicídio em transtorno bipolar, que teve frequência de 20%. No GWAS de tentativa de suicídio em esquizofrenia, não houve associações significativas.

Em uma meta-análise sobre tentativa de suicídio em transtornos de humor, houve dois loci significante no GWAS. Um deles no cromossomo 2, novamente tinha um MAF baixo e apenas um SNP ultrapassando o limite. Mas este no cromossomo 4 é o mesmo locus que surgiu no GWAS de tentativa de suicídio em transtorno bipolar, e a associação foi reforçada na meta-análise, dez SNPs ultrapassaram os limites de significância de todo o genoma, e há um belo pico aqui de SNPs em LD, e a região é uma localização de um longo RNA não codificante. Em apoio ao desenho do nosso estudo, não foi associado à depressão ou ao transtorno bipolar, sugerindo sua especificidade para uma tentativa de suicídio.

Então, este parecia ser um locus muito promissor, e queríamos tentar replicar esta associação. Então, recorremos aos nossos colaboradores que trabalham na amostra do UK Biobank e na amostra do iPSYCH na Dinamarca. Eles retiraram casos com transtornos de humor e os dividiram em tentativas de suicídio e não-tentativas para replicar o desenho do nosso estudo. Os números eram muito decentes; tivemos uma replicação boa e poderosa, mas não houve associação entre este SNP principal e tentativa de suicídio em nenhum dos conjuntos de dados de replicação.

Uma das descobertas mais interessantes deste artigo foi que os escores poligênicos para depressão estão associados à tentativa de suicídio em cada um desses transtornos psiquiátricos. Então, o que estou mostrando aqui é um escore poligênico para depressão que prevê tentativa de suicídio versus não tentativa, da esquerda para a direita, no transtorno bipolar, transtorno depressivo maior e esquizofrenia. Assim, mesmo dentro da depressão, por exemplo, os casos de depressão que fizeram uma tentativa de suicídio têm maior risco genético de depressão em comparação com os casos de depressão que não fazem uma tentativa de suicídio. E mesmo que estes sejam dados antigos do PGC, não há sobreposição aqui entre as amostras base e alvo.

Também foi interessante que esse achado pareça ser específico do escore poligênico de depressão. Então, aqui nas barras rosa, estou testando se um escore poligênico para transtorno bipolar difere entre pessoas que tentam suicídio e que não tentam suicídio com transtorno bipolar. Não há diferença entre os dois grupos. O que estou mostrando em verde é que há uma diferença nas pontuações poligênicas para esquizofrenia entre pessoas que tentam suicídio e pessoas que não tentam suicídio com esquizofrenia. Mas na verdade são os que não tentam o suicídio que apresentam maior risco genético de esquizofrenia e, como eu disse, os que tentam o suicídio com esquizofrenia apresentam maior risco genético de depressão. Então, essencialmente, a mensagem a levar para casa das análises de escore poligênico de risco é que, em todos os transtornos psiquiátricos, os que tentam suicídio têm uma maior probabilidade genética para a depressão, e não apenas uma maior probabilidade genética para o transtorno psiquiátrico pela qual são afetados. E mesmo que não tenhamos atingido o tamanho das amostras onde estamos replicando associações significativas para tentativas de suicídio entre coortes, estamos começando a obter insights sobre a etiologia genética do fenótipo usando métodos poligênicos. Este foi um esforço colaborativo de muitas pessoas no PGC e de três grupos de trabalho, por isso gostaria de agradecer a todos os colaboradores, e as estatísticas resumidas do GWAS estão todas no site do PGC.

Para a parte final da sessão de hoje, queríamos apresentar a nova iniciativa da qual todos os apresentadores fazem parte, e muitos outros também, que é o Consórcio Internacional de Genética do Suicídio. Este é um grupo de trabalho criado no ano passado e nosso objetivo é realmente ampliar os estudos genéticos do suicídio para o tamanho da amostra que todos sabemos ser necessário. Nosso objetivo inicial era realizar uma meta-análise de todas as estatísticas resumidas do GWAS que poderíamos obter sobre tentativa de suicídio ou morte.

Temos 15 grupos participantes e, até agora, reunimos dados sobre mais de 27 mil casos de tentativa de suicídio ou suicídio, incluindo uma série de diagnósticos psiquiátricos, bem como vários ancestrais genéticos. O grupo foi iniciado por mim e Doug, junto com a ajuda e orientação de Cathryn Lewis e Eli Stahl.

Estes são todos os nossos membros e todos os estudos apresentados hoje estão representados. Também temos o estudo Generation Scotland, Army STARRs, temos duas coortes afro-americanas: a Janssen está trabalhando conosco, a Columbia University, o German Borderline Genetics Consortium, Karolinska. A maioria das amostras são europeias; também temos duas coortes do Leste Asiático. Recentemente, recebemos dados do novo estudo Australian Genetics of Depression e, claro, o PGC está envolvido, incluindo o Eating Disorders Working Group. Então, é um esforço mundial.

Você notará que temos muitos tipos diferentes de coortes aqui e queríamos realmente tentar aproveitar todos os dados que pudéssemos para este projeto. Assim, desenhamos o estudo sob três modelos de análise. Dependendo do tipo de coorte, ela pode ser analisada sob um ou mais desses modelos, e a diferença entre eles é realmente o tipo de controles que estão sendo utilizados. O modelo um é um GWAS de casos de tentativa de suicídio com um transtorno psiquiátrico específico versus não tentativas com o mesmo transtorno, que é um desenho dentro de caso-controle, o mesmo estilo do PGC GWAS. O modelo dois é o GWAS de tentativa de suicídio ou morte versus controles da população em geral. E o modelo 3 é tentativa de suicídio ou morte versus controles não psiquiátricos selecionados, e em ambos os modelos 2 e 3, os controles também são selecionados para tentativa de suicídio, se essa informação estiver disponível. Esses são os números que temos em cada um dos modelos. Portanto, excedemos em muito o tamanho da amostra de qualquer um dos GWAS individuais anteriores sobre suicídio, o que é um ótimo começo. Previmos desde o início que haveria uma diferença no poder estatístico entre estes modelos, com maior poder dos modelos 2 e 3, não só devido ao tamanho da amostra, mas também à diferença fenotípica entre casos e controles nestes dois modelos.

Uma limitação do modelo 3, que é o modelo caso versus modelo de controle triado, é distinguir se alguma associação é realmente devido ao suicídio ou se pode refletir responsabilidade genética para transtornos psiquiátricos. Mas procuraremos a convergência de evidências entre os modelos, e o modelo 1 foi concebido para distinguir entre esses cenários. Então, estamos usando esses três modelos para aproveitar todos os dados que pudermos para acelerar a descoberta e complementar uns aos outros.

A maioria dos casos do estudo é de tentativa de suicídio, alguns de morte por suicídio, mas não incluímos indivíduos com pensamentos suicidas apenas no grupo de casos. No que diz respeito à constatação da tentativa de suicídio, a maioria dos estudos utilizou entrevista psiquiátrica. Todos os colaboradores realizaram o GWAS em sua própria amostra. É um GWAS dentro da ancestralidade sob o modelo apropriado, dependendo do tipo de controles que possuem. Todos nós usamos um protocolo de análise padronizado que criamos para minimizar a heterogeneidade nas análises. As estatísticas resumidas do GWAS foram compartilhadas dentro do consórcio, e realizamos uma meta-análise em todos os estudos, independentemente da ascendência, dentro de cada um dos três modelos. Então, esses são os nossos dados e esta é a nossa configuração. Somos um consórcio bastante novo e temos um grande plano de análise pela frente.

Estes são os resultados preliminares dos três modelos:

-   Existem seis loci significativos, todos eles do modelo 2 ou 3.

-   Houve herdabilidade significativa do SNP no modelo dois em 6% e 13% no modelo de casos versus controles selecionados.

-   No modelo 1, não havia SNPs significativos, e apenas uma sugestão de herdabilidade do SNP, que não era significativa. Portanto, como antecipamos, o modelo um provavelmente tem o menor poder dos três.

Os rótulos dos genes aqui são apenas o gene mais próximo do índice SNP. Algumas dessas regiões já foram associadas a transtornos psiquiátricos, como o MHC e o SHANK2. Portanto, temos análises secundárias em andamento para realmente aprofundar esses loci e dissecar ainda mais esses resultados usando também métodos poligênicos. Então, observe este espaço. Teremos uma apresentação no próximo mês no Congresso Mundial de Genética Psiquiátrica, por isso estamos ansiosos para compartilhar mais resultados. Também estamos muito entusiasmados com o fato de haver pela primeira vez uma sessão inteira sobre a genética do suicídio, então acho que isso é um sinal de todo o trabalho que está sendo feito nessa área. Todos estes são membros do ISGC com quem temos trabalhado juntos ao longo do último ano para colocar este estudo em funcionamento, e se alguém mais quiser se envolver, sinta-se à vontade para nos enviar um e-mail.

**Eli Stahl:** Obrigado, Niamh. Gostaríamos de responder a quaisquer perguntas, talvez inicialmente especificamente para Niamh, e depois abri-las para qualquer um dos palestrantes. Existem duas perguntas. Levante a mão como participante e poderei ativar seu som para participar da conversa. Ou você pode digitar uma pergunta na caixa de diálogo de perguntas e respostas ou na caixa de diálogo de bate-papo.

Então, há duas perguntas. Um está na caixa de bate-papo de Dave Curtis. Dave, devo ativar seu som e permitir que você faça sua pergunta. Vejamos, acredito que preciso tentar ativar seu som. Eu não sou capaz de fazer isso.

**David Curtis**: Eu estava apenas supondo, ideia sobre, você pega, você tem uma pessoa com diagnóstico de depressão e diz que alguns têm um suicídio, outros não, mas embora eles, todos eles tenham depressão, pode ser que os tentadores tenham uma depressão mais grave do que os que não tentaram e, portanto, o que você pode estar percebendo não é realmente uma tendência suicida, mas uma espécie de gravidade depressiva geral. E então, se você estiver recebendo um diagnóstico diferente, esquizofrenia, você pode ter algumas pessoas com esquizofrenia, tendendo a ficar mais ou menos deprimidas, e os mais deprimidos tendem a ser mais suicidas, mas novamente pode, você sabe, eu não tenho certeza se estamos captando algo específico sobre o suicídio ou se não são outras características da psicopatologia, como o quão geralmente alguém está deprimido, quão geralmente desinibido ele é, quão impulsivo ele é, se ele é limítrofe, quanto de uso de substâncias geralmente são, e todas as outras características quantitativas que esperamos variar entre pessoas dentro do mesmo diagnóstico.

**Niamh Mullins**: Sim, ah, isso é definitivamente o que estamos vendo no escore poligênico. Pessoas que tentam suicídio sempre apresentam maior risco genético de depressão, independentemente do transtorno psiquiátrico. E isso está de acordo com o quadro clínico. Por exemplo, a presença de sintomas depressivos na esquizofrenia é um fator de risco para o suicídio, episódios depressivos mais longos no transtorno bipolar são um fator de risco. Descobrimos nos dados do PGC que as pessoas que tentaram suicídio com esquizofrenia apresentavam escores fatoriais mais elevados para depressão. Então, sim, está de acordo com o quadro clínico.

E nossas análises, embora tenham como objetivo tentar separar a genética das tentativas de suicídio em comparação com o transtorno psiquiátrico, e assim poder detectar associações específicas para tentativas de suicídio, mas também, dado o que sabemos sobre a natureza poligênica dessas características, e poligenicidade entre muitos transtornos. Não esperamos necessariamente que todas essas variantes genéticas sejam específicas para tentativas de suicídio, nós esperamos ver alguma sobreposição com outros transtornos. E dentro do modelo de caso de depressão, por exemplo, não só pode captar associações específicas para o suicídio, mas também associações que são pleiotrópicas com a depressão, mas que ocorrem com maior frequência em pessoas que tentam suicídio. E então o que vimos neste estudo e em muitos outros é que o transtorno ao qual a tentativa de suicídio parece estar mais intimamente relacionada geneticamente é a depressão.

**Eli Stahl**: Algum acompanhamento? Então a pergunta do Q&A vem do Adrian Campos. Se Adrian, você mesmo quiser fazer sua pergunta, posso permitir que você ative seu som agora, se desejar.

**Adrian Campos**: Sim, por favor, você pode me ouvir?

**Eli Stahl**: Por favor, faça sua pergunta também.

**Adrian Campos**: Eu estava apenas me perguntando se havia alguma evidência de diferenças na inflação ou no poder entre os diferentes tipos de apuração de tentativa de suicídio. Por exemplo, você mencionou alguns grupos com entrevistas psiquiátricas em vez de usar autorrelato ou registros médicos de saúde.

**Niamh Mullins**: Sim, isso está no estudo do ISGC e temos vários métodos diferentes de apuração. A maioria delas são entrevistas psiquiátricas. Alguns estudos fizeram recrutamento on-line ou autorrelato. Alguns estudos utilizaram registros hospitalares como códigos CID. Então, sim, há possivelmente alguma heterogeneidade na definição do fenótipo a partir de diferentes métodos de determinação, e pretendemos investigar isso. Por exemplo, poderíamos observar as correlações genéticas entre as diferentes coortes, dependendo dos diferentes métodos de determinação, e certamente examinaremos isso. Um desafio em fazer isso é o poder estatístico do tamanho da amostra para fazer análises de correlação genética para cada uma das coortes individualmente, e isso representa um desafio para testar isso.

**Adrian Campos:** Tudo bem obrigado.

**Eli Stahl**: Obrigado. Estamos na hora. Não tenho certeza do que aconteceu às 11 horas, mas se houver outras dúvidas, talvez ainda reste um pouquinho de tempo. E se não, gostaria de agradecer a todos novamente por participarem da reunião PGC Worldwide Lab: Insights na Genética do Suicídio. Obrigado e tenha um bom dia.

------------------------------------------------------------------------

# ***Síndrome de Tourette*** {#sec-tourette}

**Título**: Genética da Síndrome de Tourette

**Apresentador**: Matt Halvorsen, PhD (Department of Genetics, University of North Carolina School of Medicine)

**Matt Halvorsen:**

Olá pessoal. Meu nome é Matt Halvorsen e hoje farei uma apresentação sobre a genética da síndrome de Tourette.

Então, primeiro, uma definição de síndrome de Tourette ou TS. Pertence a um espectro de condições de neurodesenvolvimento, conhecidas como transtornos de tiques, e isso vem do Manual Diagnóstico e Estatístico de Transtornos Mentais, ou DSM, Quinta Edição. Primeiro, vamos definir os tiques. Os tiques são definidos como movimentos motores ou vocalizações súbitas, rápidas e recorrentes, e o critério básico para o diagnóstico de TS é ter tiques motores e vocais presentes há pelo menos um ano. Outros transtornos de tiques importantes a serem lembrados são o transtorno de tiques crônico ou CTD. A característica do CTD são basicamente tiques motores ou vocais, mas não ambos, com duração de pelo menos um ano. Portanto, os transtornos de tiques têm um amplo espectro.

Prevalência de TS e comorbidades. A prevalência mundial estimada de TS está na faixa de 0,3% a 1% em crianças. Comorbidades psiquiátricas. Os casos de TS são mais frequentemente diagnosticados com transtorno obsessivo-compulsivo, ou OCD - que representa 50% dos casos - e transtorno de déficit de atenção e hiperatividade, ou ADHD - em 54% dos casos.

Breve história da síndrome de Tourette. Descrito pela primeira vez e nomeado em homenagem a Georges Albert Edouard Brutus Gilles de la Tourette em 1885. Ele descreveu a condição em nove pacientes separados, mas mesmo antes disso, tiques foram descritos em indivíduos já no século XV. Destaquei aqui o livro Malleus Maleficarum, que se traduz como 'Martelo das Bruxas' e é basicamente uma enciclopédia de bruxaria escrita naquela época. E nele é descrito o caso de um padre que tem tiques e eles culpam a possessão demoníaca. Hoje em dia temos, em vez de pilhas de livros do Malleus Maleficarum, pilhas de livros do DSM-5. E nesses livros, tanto os tiques quanto a ST são reconhecidos como tendo origem no neurodesenvolvimento, e não como alguma origem supersticiosa.

Então, que evidências temos de que a síndrome de Tourette tem um grande componente genético? Bem, a evidência de primeira linha vem de estudos com gêmeos. E em estudos com gêmeos, o que fazemos é pegar gêmeos e determinar, você sabe, nos casos em que um deles tem um transtorno como a síndrome de Tourette, com que frequência o outro gêmeo tem esse transtorno? E assim você obtém essas taxas de concordância que variam de 0 a 1; se os valores forem 0, então basicamente não há contribuição genética para o risco, e se o valor for 1, então a genética explica inteiramente o risco. Portanto, essas estimativas que listamos aqui não são as primeiras derivadas para a síndrome de Tourette, mas são uma das mais recentes. Esta é uma grande meta-análise de estudos com gêmeos e apresenta vários transtornos e características diferentes em termos desses valores de concordância, mas aqui vamos nos concentrar apenas nos valores de TS. Gêmeos monozigóticos, esta estimativa de concordância, e quando digo monozigóticos quero dizer gêmeos idênticos, então a estimativa aqui é 0,63, e então gêmeos dizigóticos, então gêmeos que não são idênticos, basicamente irmãos, essa estimativa é 0,34. Portanto, com base neste e em outros estudos com gêmeos mais especificamente focados na TS, parecem explicar uma grande parte, mas não todo, do risco de TS e de transtornos de tiques em geral.

Portanto, outra linha de evidência são os estudos familiares mais generalizados. E assim, quando falamos de estudos familiares, por exemplo, estamos falando sobre obter dados de registro em escala populacional, encontrar indivíduos com síndrome de Tourette e, em seguida, encontrar seus parentes nos dados e dizer: “Ok, são os indivíduos que são parentes de primeiro grau, segundo grau, terceiro grau... se você é parente de primeiro grau de alguém com TS ou CTD, é mais provável que você seja um caso de TS ou CTD?” E dois estudos diferentes publicados nos últimos dois anos. Um focado no registro sueco, outro focado no registro dinamarquês, relatam que por ser um parente de primeiro grau, sim, sua probabilidade de ser um caso se seu parente de primeiro grau de um caso de TS/CTD sobe muito e eles ambos também relatam elevações de risco de seu parente de segundo grau ou de um parente de terceiro grau de um caso de TS/CTD. Então, em resumo, o que estamos vendo aqui nestes estudos separados focados em diferentes populações é essencialmente o agrupamento de diagnósticos de TS e CTD dentro de famílias de uma população. E isto é consistente com uma contribuição genética significativa para o risco, portanto, dado que os estudos de base familiar apoiam uma contribuição genética, a próxima questão é: podemos identificar variações genéticas específicas que contribuem para o risco de TS? Poderíamos fazer isso utilizando tecnologias modernas de genotipagem e sequenciamento de DNA para obter dados genéticos, e então poderemos realizar estudos formais de caso-controle em grande escala sobre os dados obtidos. Então eu acho que qual é o sentido de fazer isso? Então são dois. Uma delas é ser capaz de avaliar os perfis de risco genético da TS por paciente, e o outro ponto é produzir um mapa de genes cuja atividade é afetada na TS. Isso nos ajudará a entender muito melhor a TS e a tratá-la muito melhor, potencialmente em uma resolução específica do paciente.

Então, em termos do trabalho que foi feito até agora, primeiro falarei um pouco sobre estudos de associação genômica em larga escala, ou GWAS, de TS. E quando falamos sobre GWAS, estamos falando neste caso principalmente sobre variantes que são comuns em uma população e o que procuramos é casos em que variantes são encontradas em um grau significativo em casos mais frequentemente do que os controles. E quando digo significativo, isso significa controlar se você está olhando para 7 milhões de variantes que são comuns, cada uma delas é um teste e você tem que ajustar seu limite de significância com base no número de testes realizados. Então, esse é o limite de significância, por assim dizer, que a variante tem que passar para ser significativa. O estudo mais recente é de 2019, temos 4.800 casos e 9.500 controles e há apenas um locus significativo em todo o genoma. E quando eles tentam ver se isso se replica em uma coorte separada de cerca de 1.000 casos e 6.000 controles, eles não conseguem ver uma diferença significativa entre casos e controles em uma coorte separada e, infelizmente, isso é uma espécie de requisito padrão para implicar uma variante em uma característica ou doença é ver se em uma coorte separada você vê a mesma coisa.

Portanto, descobertas adicionais. Um ponto crítico é a contribuição total da variante comum para a herdabilidade da TS. Foram produzidas duas estimativas diferentes para esta contribuição total. Um é para um subconjunto de casos com maior depleção de histórico familiar e o outro é para indivíduos com maior enriquecimento de histórico familiar. E o que eles viram é que, em termos da contribuição total para a herdabilidade da TS a partir de variantes comuns, sabemos que há uma contribuição notável em casos com depleção de histórico familiar, e o número é um pouco maior em casos com histórico familiar enriquecido, onde podemos ter irmãos que também têm síndrome de Tourette. Então isso sugeriria que essas famílias onde seus múltiplos afetados têm uma carga maior de riscos genéticos provenientes de variação comum.

E outra coisa é que as pessoas que elaboraram este artigo também foram capazes de calcular o que chamam de escore poligênico de risco para a síndrome de Tourette em amostras separadas, fora da coorte de caso-controle que analisaram. E eles descobriram que era preditivo do status do caso de Tourette, do status do caso de CTD e - esta parte é muito importante - da pior gravidade de tique já registrada. Então, eles são realmente capazes de usar PRS para prever o quão ruins são os tiques por indivíduo, então é como tratá-los como um verdadeiro tipo de característica quantitativa, em vez de você ter Tourette ou não ter Tourette.

Então, vamos ver, a seguir falaremos sobre estudos de variantes raras que foram feitos em TS. Então, primeiros estudos de variantes de número de cópias raras, ou estudos CNV, de TS. CNVs, resumidamente, são definidas como deleções ou duplicações da sequência de DNA no genoma. Eles tendem a ser um pouco mais raros e deletérios, e por isso faz sentido focar neles em termos de sua contribuição para o risco genético da síndrome de Tourette. No artigo mais recente, Huang et al., 2018, apresenta cerca de 2.400 casos e cerca de 4.000 controles. Eles implicaram duas CNVs raras específicas separadas com risco de Tourette, e estima-se que você encontraria essas CNVs específicas em cerca de 1% do total de casos de TS. Uma delas são as deleções que se sobrepõem ao gene NRXN1 e a outra são as duplicações que se sobrepõem ao gene CNTN6. De forma mais geral, eles observaram que, em geral, os casos têm um excesso de CNVs em relação aos controles, especificamente CNVs muito grandes. Presumivelmente, quanto maior a CNV, mais prejudicial será – irá deletar ou duplicar mais genes no processo. E também, há um excesso nos caso em relação aos controles de CNVs patogênicas relatadas anteriormente, então tudo isso é consistente com uma contribuição de CNVs para o risco de Tourette e provavelmente convergindo para genes de risco específicos de Tourette.

Portanto, outro tipo de desenho de estudo de variante rara que tem sido muito usado é o sequenciamento completo do exoma. O sequenciamento completo do exoma envolve o sequenciamento de 1% do genoma humano que codifica proteínas e outra coisa a ser observada sobre esses estudos é que eles são frequentemente chamados de “baseados em trio”. O objetivo aqui acaba por ser identificar variantes que estão presentes no caso de TS e ausentes em ambos os progenitores, este tipo de variantes chamamos variantes de novo e são geralmente o foco destes estudos de exoma, em particular os estudos de Tourette sobre o qual falaremos. Então vou mencionar dois. Um deles é de Willsey et al., 2017, eles identificaram um gene de risco que podemos destacar aqui, que é o WWC1. Um artigo mais recente, um ano depois, Wang et al., 2018, identificou um gene de risco adicional CELSR3. O que é fundamental é que, em ambos, eles relatam variantes de novo prejudiciais em excesso em relação aos controles. Mencionarei brevemente, também, que quando olham para famílias que têm múltiplos afetados, estas chamadas famílias multiplex, na verdade não veem esse excesso em relação aos controles. E a conclusão é que estamos falando de risco poligênico, você sabe que a carga de variantes comuns nessas famílias multiplex é maior. O que isto sugere aqui é que nessas famílias, o risco de variante comum, a carga da variância comum, é maior, mas nestas variantes raras ou de novo, a sua carga é menor nestas famílias. Portanto, variantes raras podem ter mais influência nessas famílias simplex sem histórico familiar, e a carga de variantes comuns pode ter mais influência em famílias multiplex com múltiplos afetados. Em geral, os resultados da CNV e do WES sugerem que variantes raras podem ser utilizadas para identificar genes de risco específicos para TS e que há mais para serem encontradas.

Então, a próxima análise genética de TS deve ser destacada. GWAS, há uma análise sendo montada agora, a coorte total inclui 13.500 casos e pelo menos 50.000 controles. CNV, também temos uma análise sendo montada agora e esta incluirá mais de 10.000 casos e pelo menos 20.000 controles. Portanto, um aumento substancial no tamanho da amostra em relação aos estudos que descrevemos aqui antes, e o tamanho da amostra deve ser adequado para a descoberta de variantes de risco para ambos os estudos.

Então resumo. A TS é uma condição do neurodesenvolvimento definida pela presença de tiques vocais e motores persistentes que duram pelo menos um ano. Consistente com uma contribuição da genética para o diagnóstico de TS e CTD, são altamente concordantes entre pares de gêmeos e agrupam-se dentro de famílias em grandes populações. Vemos que variantes genéticas comuns explicam uma parte da herdabilidade da característica TS em casos relativos a controles não-TS e também vemos que os casos de TS são enriquecidos para variantes raras que danificam genes codificadores de proteínas. Obrigado por ouvir.
