---
title: "Conditional Analysis"
---

> In this tutorial, Dr. Zhu gives an overview of performing conditional analyses with multi-trait conditional and joint analysis (mtCOJO), which allows for testing causality and adjusting for confounding using GWAS summary statistics, and allows for discovery of disorder-specific associations through conditioning on multiple traits.
>
> A description of mtCOJO from Dr. Zhu:
>
> *"Mendelian randomization provides a way to test for causality using GWAS results from the putative causal trait and from the outcome. However, in testing these relationships, we may wish to account for other confounding factors. If we had individual-level data, we could account for confounding factors through their inclusion as covariates. mtCOJO is a method that allows us to condition on confounding factors when we only have GWAS summary statistics. The conditional GWAS allows us to investigate causal relationships free from the bias of confounding factors."*

# mtCOJO

**Title**: How to perform mtCOJO

**Presenter(s)**: Zhihong Zhu, PhD (National Centre for Register-Based Research, Aarhus University)

**Level**: Intermediate

**Length**: 14:51

```{r, echo=FALSE}
library("vembedr")
embed_url("https://www.youtube.com/watch?v=bkHvJ3fTew0")
```

Link to video transcript [here](software_conditional_transcript.qmd#sec-video1).

Link to [mtCOJO website](https://yanglab.westlake.edu.cn/software/gcta/#mtCOJO).
